load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "workspace",
    srcs = [
        "invoke.go",
        "runscript.go",
        "workspace.go",
    ],
    importpath = "codeberg.org/ramilmsh/grpcview/service/workspace",
    visibility = ["//visibility:public"],
    deps = [
        "//inspector",
        "//proto/grpcview/v1:grpcview",
        "//service/scripting",
        "//service/store",
        "@com_connectrpc_connect//:connect",
        "@com_github_jhump_protoreflect//desc",
        "@com_github_jhump_protoreflect//dynamic",
        "@com_github_jhump_protoreflect//dynamic/grpcdynamic",
        "@com_github_jhump_protoreflect//grpcreflect",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials",
        "@org_golang_google_grpc//credentials/insecure",
        "@org_golang_google_grpc//metadata",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//types/known/durationpb",
        "@org_golang_google_protobuf//types/known/structpb",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)
