load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "workspace",
    srcs = [
        "invoke.go",
        "middleware.go",
        "runscript.go",
        "workspace.go",
    ],
    importpath = "codeberg.org/ramilmsh/grpcview/service/workspace",
    visibility = ["//visibility:public"],
    deps = [
        "//proto/grpcview/v1:grpcview",
        "//service/scripting",
        "//service/store",
        "@com_connectrpc_connect//:connect",
        "@com_github_jhump_protoreflect//desc",
        "@com_github_jhump_protoreflect//dynamic",
        "@com_github_jhump_protoreflect//dynamic/grpcdynamic",
        "@com_github_jhump_protoreflect//grpcreflect",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials",
        "@org_golang_google_grpc//credentials/insecure",
        "@org_golang_google_grpc//metadata",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//runtime/protoiface",
        "@org_golang_google_protobuf//types/descriptorpb",
        "@org_golang_google_protobuf//types/known/durationpb",
        "@org_golang_google_protobuf//types/known/structpb",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)

go_test(
    name = "workspace_test",
    srcs = [
        "body_test.go",
        "invoke_history_test.go",
        "invoke_streaming_test.go",
        "metadata_test.go",
        "middleware_test.go",
        "resolve_target_test.go",
        "scripts_test.go",
        "workspace_test.go",
    ],
    embed = [":workspace"],
    deps = [
        "//proto/grpcview/v1:grpcview",
        "//service/echo",
        "//service/scripting",
        "//service/store",
        "@com_connectrpc_connect//:connect",
        "@com_github_jhump_protoreflect//desc",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//health",
        "@org_golang_google_grpc//health/grpc_health_v1",
        "@org_golang_google_grpc//reflection",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protoregistry",
        "@org_golang_google_protobuf//types/known/structpb",
    ],
)
