load("@aspect_rules_ts//ts:defs.bzl", "ts_config")
load("//ui:defs.bzl", "ts_project")

ts_project(
    name = "sources",
    srcs = [
        "AddSourceModal.tsx",
        "SourcesView.tsx",
        "source-row.tsx",
    ],
    declaration = True,
    no_emit = False,
    preserve_jsx = False,
    resolve_json_module = True,
    tsconfig = ":tsconfig",
    visibility = ["//visibility:public"],
    deps = [
        "//grpcview/v1:grpcviewv1_proto_ts",
        "//ui:node_modules/@types/react",
        "//ui:node_modules/react",
        "//ui/src/components/ui",
        "//ui/src/lib",
    ],
)

ts_project(
    name = "sources_tests",
    testonly = True,
    srcs = [
        "add-source-modal.test.tsx",
        "source-row.test.tsx",
    ],
    declaration = True,
    no_emit = False,
    preserve_jsx = False,
    resolve_json_module = True,
    tsconfig = ":tsconfig",
    deps = [
        ":sources",
        "//grpcview/v1:grpcviewv1_proto_ts",
        "//ui:node_modules/@types/node",
        "//ui:node_modules/@types/react",
        "//ui:node_modules/@types/react-dom",
        "//ui:node_modules/expect",
        "//ui:node_modules/react",
        "//ui:node_modules/react-dom",
    ],
)

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
    visibility = [":__subpackages__"],
    deps = [
        "//ui:node_modules/@types/node",
        "//ui:tsconfig",
    ],
)
