load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "dev_lib",
    srcs = ["main.go"],
    importpath = "github.com/ramilmsh/grpcview/service/cmd/dev",
    visibility = ["//visibility:public"],
    deps = ["//service"],
)

go_binary(
    name = "dev",
    embed = [":dev_lib"],
    visibility = ["//visibility:public"],
)
