load("@npm//:defs.bzl", "npm_link_all_packages")
load("@npm//frontend:vite/package_json.bzl", vite_bin = "bin")

npm_link_all_packages(name = "node_modules")

filegroup(
    name = "src",
    srcs = glob(["src/**/*"]),
)

BUILD_DEPS = [":node_modules/" + d for d in [
    "@types/node",
    "@bufbuild/protobuf",
    "@connectrpc/connect",
    "@connectrpc/connect-web",
    "monaco-editor",
    "vue",
    "pinia",
    "pinia-plugin-persistedstate",
    "vue-router",
    "vite",
    "@vitejs/plugin-vue",
    "@vue/tsconfig",
    "typescript",
    "vite-plugin-singlefile",
    "vite-plugin-vue-devtools",
    "vue-tsc",
]]

DATA = BUILD_DEPS + [
    "env.d.ts",
    "package.json",
    "tsconfig.json",
    "vite.config.ts",
    "index.html",
    ":src",
    "//service/proto/v1:grpcviewv1_ts_proto",
]

vite_bin.vite(
    name = "frontend",
    srcs = DATA,
    outs = ["dist/index.html"],
    args = [
        "build",
        "--mode=development",
    ],
    chdir = package_name(),
    visibility = ["//visibility:public"],
)

vite_bin.vite_binary(
    name = "dev",
    chdir = package_name(),
    data = DATA,
    tags = ["ibazel_notify_changes"],
)
