load("@npm//:defs.bzl", "npm_link_all_packages")
load("@npm//:vite/package_json.bzl", vite_bin = "bin")

npm_link_all_packages(name = "node_modules")

filegroup(
    name = "srcs",
    srcs = glob(
        [
            "src/**/*",
            "static/**/*",
        ],
        allow_empty = True,
    ),
)

BUILD_DEPS = [":node_modules/" + d for d in [
    "@sveltejs/adapter-static",
    "@sveltejs/kit",
    "@sveltejs/vite-plugin-svelte",
    "svelte",
    "svelte-check",
    "typescript",
    "vite",
    "@bufbuild/protobuf",
    "@connectrpc/connect",
    "@connectrpc/connect-web",
    "monaco-editor",
]]

DATA = [
    ".npmrc",
    "package.json",
    "svelte.config.js",
    "tsconfig.json",
    "vite.config.ts",
    ":srcs",
] + BUILD_DEPS

vite_bin.vite(
    name = "frontend",
    srcs = DATA,
    outs = ["build/index.html"],
    args = ["build"],
    chdir = package_name(),
    visibility = ["//visibility:public"],
)

vite_bin.vite_binary(
    name = "serve",
    args = ["serve"],
    chdir = package_name(),
    data = DATA,
    tags = ["ibazel_notify_changes"],
)
