load("@aspect_rules_esbuild//esbuild:defs.bzl", "esbuild")
load("//ui:defs.bzl", "ts_project")

ts_project(
    name = "theme",
    srcs = [
        "monaco-theme.ts",
        "theme.json",
    ],
    declaration = True,
    no_emit = False,
    preserve_jsx = False,
    resolve_json_module = True,
    tsconfig = "//ui:tsconfig",
    visibility = ["//visibility:public"],
    deps = [
        "//ui:node_modules/@monaco-editor/react",
        "//ui:node_modules/monaco-editor",
    ],
)

esbuild(
    name = "theme_css",
    srcs = [
        "app-tokens.css",
        "fonts.css",
        "nocturne.css",
    ] + glob(["fonts/**"]),
    bazel_sandbox_plugin = False,
    config = "esbuild.config.mjs",
    entry_point = "theme.css",
    output = "dist/theme.css",
    platform = "browser",
    visibility = ["//ui/src:__pkg__"],
)
