load("@bazel_env.bzl", "bazel_env")
load("@multitool//:tools.bzl", "TOOLS")
load("@npm//:defs.bzl", "npm_link_all_packages")

npm_link_all_packages(name = "node_modules")

bazel_env(
    name = "bazel_env",
    tools = {
        "buildifier": "@buildifier_prebuilt//:buildifier",
        "buildozer": "@buildozer//:buildozer",
        "buf": "@rules_buf_toolchains//:buf",
        "pnpm": "@pnpm//:pnpm",
        "go": "@rules_go//go",
        "gazelle": "//tools:gazelle",
        "starpls": TOOLS["starpls"],
    },
)

# gazelle:go_grpc_compilers @rules_go//proto:go_proto,//tools:connect_go_proto_compiler
# gazelle:go_proto_compilers @rules_go//proto:go_proto,//tools:connect_go_proto_compiler

# gazelle:exclude **/*_pb.d.ts
# gazelle:exclude **/*_connect.d.ts
# gazelle:exclude **/*_connectquery.d.ts

# gazelle:exclude demo/**

# gazelle:js_visibility //visibility:public

# gazelle:resolve proto proto google/api/annotations.proto                   @googleapis//google/api:annotations_proto
# gazelle:resolve proto go    google/api/annotations.proto                   @org_golang_google_genproto_googleapis_api//annotations
# gazelle:resolve proto proto google/api/client.proto                        @googleapis//google/api:client_proto
# gazelle:resolve proto go    google/api/client.proto                        @org_golang_google_genproto_googleapis_api//annotations
# gazelle:resolve proto proto google/api/http.proto                          @googleapis//google/api:http_proto
# gazelle:resolve proto go    google/api/http.proto                          @org_golang_google_genproto_googleapis_api//annotations
# gazelle:resolve proto proto google/api/field_behavior.proto                @googleapis//google/api:field_behavior_proto
# gazelle:resolve proto go    google/api/field_behavior.proto                @org_golang_google_genproto_googleapis_api//annotations
# gazelle:resolve proto proto google/api/httpbody.proto                      @googleapis//google/api:httpbody_proto
# gazelle:resolve proto go    google/api/httpbody.proto                      @org_golang_google_genproto_googleapis_api//httpbody
# gazelle:resolve proto proto google/api/visibility.proto                    @googleapis//google/api:visibility_proto
# gazelle:resolve proto go    google/api/visibility.proto                    @org_golang_google_genproto_googleapis_api//visibility
# gazelle:resolve proto proto google/rpc/code.proto                          @googleapis//google/rpc:code_proto
# gazelle:resolve proto go    google/rpc/code.proto                          @org_golang_google_genproto_googleapis_rpc//code
# gazelle:resolve proto proto google/rpc/status.proto                        @googleapis//google/rpc:status_proto
# gazelle:resolve proto go    google/rpc/status.proto                        @org_golang_google_genproto_googleapis_rpc//status
