load("@bazel_env.bzl", "bazel_env")
load("@multitool//:tools.bzl", "TOOLS")
load("@npm//:defs.bzl", "npm_link_all_packages")

npm_link_all_packages(name = "node_modules")

# buf.yaml: every proto_library implicitly depends on it (lint_buf_aspect's default
# config location). .shellcheckrc: referenced by //tools/lint:linters.bzl's shellcheck
# aspect.
exports_files([
    "buf.yaml",
    ".shellcheckrc",
    "MODULE.bazel",
])

alias(
    name = "format",
    actual = "//tools/format",
)

alias(
    name = "format.check",
    actual = "//tools/format:format.check",
)

bazel_env(
    name = "bazel_env",
    tools = {
        "buildifier": "@buildifier_prebuilt//:buildifier",
        "buildozer": "@buildozer//:buildozer",
        "buf": "@rules_buf_toolchains//:buf",
        "pnpm": "@pnpm//:pnpm",
        "go": "@rules_go//go",
        "gazelle": "//tools:gazelle",
        "starpls": TOOLS["starpls"],
    },
)

# gazelle:go_grpc_compilers @rules_go//proto:go_proto,//tools:connect_go_proto_compiler
# gazelle:go_proto_compilers @rules_go//proto:go_proto,//tools:connect_go_proto_compiler

# gazelle:exclude **/*_pb.d.ts
# gazelle:exclude **/*_connect.d.ts
# gazelle:exclude **/*_connectquery.d.ts

# gazelle:exclude demo/**

# gazelle:js_visibility //visibility:public
