load("@aspect_rules_ts//ts:proto.bzl", "ts_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_buf//buf:defs.bzl", "buf_lint_test")
load("@rules_go//proto:def.bzl", "go_proto_library")

proto_library(
    name = "grpcviewstorev1_proto",
    srcs = ["storage.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "@protobuf//:descriptor_proto",
    ],
)

go_proto_library(
    name = "grpcviewstorev1_go_proto",
    compilers = [
        "@rules_go//proto:go_proto",
        "//tools:connect_go_proto_compiler",
    ],
    importpath = "codeberg.org/ramilmsh/grpcview/grpcview/store/v1",
    proto = ":grpcviewstorev1_proto",
    visibility = ["//visibility:public"],
)

ts_proto_library(
    name = "grpcviewstorev1_proto_ts",
    node_modules = "//:node_modules",
    proto = ":grpcviewstorev1_proto",
    proto_srcs = ["storage.proto"],
)

buf_lint_test(
    name = "grpcviewstorev1_proto_lint",
    config = "//:buf.yaml",
    targets = [":grpcviewstorev1_proto"],
)
