// @generated by protoc-gen-es v2.12.1 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file grpcview/store/v1/storage.proto (package grpcview.store.v1, syntax proto3)
/* eslint-disable */

// Package grpcview.store.v1 is the on-disk schema for a grpcview collection.
// Deliberately distinct from the wire messages in grpcview.v1; see
// service/store/convert.go.

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { FileDescriptorSet } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file grpcview/store/v1/storage.proto.
 */
export declare const file_grpcview_store_v1_storage: GenFile;

/**
 * grpcview.work.json at the workspace root. Optional; a non-empty collections
 * list wins over discovery.
 *
 * @generated from message grpcview.store.v1.Workspace
 */
export declare type Workspace = Message<"grpcview.store.v1.Workspace"> & {
  /**
   * Format version of this file, for forward migration.
   *
   * @generated from field: int32 schema_version = 1;
   */
  schemaVersion: number;

  /**
   * Display name of the workspace.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Workspace-relative paths or globs ("services/*\/requests"); empty means "scan".
   *
   * @generated from field: repeated string collections = 3;
   */
  collections: string[];

  /**
   * Source DEFINITIONS shared by every collection, keyed by the same
   * config-derived id. A SET, not an order: precedence is per collection. May
   * not be an Upload, and commit_descriptors here is ignored.
   *
   * @generated from field: repeated grpcview.store.v1.DescriptorSource sources = 4;
   */
  sources: DescriptorSource[];

  /**
   * What a new collection in this workspace starts from.
   *
   * @generated from field: grpcview.store.v1.Defaults defaults = 5;
   */
  defaults?: Defaults | undefined;

  /**
   * Bazel invocation settings shared by every collection's Bazel sources.
   *
   * @generated from field: grpcview.store.v1.BazelConfig bazel = 6;
   */
  bazel?: BazelConfig | undefined;
};

/**
 * Describes the message grpcview.store.v1.Workspace.
 * Use `create(WorkspaceSchema)` to create a new message.
 */
export declare const WorkspaceSchema: GenMessage<Workspace>;

/**
 * Bazel invocation settings shared by every collection's Bazel sources.
 *
 * @generated from message grpcview.store.v1.BazelConfig
 */
export declare type BazelConfig = Message<"grpcview.store.v1.BazelConfig"> & {
  /**
   * Absolute, or relative to the workspace root; empty walks up for MODULE.bazel.
   *
   * @generated from field: string root = 1;
   */
  root: string;

  /**
   * Caps one build; 0 means the default (600).
   *
   * @generated from field: int32 timeout_seconds = 2;
   */
  timeoutSeconds: number;
};

/**
 * Describes the message grpcview.store.v1.BazelConfig.
 * Use `create(BazelConfigSchema)` to create a new message.
 */
export declare const BazelConfigSchema: GenMessage<BazelConfig>;

/**
 * What a NEW collection in this workspace starts from.
 *
 * @generated from message grpcview.store.v1.Defaults
 */
export declare type Defaults = Message<"grpcview.store.v1.Defaults"> & {
  /**
   * Definition ids seeded as bare references; an unmatched id is skipped.
   *
   * @generated from field: repeated string sources = 1;
   */
  sources: string[];
};

/**
 * Describes the message grpcview.store.v1.Defaults.
 * Use `create(DefaultsSchema)` to create a new message.
 */
export declare const DefaultsSchema: GenMessage<Defaults>;

/**
 * grpcview.json at the collection root; doubles as the root folder's config.
 *
 * @generated from message grpcview.store.v1.Collection
 */
export declare type Collection = Message<"grpcview.store.v1.Collection"> & {
  /**
   * Format version of this file, for forward migration.
   *
   * @generated from field: int32 schema_version = 1;
   */
  schemaVersion: number;

  /**
   * Display name of the collection.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Ordered root-level slugs.
   *
   * @generated from field: repeated string items = 3;
   */
  items: string[];

  /**
   * Highest priority first.
   *
   * @generated from field: repeated grpcview.store.v1.DescriptorSource sources = 4;
   */
  sources: DescriptorSource[];
};

/**
 * Describes the message grpcview.store.v1.Collection.
 * Use `create(CollectionSchema)` to create a new message.
 */
export declare const CollectionSchema: GenMessage<Collection>;

/**
 * folder.json inside a (non-root) folder directory.
 *
 * @generated from message grpcview.store.v1.Folder
 */
export declare type Folder = Message<"grpcview.store.v1.Folder"> & {
  /**
   * This folder's display name and stable slug.
   *
   * @generated from field: grpcview.store.v1.ItemMeta meta = 1;
   */
  meta?: ItemMeta | undefined;

  /**
   * Ordered child slugs.
   *
   * @generated from field: repeated string items = 2;
   */
  items: string[];

  /**
   * TypeScript module feeding the gv.metadata.inherit() chain; inline UTF-8.
   *
   * @generated from field: string draft_metadata_script = 3;
   */
  draftMetadataScript: string;
};

/**
 * Describes the message grpcview.store.v1.Folder.
 * Use `create(FolderSchema)` to create a new message.
 */
export declare const FolderSchema: GenMessage<Folder>;

/**
 * request.json inside a request directory. The body and the metadata script are
 * NOT here: they are sibling body.ts / metadata.ts files, so they diff by line and
 * work as esbuild entry points. See docs/design/shipped/vscode/phase-2-body-files.md.
 *
 * @generated from message grpcview.store.v1.Request
 */
export declare type Request = Message<"grpcview.store.v1.Request"> & {
  /**
   * This request's display name and stable slug.
   *
   * @generated from field: grpcview.store.v1.ItemMeta meta = 1;
   */
  meta?: ItemMeta | undefined;

  /**
   * Fully qualified service name this request calls.
   *
   * @generated from field: string service = 2;
   */
  service: string;

  /**
   * Method name on `service` this request calls.
   *
   * @generated from field: string method = 3;
   */
  method: string;

  /**
   * Ordered display names of the MIDDLEWARE scripts run before the call.
   *
   * @generated from field: repeated string middleware = 6;
   */
  middleware: string[];

  /**
   * Unset means "use the workspace's first reflection source" (resolveTarget).
   *
   * @generated from field: grpcview.store.v1.Target target = 9;
   */
  target?: Target | undefined;
};

/**
 * Describes the message grpcview.store.v1.Request.
 * Use `create(RequestSchema)` to create a new message.
 */
export declare const RequestSchema: GenMessage<Request>;

/**
 * Identity block in every managed tree file: the directory name is the stable
 * slug, this is the display name, so a rename never moves a directory.
 *
 * @generated from message grpcview.store.v1.ItemMeta
 */
export declare type ItemMeta = Message<"grpcview.store.v1.ItemMeta"> & {
  /**
   * Display name; the directory name (the slug) is the stable identity, this is not.
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message grpcview.store.v1.ItemMeta.
 * Use `create(ItemMetaSchema)` to create a new message.
 */
export declare const ItemMetaSchema: GenMessage<ItemMeta>;

/**
 * A POINTER plus authored config, never descriptor bytes. List order in
 * Collection is the priority order (earlier wins).
 *
 * @generated from message grpcview.store.v1.DescriptorSource
 */
export declare type DescriptorSource = Message<"grpcview.store.v1.DescriptorSource"> & {
  /**
   * "upload:<file name>", "reflection:<address>[+tls]" or "bazel:<//pkg:target>".
   *
   * @generated from field: string id = 3;
   */
  id: string;

  /**
   * Which kind of source this is.
   *
   * @generated from oneof grpcview.store.v1.DescriptorSource.source
   */
  source: {
    /**
     * A human-uploaded FileDescriptorSet.
     *
     * @generated from field: grpcview.store.v1.Upload upload = 1;
     */
    value: Upload;
    case: "upload";
  } | {
    /**
     * A live server reflected over the wire.
     *
     * @generated from field: grpcview.store.v1.Reflection reflection = 2;
     */
    value: Reflection;
    case: "reflection";
  } | {
    /**
     * A Bazel label that builds its own descriptor set.
     *
     * @generated from field: grpcview.store.v1.Bazel bazel = 5;
     */
    value: Bazel;
    case: "bazel";
  } | { case: undefined; value?: undefined };

  /**
   * Write what this resolves to as a committed sidecar under descriptors/
   * instead of the local blob store.
   *
   * @generated from field: bool commit_descriptors = 4;
   */
  commitDescriptors: boolean;
};

/**
 * Describes the message grpcview.store.v1.DescriptorSource.
 * Use `create(DescriptorSourceSchema)` to create a new message.
 */
export declare const DescriptorSourceSchema: GenMessage<DescriptorSource>;

/**
 * A FileDescriptorSet a human handed over. The null-pointer kind: nothing to
 * re-acquire from, so an uncommitted upload's only copy is in local state.
 *
 * @generated from message grpcview.store.v1.Upload
 */
export declare type Upload = Message<"grpcview.store.v1.Upload"> & {
  /**
   * Identity of this upload; re-uploading under the same name refreshes it.
   *
   * @generated from field: string file_name = 1;
   */
  fileName: string;

  /**
   * Root-relative refresh recipe; empty from a browser file picker. Never identity.
   *
   * @generated from field: string path = 2;
   */
  path: string;
};

/**
 * Describes the message grpcview.store.v1.Upload.
 * Use `create(UploadSchema)` to create a new message.
 */
export declare const UploadSchema: GenMessage<Upload>;

/**
 * A build label whose default outputs are descriptor sets — the one kind that can
 * produce its own bytes. Stored canonical ("//pkg:target").
 *
 * @generated from message grpcview.store.v1.Bazel
 */
export declare type Bazel = Message<"grpcview.store.v1.Bazel"> & {
  /**
   * Canonical label, e.g. "//pkg:target".
   *
   * @generated from field: string label = 1;
   */
  label: string;
};

/**
 * Describes the message grpcview.store.v1.Bazel.
 * Use `create(BazelSchema)` to create a new message.
 */
export declare const BazelSchema: GenMessage<Bazel>;

/**
 * descriptors.json in a collection's state directory: LOCAL STATE, the
 * `id -> digest` half of the descriptor store. Covers exactly the sources whose
 * descriptors are NOT committed. The other half is the content-addressed blob
 * (`<state root>/blobs/<sha256>.binpb`), workspace-scoped so five collections
 * share one copy. The two keys stay separate: the id is a stable pointer, which
 * is what makes re-adding a source a refresh; the digest is the content key.
 *
 * @generated from message grpcview.store.v1.DescriptorIndex
 */
export declare type DescriptorIndex = Message<"grpcview.store.v1.DescriptorIndex"> & {
  /**
   * Format version of this file, for forward migration.
   *
   * @generated from field: int32 schema_version = 1;
   */
  schemaVersion: number;

  /**
   * One entry per source that has resolved at least once.
   *
   * @generated from field: repeated grpcview.store.v1.DescriptorIndexEntry entries = 2;
   */
  entries: DescriptorIndexEntry[];
};

/**
 * Describes the message grpcview.store.v1.DescriptorIndex.
 * Use `create(DescriptorIndexSchema)` to create a new message.
 */
export declare const DescriptorIndexSchema: GenMessage<DescriptorIndex>;

/**
 * One resolved source's entry in a DescriptorIndex.
 *
 * @generated from message grpcview.store.v1.DescriptorIndexEntry
 */
export declare type DescriptorIndexEntry = Message<"grpcview.store.v1.DescriptorIndexEntry"> & {
  /**
   * The DescriptorSource.id this entry resolved.
   *
   * @generated from field: string source_id = 1;
   */
  sourceId: string;

  /**
   * sha256 hex of the blob's bytes, and so its file name.
   *
   * @generated from field: string digest = 2;
   */
  digest: string;

  /**
   * Stored, not derived: a reflection server's ListServices is authoritative and
   * narrower than "every service in the descriptor set".
   *
   * @generated from field: repeated string service_names = 3;
   */
  serviceNames: string[];
};

/**
 * Describes the message grpcview.store.v1.DescriptorIndexEntry.
 * Use `create(DescriptorIndexEntrySchema)` to create a new message.
 */
export declare const DescriptorIndexEntrySchema: GenMessage<DescriptorIndexEntry>;

/**
 * What one source last resolved to, and the shape the store hands the layer
 * above either location: the blob plus its index entry, or — with
 * commit_descriptors — the committed <collection>/descriptors/<slug>-<hash>.json.
 * It exists so the merged view can be rebuilt for any mutation without
 * re-dialing, and between refreshes it is the only copy of a source's schema.
 *
 * @generated from message grpcview.store.v1.ResolvedSource
 */
export declare type ResolvedSource = Message<"grpcview.store.v1.ResolvedSource"> & {
  /**
   * The DescriptorSource.id this resolved.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The resolved schema.
   *
   * @generated from field: google.protobuf.FileDescriptorSet descriptor_set = 2;
   */
  descriptorSet?: FileDescriptorSet | undefined;

  /**
   * Narrower than "every service in descriptor_set" — see DescriptorIndexEntry.
   *
   * @generated from field: repeated string service_names = 3;
   */
  serviceNames: string[];
};

/**
 * Describes the message grpcview.store.v1.ResolvedSource.
 * Use `create(ResolvedSourceSchema)` to create a new message.
 */
export declare const ResolvedSourceSchema: GenMessage<ResolvedSource>;

/**
 * A server to reflect schemas from; disk-local, not the wire grpcview.v1.Server.
 *
 * @generated from message grpcview.store.v1.Reflection
 */
export declare type Reflection = Message<"grpcview.store.v1.Reflection"> & {
  /**
   * host:port dial string.
   *
   * @generated from field: string address = 1;
   */
  address: string;

  /**
   * Dial with TLS.
   *
   * @generated from field: bool tls = 2;
   */
  tls: boolean;
};

/**
 * Describes the message grpcview.store.v1.Reflection.
 * Use `create(ReflectionSchema)` to create a new message.
 */
export declare const ReflectionSchema: GenMessage<Reflection>;

/**
 * A per-request invoke destination, independent of the schema source.
 * Structurally like Reflection, kept distinct: different concept.
 *
 * @generated from message grpcview.store.v1.Target
 */
export declare type Target = Message<"grpcview.store.v1.Target"> & {
  /**
   * host:port dial string.
   *
   * @generated from field: string address = 1;
   */
  address: string;

  /**
   * Dial with TLS.
   *
   * @generated from field: bool tls = 2;
   */
  tls: boolean;
};

/**
 * Describes the message grpcview.store.v1.Target.
 * Use `create(TargetSchema)` to create a new message.
 */
export declare const TargetSchema: GenMessage<Target>;

