load("@aspect_bazel_lib//lib:copy_file.bzl", "copy_file")
load("@aspect_rules_esbuild//esbuild:defs.bzl", "esbuild")
load("@npm//ui:tailwindcss/package_json.bzl", tailwindcss_bin = "bin")
load("//ui:defs.bzl", "ts_project")

ts_project(
    name = "src",
    srcs = [
        "App.tsx",
        "main.tsx",
        "vite-env.d.ts",
    ],
    declaration = True,
    no_emit = False,
    preserve_jsx = False,
    resolve_json_module = True,
    tsconfig = "//ui:tsconfig",
    visibility = ["//visibility:public"],
    deps = [
        "//ui:node_modules/@connectrpc/connect-query",
        "//ui:node_modules/@tanstack/react-query",
        "//ui:node_modules/@types/react",
        "//ui:node_modules/@types/react-dom",
        "//ui:node_modules/react",
        "//ui:node_modules/react-dom",
        "//ui/src/components/shell",
        "//ui/src/components/ui",
        "//ui/src/features/daemons",
        "//ui/src/features/scripts",
        "//ui/src/features/sources",
        "//ui/src/features/workspace",
        "//ui/src/lib",
        "//ui/src/theme",
    ],
)

# keep
esbuild(
    name = "app",
    config = "esbuild.config.mjs",
    define = {
        "import.meta.env.PROD": "true",
    },
    entry_point = "main.tsx",
    external = [
        "fs",
        "path",
        "os",
        "crypto",
        "buffer",
        "perf_hooks",
        "source-map-support",
        "inspector",
    ],
    format = "esm",
    minify = True,
    output = "dist/main.js",
    output_css = "dist/main.css",
    platform = "browser",
    target = ["es2020"],
    tsconfig = "//ui:tsconfig",
    visibility = ["//service/cmd:__pkg__"],
    deps = [":src"],
)

# keep
tailwindcss_bin.tailwindcss(
    name = "tailwind_css",
    srcs = [
        "index.css",
        "index.html",
        "postcss.config.js",
        "tailwind.config.js",
        ":src",
        "//ui:node_modules/autoprefixer",
        "//ui:node_modules/tailwindcss",
        "//ui/src/components/shell",
        "//ui/src/components/tree",
        "//ui/src/components/ui",
        "//ui/src/features/daemons",
        "//ui/src/features/scripts",
        "//ui/src/features/sources",
        "//ui/src/features/workspace",
        "//ui/src/lib",
        "//ui/src/theme",
    ],
    outs = ["dist/tailwind.css"],
    args = [
        "-i",
        "index.css",
        "-o",
        "dist/tailwind.css",
        "--config",
        "tailwind.config.js",
        "--postcss",
        "postcss.config.js",
        "--minify",
    ],
    chdir = "ui/src",
)

# keep
copy_file(
    name = "dist_index_html",
    src = "index.html",
    out = "dist/index.html",
)

# keep
filegroup(
    name = "dist",
    srcs = [
        ":app",
        ":dist_index_html",
        ":tailwind_css",
        "//ui/src/theme:theme_css",
        "//ui/src/workers:editor_worker",
        "//ui/src/workers:json_worker",
        "//ui/src/workers:ts_worker",
    ],
    visibility = ["//service/cmd:__pkg__"],
)
