load("@aspect_rules_ts//ts:defs.bzl", "ts_config")
load("//ui:defs.bzl", "ts_project")

ts_project(
    name = "scripts",
    srcs = [
        "NewScriptDialog.tsx",
        "ScriptDetail.tsx",
        "ScriptOutput.tsx",
        "ScriptSidebar.tsx",
        "ScriptsView.tsx",
        "monaco-scripts.ts",
        "script-path.ts",
        "script-starter.ts",
    ],
    declaration = True,
    no_emit = False,
    preserve_jsx = False,
    resolve_json_module = True,
    tsconfig = ":tsconfig",
    visibility = ["//visibility:public"],
    deps = [
        "//grpcview/v1:grpcviewv1_proto_ts",
        "//ui:node_modules/@monaco-editor/react",
        "//ui:node_modules/@types/react",
        "//ui:node_modules/clsx",
        "//ui:node_modules/monaco-editor",
        "//ui:node_modules/react",
        "//ui/src/components/ui",
        "//ui/src/features/scripts/vendor",
        "//ui/src/lib",
        "//ui/src/theme",
    ],
)

ts_project(
    name = "scripts_tests",
    testonly = True,
    srcs = ["script-path.test.ts"],
    declaration = True,
    no_emit = False,
    preserve_jsx = False,
    resolve_json_module = True,
    tsconfig = ":tsconfig",
    deps = [
        ":scripts",
        "//ui:node_modules/@types/node",
        "//ui:node_modules/expect",
    ],
)

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
    visibility = [":__subpackages__"],
    deps = [
        "//ui:node_modules/@types/node",
        "//ui:tsconfig",
    ],
)
