// @generated by protoc-gen-es v2.12.1 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file grpcview/echo/v1/echo.proto (package grpcview.echo.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file grpcview/echo/v1/echo.proto.
 */
export declare const file_grpcview_echo_v1_echo: GenFile;

/**
 * @generated from message grpcview.echo.v1.EchoRequest
 */
export declare type EchoRequest = Message<"grpcview.echo.v1.EchoRequest"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: int32 count = 2;
   */
  count: number;
};

/**
 * Describes the message grpcview.echo.v1.EchoRequest.
 * Use `create(EchoRequestSchema)` to create a new message.
 */
export declare const EchoRequestSchema: GenMessage<EchoRequest>;

/**
 * @generated from message grpcview.echo.v1.EchoResponse
 */
export declare type EchoResponse = Message<"grpcview.echo.v1.EchoResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: int32 index = 2;
   */
  index: number;
};

/**
 * Describes the message grpcview.echo.v1.EchoResponse.
 * Use `create(EchoResponseSchema)` to create a new message.
 */
export declare const EchoResponseSchema: GenMessage<EchoResponse>;

/**
 * @generated from service grpcview.echo.v1.EchoService
 */
export declare const EchoService: GenService<{
  /**
   * @generated from rpc grpcview.echo.v1.EchoService.Unary
   */
  unary: {
    methodKind: "unary";
    input: typeof EchoRequestSchema;
    output: typeof EchoResponseSchema;
  },
  /**
   * @generated from rpc grpcview.echo.v1.EchoService.ServerStream
   */
  serverStream: {
    methodKind: "server_streaming";
    input: typeof EchoRequestSchema;
    output: typeof EchoResponseSchema;
  },
  /**
   * @generated from rpc grpcview.echo.v1.EchoService.ClientStream
   */
  clientStream: {
    methodKind: "client_streaming";
    input: typeof EchoRequestSchema;
    output: typeof EchoResponseSchema;
  },
  /**
   * @generated from rpc grpcview.echo.v1.EchoService.BidiStream
   */
  bidiStream: {
    methodKind: "bidi_streaming";
    input: typeof EchoRequestSchema;
    output: typeof EchoResponseSchema;
  },
}>;

