// @generated by protoc-gen-connect-query v2.2.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file proto/grpcview/v1/service.proto (package grpcview.v1, syntax proto3)
/* eslint-disable */

import { WorkspaceService } from "./service_pb";

/**
 * AddDescriptorSource adds a descriptor source to the workspace, it is used to obtain workspace defitions
 *
 * @generated from rpc grpcview.v1.WorkspaceService.AddDescriptorSource
 */
export const addDescriptorSource: typeof WorkspaceService["method"]["addDescriptorSource"];
/**
 * Get returns the workspace snapshot
 *
 * @generated from rpc grpcview.v1.WorkspaceService.Get
 */
export const get: typeof WorkspaceService["method"]["get"];
/**
 * CreateFolder creates a new folder in the workspace
 *
 * @generated from rpc grpcview.v1.WorkspaceService.CreateFolder
 */
export const createFolder: typeof WorkspaceService["method"]["createFolder"];
/**
 * CreateRequest creates a new request in the workspace
 *
 * @generated from rpc grpcview.v1.WorkspaceService.CreateRequest
 */
export const createRequest: typeof WorkspaceService["method"]["createRequest"];
/**
 * DeleteRequest deletes a request from the workspace
 *
 * @generated from rpc grpcview.v1.WorkspaceService.DeleteRequest
 */
export const deleteRequest: typeof WorkspaceService["method"]["deleteRequest"];
/**
 * UpdateRequest updates a request in the workspace
 *
 * @generated from rpc grpcview.v1.WorkspaceService.UpdateRequest
 */
export const updateRequest: typeof WorkspaceService["method"]["updateRequest"];
