// @generated by protoc-gen-connect-query v2.2.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file proto/grpcview/v1/service.proto (package grpcview.v1, syntax proto3)
/* eslint-disable */

import { WorkspaceService } from "./service_pb";

/**
 * Appends at LOWEST priority, or refreshes in place when the id already exists.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.AddDescriptorSource
 */
export const addDescriptorSource: typeof WorkspaceService["method"]["addDescriptorSource"];
/**
 * @generated from rpc grpcview.v1.WorkspaceService.RemoveDescriptorSource
 */
export const removeDescriptorSource: typeof WorkspaceService["method"]["removeDescriptorSource"];
/**
 * @generated from rpc grpcview.v1.WorkspaceService.RefreshDescriptorSource
 */
export const refreshDescriptorSource: typeof WorkspaceService["method"]["refreshDescriptorSource"];
/**
 * Sets which source wins when several describe the same protos.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.ReorderDescriptorSources
 */
export const reorderDescriptorSources: typeof WorkspaceService["method"]["reorderDescriptorSources"];
/**
 * Moves one source's descriptors between the committed sidecar and the local
 * blob store. Never dials or builds, so committing a source that has never
 * resolved is InvalidArgument.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.SetDescriptorSourceCommit
 */
export const setDescriptorSourceCommit: typeof WorkspaceService["method"]["setDescriptorSourceCommit"];
/**
 * A collection that does not exist is NotFound, never created on demand.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.Get
 */
export const get: typeof WorkspaceService["method"]["get"];
/**
 * Deliberately cheap: reads manifests, never trees. Eagerly Getting every
 * collection instead is the one way to make this design feel slow.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.ListCollections
 */
export const listCollections: typeof WorkspaceService["method"]["listCollections"];
/**
 * Trusts or un-trusts this workspace ROOT, like VS Code's Workspace Trust: a
 * committed bazel label means opening a repo could run arbitrary code. Trust is
 * on the folder, not its content. Revoking un-resolves nothing — only a future
 * build is refused.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.SetWorkspaceTrust
 */
export const setWorkspaceTrust: typeof WorkspaceService["method"]["setWorkspaceTrust"];
/**
 * Lists the workspace's descriptor-set-producing labels, so adding a bazel
 * source can be a pick. Runs `bazel query`, which loads BUILD files, so it is
 * trust-gated: an untrusted workspace gets FailedPrecondition, not an empty list.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.ListBazelTargets
 */
export const listBazelTargets: typeof WorkspaceService["method"]["listBazelTargets"];
/**
 * @generated from rpc grpcview.v1.WorkspaceService.CreateCollection
 */
export const createCollection: typeof WorkspaceService["method"]["createCollection"];
/**
 * @generated from rpc grpcview.v1.WorkspaceService.CreateFolder
 */
export const createFolder: typeof WorkspaceService["method"]["createFolder"];
/**
 * @generated from rpc grpcview.v1.WorkspaceService.CreateRequest
 */
export const createRequest: typeof WorkspaceService["method"]["createRequest"];
/**
 * @generated from rpc grpcview.v1.WorkspaceService.DeleteRequest
 */
export const deleteRequest: typeof WorkspaceService["method"]["deleteRequest"];
/**
 * @generated from rpc grpcview.v1.WorkspaceService.UpdateRequest
 */
export const updateRequest: typeof WorkspaceService["method"]["updateRequest"];
/**
 * @generated from rpc grpcview.v1.WorkspaceService.UpdateFolder
 */
export const updateFolder: typeof WorkspaceService["method"]["updateFolder"];
/**
 * @generated from rpc grpcview.v1.WorkspaceService.MoveItem
 */
export const moveItem: typeof WorkspaceService["method"]["moveItem"];
/**
 * Returns the status, response body, request/response metadata and latency.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.Invoke
 */
export const invoke: typeof WorkspaceService["method"]["invoke"];
/**
 * Reports a status the target returned in the response, never as an error.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.InvokeSaved
 */
export const invokeSaved: typeof WorkspaceService["method"]["invokeSaved"];
/**
 * Answers from already-resolved definitions, so it works with the target down.
 * Doc comments survive only if the winning source carried them.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.DescribeMethod
 */
export const describeMethod: typeof WorkspaceService["method"]["describeMethod"];
/**
 * Uses a fresh isolated instance: no capabilities, no collection state.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.RunScript
 */
export const runScript: typeof WorkspaceService["method"]["runScript"];
/**
 * @generated from rpc grpcview.v1.WorkspaceService.CreateScript
 */
export const createScript: typeof WorkspaceService["method"]["createScript"];
/**
 * @generated from rpc grpcview.v1.WorkspaceService.UpdateScript
 */
export const updateScript: typeof WorkspaceService["method"]["updateScript"];
/**
 * @generated from rpc grpcview.v1.WorkspaceService.DeleteScript
 */
export const deleteScript: typeof WorkspaceService["method"]["deleteScript"];
