// @generated by protoc-gen-es v2.12.1 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file proto/grpcview/v1/service.proto (package grpcview.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { Request_Response, ScriptKind, Server, Workspace } from "./workspace_pb";

/**
 * Describes the file proto/grpcview/v1/service.proto.
 */
export declare const file_proto_grpcview_v1_service: GenFile;

/**
 * @generated from message grpcview.v1.AddDescriptorSourceRequest
 */
export declare type AddDescriptorSourceRequest = Message<"grpcview.v1.AddDescriptorSourceRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * @generated from oneof grpcview.v1.AddDescriptorSourceRequest.source
   */
  source: {
    /**
     * descriptor_set is an uploaded FileDescriptorSet's raw bytes; file_name
     * names it and gives the source its identity.
     *
     * @generated from field: bytes descriptor_set = 2;
     */
    value: Uint8Array;
    case: "descriptorSet";
  } | {
    /**
     * @generated from field: grpcview.v1.Server reflection = 3;
     */
    value: Server;
    case: "reflection";
  } | { case: undefined; value?: undefined };

  /**
   * file_name identifies a descriptor_set upload (e.g. "buf_image.binpb"). It is
   * the upload's identity, so re-uploading a rebuilt file of the same name
   * REFRESHES that source in place instead of adding a second, indistinguishable
   * row. Ignored for the reflection case, which is identified by its address.
   *
   * @generated from field: string file_name = 4;
   */
  fileName: string;
};

/**
 * Describes the message grpcview.v1.AddDescriptorSourceRequest.
 * Use `create(AddDescriptorSourceRequestSchema)` to create a new message.
 */
export declare const AddDescriptorSourceRequestSchema: GenMessage<AddDescriptorSourceRequest>;

/**
 * @generated from message grpcview.v1.AddDescriptorSourceResponse
 */
export declare type AddDescriptorSourceResponse = Message<"grpcview.v1.AddDescriptorSourceResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.AddDescriptorSourceResponse.
 * Use `create(AddDescriptorSourceResponseSchema)` to create a new message.
 */
export declare const AddDescriptorSourceResponseSchema: GenMessage<AddDescriptorSourceResponse>;

/**
 * @generated from message grpcview.v1.RemoveDescriptorSourceRequest
 */
export declare type RemoveDescriptorSourceRequest = Message<"grpcview.v1.RemoveDescriptorSourceRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * id selects the source to remove (DescriptorSource.id).
   *
   * @generated from field: string id = 2;
   */
  id: string;
};

/**
 * Describes the message grpcview.v1.RemoveDescriptorSourceRequest.
 * Use `create(RemoveDescriptorSourceRequestSchema)` to create a new message.
 */
export declare const RemoveDescriptorSourceRequestSchema: GenMessage<RemoveDescriptorSourceRequest>;

/**
 * @generated from message grpcview.v1.RemoveDescriptorSourceResponse
 */
export declare type RemoveDescriptorSourceResponse = Message<"grpcview.v1.RemoveDescriptorSourceResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.RemoveDescriptorSourceResponse.
 * Use `create(RemoveDescriptorSourceResponseSchema)` to create a new message.
 */
export declare const RemoveDescriptorSourceResponseSchema: GenMessage<RemoveDescriptorSourceResponse>;

/**
 * @generated from message grpcview.v1.RefreshDescriptorSourceRequest
 */
export declare type RefreshDescriptorSourceRequest = Message<"grpcview.v1.RefreshDescriptorSourceRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * id selects the source to re-resolve (DescriptorSource.id).
   *
   * @generated from field: string id = 2;
   */
  id: string;
};

/**
 * Describes the message grpcview.v1.RefreshDescriptorSourceRequest.
 * Use `create(RefreshDescriptorSourceRequestSchema)` to create a new message.
 */
export declare const RefreshDescriptorSourceRequestSchema: GenMessage<RefreshDescriptorSourceRequest>;

/**
 * @generated from message grpcview.v1.RefreshDescriptorSourceResponse
 */
export declare type RefreshDescriptorSourceResponse = Message<"grpcview.v1.RefreshDescriptorSourceResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.RefreshDescriptorSourceResponse.
 * Use `create(RefreshDescriptorSourceResponseSchema)` to create a new message.
 */
export declare const RefreshDescriptorSourceResponseSchema: GenMessage<RefreshDescriptorSourceResponse>;

/**
 * @generated from message grpcview.v1.ReorderDescriptorSourcesRequest
 */
export declare type ReorderDescriptorSourcesRequest = Message<"grpcview.v1.ReorderDescriptorSourcesRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * ids is the full set of DescriptorSource.id values in the desired priority
   * order — earlier wins. It must be a permutation of the workspace's current
   * source ids; a missing or unknown id is an error rather than a partial
   * reorder, so a stale client can never silently drop a source.
   *
   * @generated from field: repeated string ids = 2;
   */
  ids: string[];
};

/**
 * Describes the message grpcview.v1.ReorderDescriptorSourcesRequest.
 * Use `create(ReorderDescriptorSourcesRequestSchema)` to create a new message.
 */
export declare const ReorderDescriptorSourcesRequestSchema: GenMessage<ReorderDescriptorSourcesRequest>;

/**
 * @generated from message grpcview.v1.ReorderDescriptorSourcesResponse
 */
export declare type ReorderDescriptorSourcesResponse = Message<"grpcview.v1.ReorderDescriptorSourcesResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.ReorderDescriptorSourcesResponse.
 * Use `create(ReorderDescriptorSourcesResponseSchema)` to create a new message.
 */
export declare const ReorderDescriptorSourcesResponseSchema: GenMessage<ReorderDescriptorSourcesResponse>;

/**
 * @generated from message grpcview.v1.CreateFolderRequest
 */
export declare type CreateFolderRequest = Message<"grpcview.v1.CreateFolderRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;
};

/**
 * Describes the message grpcview.v1.CreateFolderRequest.
 * Use `create(CreateFolderRequestSchema)` to create a new message.
 */
export declare const CreateFolderRequestSchema: GenMessage<CreateFolderRequest>;

/**
 * @generated from message grpcview.v1.CreateFolderResponse
 */
export declare type CreateFolderResponse = Message<"grpcview.v1.CreateFolderResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.CreateFolderResponse.
 * Use `create(CreateFolderResponseSchema)` to create a new message.
 */
export declare const CreateFolderResponseSchema: GenMessage<CreateFolderResponse>;

/**
 * @generated from message grpcview.v1.CreateRequestRequest
 */
export declare type CreateRequestRequest = Message<"grpcview.v1.CreateRequestRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;

  /**
   * @generated from field: string service = 4;
   */
  service: string;

  /**
   * @generated from field: string method = 5;
   */
  method: string;
};

/**
 * Describes the message grpcview.v1.CreateRequestRequest.
 * Use `create(CreateRequestRequestSchema)` to create a new message.
 */
export declare const CreateRequestRequestSchema: GenMessage<CreateRequestRequest>;

/**
 * @generated from message grpcview.v1.CreateRequestResponse
 */
export declare type CreateRequestResponse = Message<"grpcview.v1.CreateRequestResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.CreateRequestResponse.
 * Use `create(CreateRequestResponseSchema)` to create a new message.
 */
export declare const CreateRequestResponseSchema: GenMessage<CreateRequestResponse>;

/**
 * @generated from message grpcview.v1.DeleteRequestRequest
 */
export declare type DeleteRequestRequest = Message<"grpcview.v1.DeleteRequestRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;
};

/**
 * Describes the message grpcview.v1.DeleteRequestRequest.
 * Use `create(DeleteRequestRequestSchema)` to create a new message.
 */
export declare const DeleteRequestRequestSchema: GenMessage<DeleteRequestRequest>;

/**
 * @generated from message grpcview.v1.DeleteRequestResponse
 */
export declare type DeleteRequestResponse = Message<"grpcview.v1.DeleteRequestResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.DeleteRequestResponse.
 * Use `create(DeleteRequestResponseSchema)` to create a new message.
 */
export declare const DeleteRequestResponseSchema: GenMessage<DeleteRequestResponse>;

/**
 * @generated from message grpcview.v1.UpdateRequestRequest
 */
export declare type UpdateRequestRequest = Message<"grpcview.v1.UpdateRequestRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;

  /**
   * @generated from field: optional string service = 4;
   */
  service?: string | undefined;

  /**
   * @generated from field: optional string method = 5;
   */
  method?: string | undefined;

  /**
   * @generated from field: optional string draft_body = 6;
   */
  draftBody?: string | undefined;

  /**
   * name renames the request (its display name). Unset leaves the name unchanged;
   * a rename that collides with a sibling fails with FailedPrecondition.
   *
   * @generated from field: optional string name = 8;
   */
  name?: string | undefined;

  /**
   * middleware patches the request's attached-middleware list (ordered MIDDLEWARE
   * script display names). proto3 repeated can't be `optional`, so update_middleware
   * is the set-flag that distinguishes "leave unchanged" from "set": when
   * update_middleware is true the list is replaced by `middleware` (an empty list
   * clears it); when false/unset the list is left as-is.
   *
   * @generated from field: optional bool update_middleware = 9;
   */
  updateMiddleware?: boolean | undefined;

  /**
   * @generated from field: repeated string middleware = 10;
   */
  middleware: string[];

  /**
   * draft_metadata_script patches the request's metadata source: a TypeScript
   * module (`export default (): Metadata => ({ ... })`) whose returned
   * {[key: string]: string[]} object is evaluated on invoke to build the
   * outgoing metadata. It mirrors draft_body's plumbing (a plain string patched
   * like draft_body). Unset leaves it unchanged, an empty-but-present value clears it.
   *
   * @generated from field: optional string draft_metadata_script = 12;
   */
  draftMetadataScript?: string | undefined;

  /**
   * target patches the request's per-request invoke destination (host:port +
   * TLS). Like update_middleware, it needs a set-flag to distinguish "leave
   * unchanged" from "clear": when update_target is true the target is replaced
   * by `target` (a nil `target` clears it, reverting to the reflection-source
   * default); when false/unset it is left unchanged.
   *
   * @generated from field: optional bool update_target = 13;
   */
  updateTarget?: boolean | undefined;

  /**
   * @generated from field: optional grpcview.v1.Server target = 14;
   */
  target?: Server | undefined;
};

/**
 * Describes the message grpcview.v1.UpdateRequestRequest.
 * Use `create(UpdateRequestRequestSchema)` to create a new message.
 */
export declare const UpdateRequestRequestSchema: GenMessage<UpdateRequestRequest>;

/**
 * @generated from message grpcview.v1.UpdateRequestResponse
 */
export declare type UpdateRequestResponse = Message<"grpcview.v1.UpdateRequestResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.UpdateRequestResponse.
 * Use `create(UpdateRequestResponseSchema)` to create a new message.
 */
export declare const UpdateRequestResponseSchema: GenMessage<UpdateRequestResponse>;

/**
 * UpdateFolderRequest patches a folder's name and metadata script. Mirrors
 * UpdateRequestRequest's plumbing but carries only the fields a folder has:
 * folders have no service/method/body/middleware/target of their own.
 *
 * @generated from message grpcview.v1.UpdateFolderRequest
 */
export declare type UpdateFolderRequest = Message<"grpcview.v1.UpdateFolderRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;

  /**
   * draft_metadata_script patches the folder's metadata source: a TypeScript
   * module (`export default (): Metadata => ({ ... })`) whose returned
   * {[key: string]: string[]} object contributes to the ancestor-folder
   * metadata chain gv.metadata.inherit() folds over. Mirrors
   * UpdateRequestRequest.draft_metadata_script: unset leaves it unchanged, an
   * empty-but-present value clears it.
   *
   * @generated from field: optional string draft_metadata_script = 4;
   */
  draftMetadataScript?: string | undefined;

  /**
   * name renames the folder (its display name). Unset leaves the name unchanged;
   * a rename that collides with a sibling fails with FailedPrecondition. Mirrors
   * UpdateRequestRequest.name, including the slug-identity model: the folder's
   * on-disk directory (and every descendant's) stays put.
   *
   * @generated from field: optional string name = 5;
   */
  name?: string | undefined;
};

/**
 * Describes the message grpcview.v1.UpdateFolderRequest.
 * Use `create(UpdateFolderRequestSchema)` to create a new message.
 */
export declare const UpdateFolderRequestSchema: GenMessage<UpdateFolderRequest>;

/**
 * @generated from message grpcview.v1.UpdateFolderResponse
 */
export declare type UpdateFolderResponse = Message<"grpcview.v1.UpdateFolderResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.UpdateFolderResponse.
 * Use `create(UpdateFolderResponseSchema)` to create a new message.
 */
export declare const UpdateFolderResponseSchema: GenMessage<UpdateFolderResponse>;

/**
 * MoveItemRequest reparents and/or reorders one tree item (of either kind). It is
 * the one mutation the Update* RPCs deliberately cannot express: their `path` +
 * `item_name` are pure ADDRESSING and `name` only rewrites the display name, per
 * the slug-identity model — nothing there moves an item between folders.
 *
 * Moving a folder into itself, or into any of its own descendants, is rejected
 * with FailedPrecondition (store.ErrMoveIntoDescendant): the drop would detach
 * the subtree from the tree entirely. The check is enforced in the store, not
 * just in the dragging UI, so a stale or hand-written request cannot corrupt the
 * collection. A destination that already holds an item with the same DISPLAY name
 * is likewise FailedPrecondition (store.ErrAlreadyExists) — a move never silently
 * renames what it moves.
 *
 * @generated from message grpcview.v1.MoveItemRequest
 */
export declare type MoveItemRequest = Message<"grpcview.v1.MoveItemRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * path + item_name address the item to move, exactly like every other item RPC.
   *
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;

  /**
   * new_path is the DESTINATION parent folder's display-name path (empty = the
   * collection root). Resolving to the item's CURRENT parent means a pure reorder
   * within that parent: the item's on-disk directory is left untouched and only
   * the recorded sibling order changes.
   *
   * @generated from field: repeated string new_path = 4;
   */
  newPath: string[];

  /**
   * before names a sibling in the destination parent to insert this item ahead of;
   * unset appends to the end. This is what makes a drop BETWEEN two rows
   * expressible and not just a drop INTO a folder. A `before` that no longer names
   * a child of the destination appends rather than failing — a stale drop target is
   * a UI race, not a corrupt request.
   *
   * @generated from field: optional string before = 5;
   */
  before?: string | undefined;
};

/**
 * Describes the message grpcview.v1.MoveItemRequest.
 * Use `create(MoveItemRequestSchema)` to create a new message.
 */
export declare const MoveItemRequestSchema: GenMessage<MoveItemRequest>;

/**
 * @generated from message grpcview.v1.MoveItemResponse
 */
export declare type MoveItemResponse = Message<"grpcview.v1.MoveItemResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.MoveItemResponse.
 * Use `create(MoveItemResponseSchema)` to create a new message.
 */
export declare const MoveItemResponseSchema: GenMessage<MoveItemResponse>;

/**
 * @generated from message grpcview.v1.GetRequest
 */
export declare type GetRequest = Message<"grpcview.v1.GetRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;
};

/**
 * Describes the message grpcview.v1.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export declare const GetRequestSchema: GenMessage<GetRequest>;

/**
 * @generated from message grpcview.v1.GetResponse
 */
export declare type GetResponse = Message<"grpcview.v1.GetResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export declare const GetResponseSchema: GenMessage<GetResponse>;

/**
 * InvokeRequest executes a single unary RPC against a target server. The
 * service/method/body/metadata carry the (possibly unsaved) editor state, so a
 * send never depends on a prior UpdateRequest landing first. workspace_name
 * identifies the collection (used to default the target from its reflection
 * source and, later, to key run history by path/item_name).
 *
 * @generated from message grpcview.v1.InvokeRequest
 */
export declare type InvokeRequest = Message<"grpcview.v1.InvokeRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;

  /**
   * @generated from field: string service = 4;
   */
  service: string;

  /**
   * @generated from field: string method = 5;
   */
  method: string;

  /**
   * @generated from field: string body = 6;
   */
  body: string;

  /**
   * @generated from field: google.protobuf.Struct metadata = 7;
   */
  metadata?: JsonObject | undefined;

  /**
   * target overrides where the call is sent; when unset it defaults to the
   * workspace's first reflection source.
   *
   * @generated from field: optional grpcview.v1.Server target = 8;
   */
  target?: Server | undefined;

  /**
   * metadata_script, when non-empty, is a TypeScript module
   * (`export default (): Metadata => ({ ... })`) whose returned
   * {[key: string]: string[]} object is evaluated on the backend (same engine as
   * the TS body, generators composable as ambient globals) to build the outgoing
   * metadata — superseding the `metadata` Struct above. Empty means "use
   * `metadata` as-is" (today's path). Carries the editor's current source, like
   * `body`, so a send never depends on a prior UpdateRequest landing first.
   *
   * @generated from field: string metadata_script = 10;
   */
  metadataScript: string;
};

/**
 * Describes the message grpcview.v1.InvokeRequest.
 * Use `create(InvokeRequestSchema)` to create a new message.
 */
export declare const InvokeRequestSchema: GenMessage<InvokeRequest>;

/**
 * @generated from message grpcview.v1.InvokeResponse
 */
export declare type InvokeResponse = Message<"grpcview.v1.InvokeResponse"> & {
  /**
   * @generated from field: grpcview.v1.Request.Response response = 1;
   */
  response?: Request_Response | undefined;
};

/**
 * Describes the message grpcview.v1.InvokeResponse.
 * Use `create(InvokeResponseSchema)` to create a new message.
 */
export declare const InvokeResponseSchema: GenMessage<InvokeResponse>;

/**
 * InvokeStreamRequest opens a streaming invoke. The browser transport
 * (@connectrpc/connect-web) cannot stream a request body, so the entire call is
 * modeled as a single server-streaming RPC: every client message is supplied
 * up-front in `messages`, and the backend maps them onto the target method's
 * real streaming kind (unary / server / client / bidi over full gRPC). The
 * service/method/messages/metadata carry the (possibly unsaved) editor state,
 * mirroring InvokeRequest.
 *
 * @generated from message grpcview.v1.InvokeStreamRequest
 */
export declare type InvokeStreamRequest = Message<"grpcview.v1.InvokeStreamRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;

  /**
   * @generated from field: string service = 4;
   */
  service: string;

  /**
   * @generated from field: string method = 5;
   */
  method: string;

  /**
   * messages are the client request bodies as JSON text, in send order. Unary
   * and server-streaming targets expect exactly one; client-streaming and bidi
   * targets receive all of them composed up-front — there is no live interleave,
   * a deliberate v1 limit of the browser transport. Empty defaults to one "{}".
   *
   * @generated from field: repeated string messages = 6;
   */
  messages: string[];

  /**
   * @generated from field: google.protobuf.Struct metadata = 7;
   */
  metadata?: JsonObject | undefined;

  /**
   * target overrides where the call is sent; unset defaults to the workspace's
   * first reflection source (same as Invoke).
   *
   * @generated from field: optional grpcview.v1.Server target = 8;
   */
  target?: Server | undefined;

  /**
   * metadata_script mirrors InvokeRequest.metadata_script: a TypeScript module
   * whose returned {[key: string]: string[]} object is evaluated on the backend
   * to build the outgoing metadata, superseding the `metadata` Struct when
   * non-empty. Empty means "use `metadata` as-is".
   *
   * @generated from field: string metadata_script = 10;
   */
  metadataScript: string;
};

/**
 * Describes the message grpcview.v1.InvokeStreamRequest.
 * Use `create(InvokeStreamRequestSchema)` to create a new message.
 */
export declare const InvokeStreamRequestSchema: GenMessage<InvokeStreamRequest>;

/**
 * InvokeStreamResponse is one frame of a streaming invoke. Zero or more `message`
 * frames carry response payloads as the target emits them; exactly one terminal
 * `result` frame closes the stream, carrying the final gRPC status, request +
 * response metadata, latency and timestamp — the same Request.Response shape
 * unary Invoke returns (its `response` bytes are left empty; payloads arrived as
 * message frames). A gRPC-status failure of the invoked call is reported in the
 * terminal frame's status, NOT as a Connect stream error; only grpcview-internal
 * failures (no target, unreachable schema, a body that doesn't parse) surface as
 * Connect errors.
 *
 * @generated from message grpcview.v1.InvokeStreamResponse
 */
export declare type InvokeStreamResponse = Message<"grpcview.v1.InvokeStreamResponse"> & {
  /**
   * @generated from oneof grpcview.v1.InvokeStreamResponse.event
   */
  event: {
    /**
     * @generated from field: bytes message = 1;
     */
    value: Uint8Array;
    case: "message";
  } | {
    /**
     * @generated from field: grpcview.v1.Request.Response result = 2;
     */
    value: Request_Response;
    case: "result";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message grpcview.v1.InvokeStreamResponse.
 * Use `create(InvokeStreamResponseSchema)` to create a new message.
 */
export declare const InvokeStreamResponseSchema: GenMessage<InvokeStreamResponse>;

/**
 * InvokeSavedRequest runs the request SAVED at path/item_name, resolving its body,
 * metadata script, attached middleware and target server-side — the addressed
 * counterpart to InvokeRequest, which carries the caller's own (possibly unsaved)
 * body. It backs both InvokeSaved and InvokeSavedStreaming.
 *
 * @generated from message grpcview.v1.InvokeSavedRequest
 */
export declare type InvokeSavedRequest = Message<"grpcview.v1.InvokeSavedRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * path is the saved request's PARENT-folder display-name path, outermost first;
   * empty for a request at the top level.
   *
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * item_name is the saved request's own display name.
   *
   * @generated from field: string item_name = 3;
   */
  itemName: string;

  /**
   * params is this run's gv.request.params: the object the request's body, metadata
   * script, ancestor folder metadata scripts and middleware all read it from.
   *
   * @generated from field: google.protobuf.Struct params = 4;
   */
  params?: JsonObject | undefined;

  /**
   * target overrides the saved request's target for this run; unset uses the saved
   * one (and, when that is unset too, the same default Invoke applies).
   *
   * @generated from field: optional grpcview.v1.Server target = 5;
   */
  target?: Server | undefined;

  /**
   * messages, when non-empty, override the saved body for this run only — the
   * request bodies as JSON (or TypeScript) text, in send order. The rule matches
   * InvokeStreamRequest.messages: unary and server-streaming targets expect exactly
   * one; client-streaming and bidi targets receive all of them composed up-front.
   *
   * @generated from field: repeated string messages = 6;
   */
  messages: string[];

  /**
   * record_history gates whether this run is appended to the saved request's run
   * history. It defaults to TRUE (an explicit false opts out) because an addressed
   * run is a real user-initiated one, unlike a script's fan-out.
   *
   * @generated from field: optional bool record_history = 7;
   */
  recordHistory?: boolean | undefined;

  /**
   * dry_run resolves and evaluates everything the call needs and then sends
   * nothing, reporting the outcome in InvokeSavedResponse.resolved. Nothing is
   * dialed, so a dry run works with the target down. Rejected by the streaming form,
   * which has no frame to carry the result — dry-run any request, of any streaming
   * kind, through the unary one.
   *
   * @generated from field: bool dry_run = 8;
   */
  dryRun: boolean;
};

/**
 * Describes the message grpcview.v1.InvokeSavedRequest.
 * Use `create(InvokeSavedRequestSchema)` to create a new message.
 */
export declare const InvokeSavedRequestSchema: GenMessage<InvokeSavedRequest>;

/**
 * InvokeSavedResponse carries a saved request's run: response for a real call,
 * resolved for a dry run. Exactly one of the two is ever set.
 *
 * @generated from message grpcview.v1.InvokeSavedResponse
 */
export declare type InvokeSavedResponse = Message<"grpcview.v1.InvokeSavedResponse"> & {
  /**
   * @generated from field: grpcview.v1.Request.Response response = 1;
   */
  response?: Request_Response | undefined;

  /**
   * @generated from field: optional grpcview.v1.ResolvedRequest resolved = 2;
   */
  resolved?: ResolvedRequest | undefined;
};

/**
 * Describes the message grpcview.v1.InvokeSavedResponse.
 * Use `create(InvokeSavedResponseSchema)` to create a new message.
 */
export declare const InvokeSavedResponseSchema: GenMessage<InvokeSavedResponse>;

/**
 * ResolvedRequest is what a dry run reports: everything the server would have sent,
 * post-evaluation and post-middleware, with nothing dialed.
 *
 * @generated from message grpcview.v1.ResolvedRequest
 */
export declare type ResolvedRequest = Message<"grpcview.v1.ResolvedRequest"> & {
  /**
   * @generated from field: string service = 1;
   */
  service: string;

  /**
   * @generated from field: string method = 2;
   */
  method: string;

  /**
   * target is the server the call would have been sent to, after the saved
   * request's own target and the per-run override are applied.
   *
   * @generated from field: grpcview.v1.Server target = 3;
   */
  target?: Server | undefined;

  /**
   * messages are the evaluated request bodies as JSON, post-middleware, in send
   * order — one entry for a unary or server-streaming target, all of them for a
   * client-streaming or bidi one.
   *
   * @generated from field: repeated string messages = 4;
   */
  messages: string[];

  /**
   * metadata is the evaluated outgoing metadata, post-middleware, as
   * {[key]: string[]}.
   *
   * @generated from field: google.protobuf.Struct metadata = 5;
   */
  metadata?: JsonObject | undefined;
};

/**
 * Describes the message grpcview.v1.ResolvedRequest.
 * Use `create(ResolvedRequestSchema)` to create a new message.
 */
export declare const ResolvedRequestSchema: GenMessage<ResolvedRequest>;

/**
 * DescribeMethodRequest asks for one method's schema, read from the workspace's
 * already-resolved definitions. Nothing is dialed, so it answers from a box that
 * cannot reach the target.
 *
 * @generated from message grpcview.v1.DescribeMethodRequest
 */
export declare type DescribeMethodRequest = Message<"grpcview.v1.DescribeMethodRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * service is the fully-qualified service name, e.g. "echo.v1.EchoService".
   *
   * @generated from field: string service = 2;
   */
  service: string;

  /**
   * method is the method's own name, e.g. "Unary" — not qualified by the service.
   *
   * @generated from field: string method = 3;
   */
  method: string;
};

/**
 * Describes the message grpcview.v1.DescribeMethodRequest.
 * Use `create(DescribeMethodRequestSchema)` to create a new message.
 */
export declare const DescribeMethodRequestSchema: GenMessage<DescribeMethodRequest>;

/**
 * DescribeMethodResponse carries the same schema twice: once rendered for a human
 * to read, once as descriptors for a program to parse.
 *
 * @generated from message grpcview.v1.DescribeMethodResponse
 */
export declare type DescribeMethodResponse = Message<"grpcview.v1.DescribeMethodResponse"> & {
  /**
   * proto_text is the rendered .proto view: the method, its input and output
   * messages, and every type they transitively reference. Doc comments appear only
   * when the winning source carried them.
   *
   * @generated from field: string proto_text = 1;
   */
  protoText: string;

  /**
   * descriptor_set is a serialized FileDescriptorSet covering the same closure,
   * self-contained (transitive imports included) so it links on its own.
   *
   * @generated from field: bytes descriptor_set = 2;
   */
  descriptorSet: Uint8Array;

  /**
   * source_id names the definition source the schema was read from, e.g.
   * "reflection:localhost:9000" or "upload:api.binpb".
   *
   * @generated from field: string source_id = 3;
   */
  sourceId: string;

  /**
   * client_streaming is true when the caller sends a stream of request messages.
   *
   * @generated from field: bool client_streaming = 4;
   */
  clientStreaming: boolean;

  /**
   * server_streaming is true when the target replies with a stream of messages.
   *
   * @generated from field: bool server_streaming = 5;
   */
  serverStreaming: boolean;
};

/**
 * Describes the message grpcview.v1.DescribeMethodResponse.
 * Use `create(DescribeMethodResponseSchema)` to create a new message.
 */
export declare const DescribeMethodResponseSchema: GenMessage<DescribeMethodResponse>;

/**
 * CreateScriptRequest creates a new, empty script of the given kind in the
 * collection. The name must be unique among scripts.
 *
 * @generated from message grpcview.v1.CreateScriptRequest
 */
export declare type CreateScriptRequest = Message<"grpcview.v1.CreateScriptRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: grpcview.v1.ScriptKind kind = 3;
   */
  kind: ScriptKind;
};

/**
 * Describes the message grpcview.v1.CreateScriptRequest.
 * Use `create(CreateScriptRequestSchema)` to create a new message.
 */
export declare const CreateScriptRequestSchema: GenMessage<CreateScriptRequest>;

/**
 * @generated from message grpcview.v1.CreateScriptResponse
 */
export declare type CreateScriptResponse = Message<"grpcview.v1.CreateScriptResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.CreateScriptResponse.
 * Use `create(CreateScriptResponseSchema)` to create a new message.
 */
export declare const CreateScriptResponseSchema: GenMessage<CreateScriptResponse>;

/**
 * UpdateScriptRequest applies a partial update to the script named `name`. An
 * unset field is left unchanged; source replaces the authored source, and new_name
 * renames the script (a collision with another script fails FailedPrecondition —
 * like UpdateRequest's rename).
 *
 * @generated from message grpcview.v1.UpdateScriptRequest
 */
export declare type UpdateScriptRequest = Message<"grpcview.v1.UpdateScriptRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional string source = 3;
   */
  source?: string | undefined;

  /**
   * @generated from field: optional string new_name = 4;
   */
  newName?: string | undefined;
};

/**
 * Describes the message grpcview.v1.UpdateScriptRequest.
 * Use `create(UpdateScriptRequestSchema)` to create a new message.
 */
export declare const UpdateScriptRequestSchema: GenMessage<UpdateScriptRequest>;

/**
 * @generated from message grpcview.v1.UpdateScriptResponse
 */
export declare type UpdateScriptResponse = Message<"grpcview.v1.UpdateScriptResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.UpdateScriptResponse.
 * Use `create(UpdateScriptResponseSchema)` to create a new message.
 */
export declare const UpdateScriptResponseSchema: GenMessage<UpdateScriptResponse>;

/**
 * @generated from message grpcview.v1.DeleteScriptRequest
 */
export declare type DeleteScriptRequest = Message<"grpcview.v1.DeleteScriptRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message grpcview.v1.DeleteScriptRequest.
 * Use `create(DeleteScriptRequestSchema)` to create a new message.
 */
export declare const DeleteScriptRequestSchema: GenMessage<DeleteScriptRequest>;

/**
 * @generated from message grpcview.v1.DeleteScriptResponse
 */
export declare type DeleteScriptResponse = Message<"grpcview.v1.DeleteScriptResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.DeleteScriptResponse.
 * Use `create(DeleteScriptResponseSchema)` to create a new message.
 */
export declare const DeleteScriptResponseSchema: GenMessage<DeleteScriptResponse>;

/**
 * RunScriptRequest evaluates a script through the scripting engine (fresh isolated
 * instance, no capabilities granted, no workspace state touched). kind selects the
 * execution profile and calling convention: a generator's `export default` is called,
 * a middleware's `handle`/default export is called with a ctx; unset (or scenario)
 * evaluates the buffer as an ad-hoc scratchpad (last-expression value) — the surface
 * that validates the engine end to end from the UI.
 *
 * @generated from message grpcview.v1.RunScriptRequest
 */
export declare type RunScriptRequest = Message<"grpcview.v1.RunScriptRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * @generated from field: string source = 2;
   */
  source: string;

  /**
   * @generated from field: optional grpcview.v1.ScriptKind kind = 3;
   */
  kind?: ScriptKind | undefined;
};

/**
 * Describes the message grpcview.v1.RunScriptRequest.
 * Use `create(RunScriptRequestSchema)` to create a new message.
 */
export declare const RunScriptRequestSchema: GenMessage<RunScriptRequest>;

/**
 * ScriptLog is one buffered console.* call captured during a run.
 *
 * @generated from message grpcview.v1.ScriptLog
 */
export declare type ScriptLog = Message<"grpcview.v1.ScriptLog"> & {
  /**
   * debug | log | warn | error
   *
   * @generated from field: string level = 1;
   */
  level: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message grpcview.v1.ScriptLog.
 * Use `create(ScriptLogSchema)` to create a new message.
 */
export declare const ScriptLogSchema: GenMessage<ScriptLog>;

/**
 * ScriptError is a JavaScript exception (or an execution failure like a timeout)
 * that propagated out of a run. line is the source line parsed from the guest
 * backtrace (0 when unknown).
 *
 * @generated from message grpcview.v1.ScriptError
 */
export declare type ScriptError = Message<"grpcview.v1.ScriptError"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: string stack = 2;
   */
  stack: string;

  /**
   * @generated from field: int32 line = 3;
   */
  line: number;
};

/**
 * Describes the message grpcview.v1.ScriptError.
 * Use `create(ScriptErrorSchema)` to create a new message.
 */
export declare const ScriptErrorSchema: GenMessage<ScriptError>;

/**
 * RunScriptResponse carries a run's outcome. A script that throws or times out is
 * reported here (error set), NOT as a Connect-level failure — only grpcview's own
 * inability to run the engine surfaces as a Connect error.
 *
 * @generated from message grpcview.v1.RunScriptResponse
 */
export declare type RunScriptResponse = Message<"grpcview.v1.RunScriptResponse"> & {
  /**
   * value is the script's return value as JSON text; unset when the script
   * returned undefined (a JSON `null` return is the literal string "null").
   *
   * @generated from field: optional string value = 1;
   */
  value?: string | undefined;

  /**
   * @generated from field: repeated grpcview.v1.ScriptLog logs = 2;
   */
  logs: ScriptLog[];

  /**
   * @generated from field: optional grpcview.v1.ScriptError error = 3;
   */
  error?: ScriptError | undefined;
};

/**
 * Describes the message grpcview.v1.RunScriptResponse.
 * Use `create(RunScriptResponseSchema)` to create a new message.
 */
export declare const RunScriptResponseSchema: GenMessage<RunScriptResponse>;

/**
 * WorkspaceService is a gRPC service that provides access to the workspace
 *
 * @generated from service grpcview.v1.WorkspaceService
 */
export declare const WorkspaceService: GenService<{
  /**
   * AddDescriptorSource adds a descriptor source to the workspace — where its
   * definitions come from. A source whose id already exists is refreshed in place
   * (see AddDescriptorSourceRequest.file_name); a new one is appended at LOWEST
   * priority, so adding never changes which source an existing service resolves
   * from. Only the added/refreshed source is resolved (one network round-trip for
   * reflection); the merged view is rebuilt from every source's cached resolve.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.AddDescriptorSource
   */
  addDescriptorSource: {
    methodKind: "unary";
    input: typeof AddDescriptorSourceRequestSchema;
    output: typeof AddDescriptorSourceResponseSchema;
  },
  /**
   * RemoveDescriptorSource drops the source with the given id and rebuilds the
   * merged view from the cached resolves of those that remain — no network, so
   * an unreachable sibling source can never block a removal.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.RemoveDescriptorSource
   */
  removeDescriptorSource: {
    methodKind: "unary";
    input: typeof RemoveDescriptorSourceRequestSchema;
    output: typeof RemoveDescriptorSourceResponseSchema;
  },
  /**
   * RefreshDescriptorSource re-resolves exactly one source (re-dialing a
   * reflection target, re-parsing an upload) and rebuilds the merged view.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.RefreshDescriptorSource
   */
  refreshDescriptorSource: {
    methodKind: "unary";
    input: typeof RefreshDescriptorSourceRequestSchema;
    output: typeof RefreshDescriptorSourceResponseSchema;
  },
  /**
   * ReorderDescriptorSources sets the source priority order and rebuilds the
   * merged view from the cached resolves — no network. This is how you switch
   * which source's definitions win when several describe the same protos.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.ReorderDescriptorSources
   */
  reorderDescriptorSources: {
    methodKind: "unary";
    input: typeof ReorderDescriptorSourcesRequestSchema;
    output: typeof ReorderDescriptorSourcesResponseSchema;
  },
  /**
   * Get returns the workspace snapshot
   *
   * @generated from rpc grpcview.v1.WorkspaceService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetRequestSchema;
    output: typeof GetResponseSchema;
  },
  /**
   * CreateFolder creates a new folder in the workspace
   *
   * @generated from rpc grpcview.v1.WorkspaceService.CreateFolder
   */
  createFolder: {
    methodKind: "unary";
    input: typeof CreateFolderRequestSchema;
    output: typeof CreateFolderResponseSchema;
  },
  /**
   * CreateRequest creates a new request in the workspace
   *
   * @generated from rpc grpcview.v1.WorkspaceService.CreateRequest
   */
  createRequest: {
    methodKind: "unary";
    input: typeof CreateRequestRequestSchema;
    output: typeof CreateRequestResponseSchema;
  },
  /**
   * DeleteRequest deletes a request from the workspace
   *
   * @generated from rpc grpcview.v1.WorkspaceService.DeleteRequest
   */
  deleteRequest: {
    methodKind: "unary";
    input: typeof DeleteRequestRequestSchema;
    output: typeof DeleteRequestResponseSchema;
  },
  /**
   * UpdateRequest updates a request in the workspace
   *
   * @generated from rpc grpcview.v1.WorkspaceService.UpdateRequest
   */
  updateRequest: {
    methodKind: "unary";
    input: typeof UpdateRequestRequestSchema;
    output: typeof UpdateRequestResponseSchema;
  },
  /**
   * UpdateFolder updates a folder's metadata script in the workspace
   *
   * @generated from rpc grpcview.v1.WorkspaceService.UpdateFolder
   */
  updateFolder: {
    methodKind: "unary";
    input: typeof UpdateFolderRequestSchema;
    output: typeof UpdateFolderResponseSchema;
  },
  /**
   * MoveItem reparents and/or reorders an item; a drop into the moved folder's own
   * subtree is rejected server-side.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.MoveItem
   */
  moveItem: {
    methodKind: "unary";
    input: typeof MoveItemRequestSchema;
    output: typeof MoveItemResponseSchema;
  },
  /**
   * Invoke executes a unary RPC against a target server and returns the result
   * (status, response body, request/response metadata, latency).
   *
   * @generated from rpc grpcview.v1.WorkspaceService.Invoke
   */
  invoke: {
    methodKind: "unary";
    input: typeof InvokeRequestSchema;
    output: typeof InvokeResponseSchema;
  },
  /**
   * InvokeStreaming executes an RPC of any kind (unary, server-, client-, or
   * bidi-streaming) against the target and streams the responses back. Modeled
   * as server-streaming — not the bidi the design sketch suggested — because the
   * browser transport (connect-web) cannot stream a request body; see
   * InvokeStreamRequest for how client messages are supplied.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.InvokeStreaming
   */
  invokeStreaming: {
    methodKind: "server_streaming";
    input: typeof InvokeStreamRequestSchema;
    output: typeof InvokeStreamResponseSchema;
  },
  /**
   * Runs the request saved at a collection path and returns the result of the call.
   *
   * Requires workspace_name, item_name (the request's display name) and path (its
   * parent folders, outermost first; empty at the top level). The saved request's own
   * body, metadata, middleware and target are used, so the caller supplies no body of
   * its own. params is a free-form object its body and metadata read values from. For one
   * run only: target overrides where the call goes, messages override the request
   * bodies as JSON text, record_history defaults to true, and dry_run evaluates
   * everything but sends nothing.
   *
   * Returns the response message, the call's gRPC status, request and response
   * metadata and the latency — or, for a dry run, only the resolved request. A status
   * the target returned is reported in the response, never as an error. A streaming
   * method needs the streaming form of this call.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.InvokeSaved
   */
  invokeSaved: {
    methodKind: "unary";
    input: typeof InvokeSavedRequestSchema;
    output: typeof InvokeSavedResponseSchema;
  },
  /**
   * Runs the request saved at a collection path and streams every response message back.
   *
   * Takes the same arguments as the unary form except dry_run, which is rejected here.
   * Handles a method of any kind: a client-streaming or bidi method is sent every entry
   * of messages up-front, in order, since there is no live interleave.
   *
   * Returns zero or more message frames as the target emits them, then one final frame
   * carrying the gRPC status, request and response metadata and the latency. A status
   * the target returned is reported in that final frame, never as an error.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.InvokeSavedStreaming
   */
  invokeSavedStreaming: {
    methodKind: "server_streaming";
    input: typeof InvokeSavedRequestSchema;
    output: typeof InvokeStreamResponseSchema;
  },
  /**
   * Describes the input and output shape of one method, without calling anything.
   *
   * Requires workspace_name, service (fully qualified, e.g. "echo.v1.EchoService") and
   * method (its own name, e.g. "Unary"). The shape comes from definitions the workspace
   * has already resolved, so this answers even when the target is unreachable.
   *
   * Returns the method's input and output messages plus every type they reference —
   * twice: as rendered .proto text to read, and as serialized FileDescriptorSet bytes to
   * parse — with the id of the source they were read from and whether either side of the
   * call streams.
   *
   * Doc comments come through only if that source carried them: a server answering by
   * reflection strips them, an uploaded descriptor set built with them keeps them.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.DescribeMethod
   */
  describeMethod: {
    methodKind: "unary";
    input: typeof DescribeMethodRequestSchema;
    output: typeof DescribeMethodResponseSchema;
  },
  /**
   * RunScript evaluates a script through the scripting engine and returns its
   * value, console output, and any error — the scratchpad and the per-kind
   * test-run surface that validates the engine end to end.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.RunScript
   */
  runScript: {
    methodKind: "unary";
    input: typeof RunScriptRequestSchema;
    output: typeof RunScriptResponseSchema;
  },
  /**
   * CreateScript creates a new, empty script of a given kind in the workspace.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.CreateScript
   */
  createScript: {
    methodKind: "unary";
    input: typeof CreateScriptRequestSchema;
    output: typeof CreateScriptResponseSchema;
  },
  /**
   * UpdateScript edits a script's source and/or renames it.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.UpdateScript
   */
  updateScript: {
    methodKind: "unary";
    input: typeof UpdateScriptRequestSchema;
    output: typeof UpdateScriptResponseSchema;
  },
  /**
   * DeleteScript removes a script from the workspace.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.DeleteScript
   */
  deleteScript: {
    methodKind: "unary";
    input: typeof DeleteScriptRequestSchema;
    output: typeof DeleteScriptResponseSchema;
  },
}>;

