// @generated by protoc-gen-es v2.12.1 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file proto/grpcview/v1/service.proto (package grpcview.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { Request_Response, Server, Workspace } from "./workspace_pb";

/**
 * Describes the file proto/grpcview/v1/service.proto.
 */
export declare const file_proto_grpcview_v1_service: GenFile;

/**
 * @generated from message grpcview.v1.AddDescriptorSourceRequest
 */
export declare type AddDescriptorSourceRequest = Message<"grpcview.v1.AddDescriptorSourceRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * @generated from oneof grpcview.v1.AddDescriptorSourceRequest.source
   */
  source: {
    /**
     * @generated from field: bytes descriptor_set = 2;
     */
    value: Uint8Array;
    case: "descriptorSet";
  } | {
    /**
     * @generated from field: grpcview.v1.Server reflection = 3;
     */
    value: Server;
    case: "reflection";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message grpcview.v1.AddDescriptorSourceRequest.
 * Use `create(AddDescriptorSourceRequestSchema)` to create a new message.
 */
export declare const AddDescriptorSourceRequestSchema: GenMessage<AddDescriptorSourceRequest>;

/**
 * @generated from message grpcview.v1.AddDescriptorSourceResponse
 */
export declare type AddDescriptorSourceResponse = Message<"grpcview.v1.AddDescriptorSourceResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.AddDescriptorSourceResponse.
 * Use `create(AddDescriptorSourceResponseSchema)` to create a new message.
 */
export declare const AddDescriptorSourceResponseSchema: GenMessage<AddDescriptorSourceResponse>;

/**
 * @generated from message grpcview.v1.CreateFolderRequest
 */
export declare type CreateFolderRequest = Message<"grpcview.v1.CreateFolderRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;
};

/**
 * Describes the message grpcview.v1.CreateFolderRequest.
 * Use `create(CreateFolderRequestSchema)` to create a new message.
 */
export declare const CreateFolderRequestSchema: GenMessage<CreateFolderRequest>;

/**
 * @generated from message grpcview.v1.CreateFolderResponse
 */
export declare type CreateFolderResponse = Message<"grpcview.v1.CreateFolderResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.CreateFolderResponse.
 * Use `create(CreateFolderResponseSchema)` to create a new message.
 */
export declare const CreateFolderResponseSchema: GenMessage<CreateFolderResponse>;

/**
 * @generated from message grpcview.v1.CreateRequestRequest
 */
export declare type CreateRequestRequest = Message<"grpcview.v1.CreateRequestRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;

  /**
   * @generated from field: string service = 4;
   */
  service: string;

  /**
   * @generated from field: string method = 5;
   */
  method: string;
};

/**
 * Describes the message grpcview.v1.CreateRequestRequest.
 * Use `create(CreateRequestRequestSchema)` to create a new message.
 */
export declare const CreateRequestRequestSchema: GenMessage<CreateRequestRequest>;

/**
 * @generated from message grpcview.v1.CreateRequestResponse
 */
export declare type CreateRequestResponse = Message<"grpcview.v1.CreateRequestResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.CreateRequestResponse.
 * Use `create(CreateRequestResponseSchema)` to create a new message.
 */
export declare const CreateRequestResponseSchema: GenMessage<CreateRequestResponse>;

/**
 * @generated from message grpcview.v1.DeleteRequestRequest
 */
export declare type DeleteRequestRequest = Message<"grpcview.v1.DeleteRequestRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;
};

/**
 * Describes the message grpcview.v1.DeleteRequestRequest.
 * Use `create(DeleteRequestRequestSchema)` to create a new message.
 */
export declare const DeleteRequestRequestSchema: GenMessage<DeleteRequestRequest>;

/**
 * @generated from message grpcview.v1.DeleteRequestResponse
 */
export declare type DeleteRequestResponse = Message<"grpcview.v1.DeleteRequestResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.DeleteRequestResponse.
 * Use `create(DeleteRequestResponseSchema)` to create a new message.
 */
export declare const DeleteRequestResponseSchema: GenMessage<DeleteRequestResponse>;

/**
 * @generated from message grpcview.v1.UpdateRequestRequest
 */
export declare type UpdateRequestRequest = Message<"grpcview.v1.UpdateRequestRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;

  /**
   * @generated from field: optional string service = 4;
   */
  service?: string | undefined;

  /**
   * @generated from field: optional string method = 5;
   */
  method?: string | undefined;

  /**
   * @generated from field: optional string draft_body = 6;
   */
  draftBody?: string | undefined;

  /**
   * @generated from field: optional google.protobuf.Struct draft_metadata = 7;
   */
  draftMetadata?: JsonObject | undefined;

  /**
   * name renames the request (its display name). Unset leaves the name unchanged;
   * a rename that collides with a sibling fails with FailedPrecondition.
   *
   * @generated from field: optional string name = 8;
   */
  name?: string | undefined;
};

/**
 * Describes the message grpcview.v1.UpdateRequestRequest.
 * Use `create(UpdateRequestRequestSchema)` to create a new message.
 */
export declare const UpdateRequestRequestSchema: GenMessage<UpdateRequestRequest>;

/**
 * @generated from message grpcview.v1.UpdateRequestResponse
 */
export declare type UpdateRequestResponse = Message<"grpcview.v1.UpdateRequestResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.UpdateRequestResponse.
 * Use `create(UpdateRequestResponseSchema)` to create a new message.
 */
export declare const UpdateRequestResponseSchema: GenMessage<UpdateRequestResponse>;

/**
 * @generated from message grpcview.v1.GetRequest
 */
export declare type GetRequest = Message<"grpcview.v1.GetRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;
};

/**
 * Describes the message grpcview.v1.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export declare const GetRequestSchema: GenMessage<GetRequest>;

/**
 * @generated from message grpcview.v1.GetResponse
 */
export declare type GetResponse = Message<"grpcview.v1.GetResponse"> & {
  /**
   * @generated from field: grpcview.v1.Workspace workspace = 1;
   */
  workspace?: Workspace | undefined;
};

/**
 * Describes the message grpcview.v1.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export declare const GetResponseSchema: GenMessage<GetResponse>;

/**
 * InvokeRequest executes a single unary RPC against a target server. The
 * service/method/body/metadata carry the (possibly unsaved) editor state, so a
 * send never depends on a prior UpdateRequest landing first. workspace_name
 * identifies the collection (used to default the target from its reflection
 * source and, later, to key run history by path/item_name).
 *
 * @generated from message grpcview.v1.InvokeRequest
 */
export declare type InvokeRequest = Message<"grpcview.v1.InvokeRequest"> & {
  /**
   * @generated from field: string workspace_name = 1;
   */
  workspaceName: string;

  /**
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;

  /**
   * @generated from field: string service = 4;
   */
  service: string;

  /**
   * @generated from field: string method = 5;
   */
  method: string;

  /**
   * @generated from field: string body = 6;
   */
  body: string;

  /**
   * @generated from field: google.protobuf.Struct metadata = 7;
   */
  metadata?: JsonObject | undefined;

  /**
   * target overrides where the call is sent; when unset it defaults to the
   * workspace's first reflection source.
   *
   * @generated from field: optional grpcview.v1.Server target = 8;
   */
  target?: Server | undefined;
};

/**
 * Describes the message grpcview.v1.InvokeRequest.
 * Use `create(InvokeRequestSchema)` to create a new message.
 */
export declare const InvokeRequestSchema: GenMessage<InvokeRequest>;

/**
 * @generated from message grpcview.v1.InvokeResponse
 */
export declare type InvokeResponse = Message<"grpcview.v1.InvokeResponse"> & {
  /**
   * @generated from field: grpcview.v1.Request.Response response = 1;
   */
  response?: Request_Response | undefined;
};

/**
 * Describes the message grpcview.v1.InvokeResponse.
 * Use `create(InvokeResponseSchema)` to create a new message.
 */
export declare const InvokeResponseSchema: GenMessage<InvokeResponse>;

/**
 * RunScriptRequest evaluates an ad-hoc script through the scripting engine's
 * scenario profile (fresh isolated instance, no capabilities granted, no
 * workspace state touched). It is the scratchpad that validates the engine end
 * to end from the UI.
 *
 * @generated from message grpcview.v1.RunScriptRequest
 */
export declare type RunScriptRequest = Message<"grpcview.v1.RunScriptRequest"> & {
  /**
   * @generated from field: string source = 1;
   */
  source: string;
};

/**
 * Describes the message grpcview.v1.RunScriptRequest.
 * Use `create(RunScriptRequestSchema)` to create a new message.
 */
export declare const RunScriptRequestSchema: GenMessage<RunScriptRequest>;

/**
 * ScriptLog is one buffered console.* call captured during a run.
 *
 * @generated from message grpcview.v1.ScriptLog
 */
export declare type ScriptLog = Message<"grpcview.v1.ScriptLog"> & {
  /**
   * debug | log | warn | error
   *
   * @generated from field: string level = 1;
   */
  level: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message grpcview.v1.ScriptLog.
 * Use `create(ScriptLogSchema)` to create a new message.
 */
export declare const ScriptLogSchema: GenMessage<ScriptLog>;

/**
 * ScriptError is a JavaScript exception (or an execution failure like a timeout)
 * that propagated out of a run. line is the source line parsed from the guest
 * backtrace (0 when unknown).
 *
 * @generated from message grpcview.v1.ScriptError
 */
export declare type ScriptError = Message<"grpcview.v1.ScriptError"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: string stack = 2;
   */
  stack: string;

  /**
   * @generated from field: int32 line = 3;
   */
  line: number;
};

/**
 * Describes the message grpcview.v1.ScriptError.
 * Use `create(ScriptErrorSchema)` to create a new message.
 */
export declare const ScriptErrorSchema: GenMessage<ScriptError>;

/**
 * RunScriptResponse carries a run's outcome. A script that throws or times out is
 * reported here (error set), NOT as a Connect-level failure — only grpcview's own
 * inability to run the engine surfaces as a Connect error.
 *
 * @generated from message grpcview.v1.RunScriptResponse
 */
export declare type RunScriptResponse = Message<"grpcview.v1.RunScriptResponse"> & {
  /**
   * value is the script's return value as JSON text; unset when the script
   * returned undefined (a JSON `null` return is the literal string "null").
   *
   * @generated from field: optional string value = 1;
   */
  value?: string | undefined;

  /**
   * @generated from field: repeated grpcview.v1.ScriptLog logs = 2;
   */
  logs: ScriptLog[];

  /**
   * @generated from field: optional grpcview.v1.ScriptError error = 3;
   */
  error?: ScriptError | undefined;
};

/**
 * Describes the message grpcview.v1.RunScriptResponse.
 * Use `create(RunScriptResponseSchema)` to create a new message.
 */
export declare const RunScriptResponseSchema: GenMessage<RunScriptResponse>;

/**
 * WorkspaceService is a gRPC service that provides access to the workspace
 *
 * @generated from service grpcview.v1.WorkspaceService
 */
export declare const WorkspaceService: GenService<{
  /**
   * AddDescriptorSource adds a descriptor source to the workspace, it is used to obtain workspace defitions
   *
   * @generated from rpc grpcview.v1.WorkspaceService.AddDescriptorSource
   */
  addDescriptorSource: {
    methodKind: "unary";
    input: typeof AddDescriptorSourceRequestSchema;
    output: typeof AddDescriptorSourceResponseSchema;
  },
  /**
   * Get returns the workspace snapshot
   *
   * @generated from rpc grpcview.v1.WorkspaceService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetRequestSchema;
    output: typeof GetResponseSchema;
  },
  /**
   * CreateFolder creates a new folder in the workspace
   *
   * @generated from rpc grpcview.v1.WorkspaceService.CreateFolder
   */
  createFolder: {
    methodKind: "unary";
    input: typeof CreateFolderRequestSchema;
    output: typeof CreateFolderResponseSchema;
  },
  /**
   * CreateRequest creates a new request in the workspace
   *
   * @generated from rpc grpcview.v1.WorkspaceService.CreateRequest
   */
  createRequest: {
    methodKind: "unary";
    input: typeof CreateRequestRequestSchema;
    output: typeof CreateRequestResponseSchema;
  },
  /**
   * DeleteRequest deletes a request from the workspace
   *
   * @generated from rpc grpcview.v1.WorkspaceService.DeleteRequest
   */
  deleteRequest: {
    methodKind: "unary";
    input: typeof DeleteRequestRequestSchema;
    output: typeof DeleteRequestResponseSchema;
  },
  /**
   * UpdateRequest updates a request in the workspace
   *
   * @generated from rpc grpcview.v1.WorkspaceService.UpdateRequest
   */
  updateRequest: {
    methodKind: "unary";
    input: typeof UpdateRequestRequestSchema;
    output: typeof UpdateRequestResponseSchema;
  },
  /**
   * Invoke executes a unary RPC against a target server and returns the result
   * (status, response body, request/response metadata, latency).
   *
   * @generated from rpc grpcview.v1.WorkspaceService.Invoke
   */
  invoke: {
    methodKind: "unary";
    input: typeof InvokeRequestSchema;
    output: typeof InvokeResponseSchema;
  },
  /**
   * RunScript evaluates an ad-hoc script through the scripting engine and returns
   * its value, console output, and any error — the scratchpad that validates the
   * engine end to end.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.RunScript
   */
  runScript: {
    methodKind: "unary";
    input: typeof RunScriptRequestSchema;
    output: typeof RunScriptResponseSchema;
  },
}>;

