// @generated by protoc-gen-es v2.12.1 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file proto/grpcview/v1/service.proto (package grpcview.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { Bazel, Collection, Request_Response, Server } from "./workspace_pb";
import type { Duration } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file proto/grpcview/v1/service.proto.
 */
export declare const file_proto_grpcview_v1_service: GenFile;

/**
 * @generated from message grpcview.v1.AddDescriptorSourceRequest
 */
export declare type AddDescriptorSourceRequest = Message<"grpcview.v1.AddDescriptorSourceRequest"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * @generated from oneof grpcview.v1.AddDescriptorSourceRequest.source
   */
  source: {
    /**
     * @generated from field: bytes descriptor_set = 2;
     */
    value: Uint8Array;
    case: "descriptorSet";
  } | {
    /**
     * @generated from field: grpcview.v1.Server reflection = 3;
     */
    value: Server;
    case: "reflection";
  } | {
    /**
     * @generated from field: grpcview.v1.Bazel bazel = 6;
     */
    value: Bazel;
    case: "bazel";
  } | { case: undefined; value?: undefined };

  /**
   * Identity of a descriptor_set upload; re-uploading the same name refreshes it.
   *
   * @generated from field: string file_name = 4;
   */
  fileName: string;

  /**
   * Refresh recipe for a descriptor_set upload. Absolute or workspace-relative;
   * stored root-relative. Empty from a browser, which only loses refresh.
   *
   * @generated from field: string path = 7;
   */
  path: string;

  /**
   * See DescriptorSource.commit_descriptors.
   *
   * @generated from field: bool commit_descriptors = 5;
   */
  commitDescriptors: boolean;
};

/**
 * Describes the message grpcview.v1.AddDescriptorSourceRequest.
 * Use `create(AddDescriptorSourceRequestSchema)` to create a new message.
 */
export declare const AddDescriptorSourceRequestSchema: GenMessage<AddDescriptorSourceRequest>;

/**
 * @generated from message grpcview.v1.AddDescriptorSourceResponse
 */
export declare type AddDescriptorSourceResponse = Message<"grpcview.v1.AddDescriptorSourceResponse"> & {
  /**
   * @generated from field: grpcview.v1.Collection collection = 1;
   */
  collection?: Collection | undefined;
};

/**
 * Describes the message grpcview.v1.AddDescriptorSourceResponse.
 * Use `create(AddDescriptorSourceResponseSchema)` to create a new message.
 */
export declare const AddDescriptorSourceResponseSchema: GenMessage<AddDescriptorSourceResponse>;

/**
 * @generated from message grpcview.v1.RemoveDescriptorSourceRequest
 */
export declare type RemoveDescriptorSourceRequest = Message<"grpcview.v1.RemoveDescriptorSourceRequest"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;
};

/**
 * Describes the message grpcview.v1.RemoveDescriptorSourceRequest.
 * Use `create(RemoveDescriptorSourceRequestSchema)` to create a new message.
 */
export declare const RemoveDescriptorSourceRequestSchema: GenMessage<RemoveDescriptorSourceRequest>;

/**
 * @generated from message grpcview.v1.RemoveDescriptorSourceResponse
 */
export declare type RemoveDescriptorSourceResponse = Message<"grpcview.v1.RemoveDescriptorSourceResponse"> & {
  /**
   * @generated from field: grpcview.v1.Collection collection = 1;
   */
  collection?: Collection | undefined;
};

/**
 * Describes the message grpcview.v1.RemoveDescriptorSourceResponse.
 * Use `create(RemoveDescriptorSourceResponseSchema)` to create a new message.
 */
export declare const RemoveDescriptorSourceResponseSchema: GenMessage<RemoveDescriptorSourceResponse>;

/**
 * @generated from message grpcview.v1.RefreshDescriptorSourceRequest
 */
export declare type RefreshDescriptorSourceRequest = Message<"grpcview.v1.RefreshDescriptorSourceRequest"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;
};

/**
 * Describes the message grpcview.v1.RefreshDescriptorSourceRequest.
 * Use `create(RefreshDescriptorSourceRequestSchema)` to create a new message.
 */
export declare const RefreshDescriptorSourceRequestSchema: GenMessage<RefreshDescriptorSourceRequest>;

/**
 * @generated from message grpcview.v1.RefreshDescriptorSourceResponse
 */
export declare type RefreshDescriptorSourceResponse = Message<"grpcview.v1.RefreshDescriptorSourceResponse"> & {
  /**
   * @generated from field: grpcview.v1.Collection collection = 1;
   */
  collection?: Collection | undefined;
};

/**
 * Describes the message grpcview.v1.RefreshDescriptorSourceResponse.
 * Use `create(RefreshDescriptorSourceResponseSchema)` to create a new message.
 */
export declare const RefreshDescriptorSourceResponseSchema: GenMessage<RefreshDescriptorSourceResponse>;

/**
 * @generated from message grpcview.v1.ReorderDescriptorSourcesRequest
 */
export declare type ReorderDescriptorSourcesRequest = Message<"grpcview.v1.ReorderDescriptorSourcesRequest"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * Every DescriptorSource.id in priority order — earlier wins; must be a permutation.
   *
   * @generated from field: repeated string ids = 2;
   */
  ids: string[];
};

/**
 * Describes the message grpcview.v1.ReorderDescriptorSourcesRequest.
 * Use `create(ReorderDescriptorSourcesRequestSchema)` to create a new message.
 */
export declare const ReorderDescriptorSourcesRequestSchema: GenMessage<ReorderDescriptorSourcesRequest>;

/**
 * @generated from message grpcview.v1.ReorderDescriptorSourcesResponse
 */
export declare type ReorderDescriptorSourcesResponse = Message<"grpcview.v1.ReorderDescriptorSourcesResponse"> & {
  /**
   * @generated from field: grpcview.v1.Collection collection = 1;
   */
  collection?: Collection | undefined;
};

/**
 * Describes the message grpcview.v1.ReorderDescriptorSourcesResponse.
 * Use `create(ReorderDescriptorSourcesResponseSchema)` to create a new message.
 */
export declare const ReorderDescriptorSourcesResponseSchema: GenMessage<ReorderDescriptorSourcesResponse>;

/**
 * @generated from message grpcview.v1.SetDescriptorSourceCommitRequest
 */
export declare type SetDescriptorSourceCommitRequest = Message<"grpcview.v1.SetDescriptorSourceCommitRequest"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * @generated from field: bool commit = 3;
   */
  commit: boolean;
};

/**
 * Describes the message grpcview.v1.SetDescriptorSourceCommitRequest.
 * Use `create(SetDescriptorSourceCommitRequestSchema)` to create a new message.
 */
export declare const SetDescriptorSourceCommitRequestSchema: GenMessage<SetDescriptorSourceCommitRequest>;

/**
 * @generated from message grpcview.v1.SetDescriptorSourceCommitResponse
 */
export declare type SetDescriptorSourceCommitResponse = Message<"grpcview.v1.SetDescriptorSourceCommitResponse"> & {
  /**
   * @generated from field: grpcview.v1.Collection collection = 1;
   */
  collection?: Collection | undefined;
};

/**
 * Describes the message grpcview.v1.SetDescriptorSourceCommitResponse.
 * Use `create(SetDescriptorSourceCommitResponseSchema)` to create a new message.
 */
export declare const SetDescriptorSourceCommitResponseSchema: GenMessage<SetDescriptorSourceCommitResponse>;

/**
 * @generated from message grpcview.v1.CreateFolderRequest
 */
export declare type CreateFolderRequest = Message<"grpcview.v1.CreateFolderRequest"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;
};

/**
 * Describes the message grpcview.v1.CreateFolderRequest.
 * Use `create(CreateFolderRequestSchema)` to create a new message.
 */
export declare const CreateFolderRequestSchema: GenMessage<CreateFolderRequest>;

/**
 * @generated from message grpcview.v1.CreateFolderResponse
 */
export declare type CreateFolderResponse = Message<"grpcview.v1.CreateFolderResponse"> & {
  /**
   * @generated from field: grpcview.v1.Collection collection = 1;
   */
  collection?: Collection | undefined;
};

/**
 * Describes the message grpcview.v1.CreateFolderResponse.
 * Use `create(CreateFolderResponseSchema)` to create a new message.
 */
export declare const CreateFolderResponseSchema: GenMessage<CreateFolderResponse>;

/**
 * @generated from message grpcview.v1.CreateRequestRequest
 */
export declare type CreateRequestRequest = Message<"grpcview.v1.CreateRequestRequest"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;

  /**
   * @generated from field: string service = 4;
   */
  service: string;

  /**
   * @generated from field: string method = 5;
   */
  method: string;
};

/**
 * Describes the message grpcview.v1.CreateRequestRequest.
 * Use `create(CreateRequestRequestSchema)` to create a new message.
 */
export declare const CreateRequestRequestSchema: GenMessage<CreateRequestRequest>;

/**
 * @generated from message grpcview.v1.CreateRequestResponse
 */
export declare type CreateRequestResponse = Message<"grpcview.v1.CreateRequestResponse"> & {
  /**
   * @generated from field: grpcview.v1.Collection collection = 1;
   */
  collection?: Collection | undefined;

  /**
   * Non-fatal: the request was created. Says what about it will not work yet, e.g.
   * a streaming method, which invoke rejects with Unimplemented.
   *
   * @generated from field: repeated string warnings = 2;
   */
  warnings: string[];
};

/**
 * Describes the message grpcview.v1.CreateRequestResponse.
 * Use `create(CreateRequestResponseSchema)` to create a new message.
 */
export declare const CreateRequestResponseSchema: GenMessage<CreateRequestResponse>;

/**
 * @generated from message grpcview.v1.DeleteRequestRequest
 */
export declare type DeleteRequestRequest = Message<"grpcview.v1.DeleteRequestRequest"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;
};

/**
 * Describes the message grpcview.v1.DeleteRequestRequest.
 * Use `create(DeleteRequestRequestSchema)` to create a new message.
 */
export declare const DeleteRequestRequestSchema: GenMessage<DeleteRequestRequest>;

/**
 * @generated from message grpcview.v1.DeleteRequestResponse
 */
export declare type DeleteRequestResponse = Message<"grpcview.v1.DeleteRequestResponse"> & {
  /**
   * @generated from field: grpcview.v1.Collection collection = 1;
   */
  collection?: Collection | undefined;
};

/**
 * Describes the message grpcview.v1.DeleteRequestResponse.
 * Use `create(DeleteRequestResponseSchema)` to create a new message.
 */
export declare const DeleteRequestResponseSchema: GenMessage<DeleteRequestResponse>;

/**
 * @generated from message grpcview.v1.UpdateRequestRequest
 */
export declare type UpdateRequestRequest = Message<"grpcview.v1.UpdateRequestRequest"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;

  /**
   * @generated from field: optional string service = 4;
   */
  service?: string | undefined;

  /**
   * @generated from field: optional string method = 5;
   */
  method?: string | undefined;

  /**
   * @generated from field: optional string draft_body = 6;
   */
  draftBody?: string | undefined;

  /**
   * @generated from field: optional string name = 8;
   */
  name?: string | undefined;

  /**
   * Set-flag: true replaces `middleware` (empty clears it), false/unset leaves it.
   *
   * @generated from field: optional bool update_middleware = 9;
   */
  updateMiddleware?: boolean | undefined;

  /**
   * @generated from field: repeated string middleware = 10;
   */
  middleware: string[];

  /**
   * TypeScript module; empty-but-present clears it.
   *
   * @generated from field: optional string draft_metadata_script = 12;
   */
  draftMetadataScript?: string | undefined;

  /**
   * Set-flag: true replaces `target` (nil clears it), false/unset leaves it.
   *
   * @generated from field: optional bool update_target = 13;
   */
  updateTarget?: boolean | undefined;

  /**
   * @generated from field: optional grpcview.v1.Server target = 14;
   */
  target?: Server | undefined;
};

/**
 * Describes the message grpcview.v1.UpdateRequestRequest.
 * Use `create(UpdateRequestRequestSchema)` to create a new message.
 */
export declare const UpdateRequestRequestSchema: GenMessage<UpdateRequestRequest>;

/**
 * @generated from message grpcview.v1.UpdateRequestResponse
 */
export declare type UpdateRequestResponse = Message<"grpcview.v1.UpdateRequestResponse"> & {
  /**
   * @generated from field: grpcview.v1.Collection collection = 1;
   */
  collection?: Collection | undefined;
};

/**
 * Describes the message grpcview.v1.UpdateRequestResponse.
 * Use `create(UpdateRequestResponseSchema)` to create a new message.
 */
export declare const UpdateRequestResponseSchema: GenMessage<UpdateRequestResponse>;

/**
 * @generated from message grpcview.v1.UpdateFolderRequest
 */
export declare type UpdateFolderRequest = Message<"grpcview.v1.UpdateFolderRequest"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;

  /**
   * TypeScript module feeding the gv.metadata.inherit() chain; empty clears it.
   *
   * @generated from field: optional string draft_metadata_script = 4;
   */
  draftMetadataScript?: string | undefined;

  /**
   * @generated from field: optional string name = 5;
   */
  name?: string | undefined;
};

/**
 * Describes the message grpcview.v1.UpdateFolderRequest.
 * Use `create(UpdateFolderRequestSchema)` to create a new message.
 */
export declare const UpdateFolderRequestSchema: GenMessage<UpdateFolderRequest>;

/**
 * @generated from message grpcview.v1.UpdateFolderResponse
 */
export declare type UpdateFolderResponse = Message<"grpcview.v1.UpdateFolderResponse"> & {
  /**
   * @generated from field: grpcview.v1.Collection collection = 1;
   */
  collection?: Collection | undefined;
};

/**
 * Describes the message grpcview.v1.UpdateFolderResponse.
 * Use `create(UpdateFolderResponseSchema)` to create a new message.
 */
export declare const UpdateFolderResponseSchema: GenMessage<UpdateFolderResponse>;

/**
 * A move into the moved folder's own subtree, or onto an existing name, fails.
 *
 * @generated from message grpcview.v1.MoveItemRequest
 */
export declare type MoveItemRequest = Message<"grpcview.v1.MoveItemRequest"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;

  /**
   * Destination parent; empty is the root, the current parent means a pure reorder.
   *
   * @generated from field: repeated string new_path = 4;
   */
  newPath: string[];

  /**
   * Sibling in the destination to insert ahead of; unset (or stale) appends.
   *
   * @generated from field: optional string before = 5;
   */
  before?: string | undefined;
};

/**
 * Describes the message grpcview.v1.MoveItemRequest.
 * Use `create(MoveItemRequestSchema)` to create a new message.
 */
export declare const MoveItemRequestSchema: GenMessage<MoveItemRequest>;

/**
 * @generated from message grpcview.v1.MoveItemResponse
 */
export declare type MoveItemResponse = Message<"grpcview.v1.MoveItemResponse"> & {
  /**
   * @generated from field: grpcview.v1.Collection collection = 1;
   */
  collection?: Collection | undefined;
};

/**
 * Describes the message grpcview.v1.MoveItemResponse.
 * Use `create(MoveItemResponseSchema)` to create a new message.
 */
export declare const MoveItemResponseSchema: GenMessage<MoveItemResponse>;

/**
 * @generated from message grpcview.v1.GetRequest
 */
export declare type GetRequest = Message<"grpcview.v1.GetRequest"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;
};

/**
 * Describes the message grpcview.v1.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export declare const GetRequestSchema: GenMessage<GetRequest>;

/**
 * @generated from message grpcview.v1.GetResponse
 */
export declare type GetResponse = Message<"grpcview.v1.GetResponse"> & {
  /**
   * @generated from field: grpcview.v1.Collection collection = 1;
   */
  collection?: Collection | undefined;
};

/**
 * Describes the message grpcview.v1.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export declare const GetResponseSchema: GenMessage<GetResponse>;

/**
 * @generated from message grpcview.v1.ListCollectionsRequest
 */
export declare type ListCollectionsRequest = Message<"grpcview.v1.ListCollectionsRequest"> & {
};

/**
 * Describes the message grpcview.v1.ListCollectionsRequest.
 * Use `create(ListCollectionsRequestSchema)` to create a new message.
 */
export declare const ListCollectionsRequestSchema: GenMessage<ListCollectionsRequest>;

/**
 * @generated from message grpcview.v1.CollectionSummary
 */
export declare type CollectionSummary = Message<"grpcview.v1.CollectionSummary"> & {
  /**
   * Workspace-relative path that addresses this collection; "." is the root.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Display name, never the id — five collections may all be called "requests".
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: int32 source_count = 3;
   */
  sourceCount: number;

  /**
   * Why this collection could not be summarized; a broken one is a visible row.
   *
   * @generated from field: string error = 4;
   */
  error: string;
};

/**
 * Describes the message grpcview.v1.CollectionSummary.
 * Use `create(CollectionSummarySchema)` to create a new message.
 */
export declare const CollectionSummarySchema: GenMessage<CollectionSummary>;

/**
 * @generated from message grpcview.v1.ListCollectionsResponse
 */
export declare type ListCollectionsResponse = Message<"grpcview.v1.ListCollectionsResponse"> & {
  /**
   * Absolute workspace root, so a caller with a cwd of its own (the CLI) can
   * resolve that cwd against the workspace it is talking to.
   *
   * @generated from field: string root = 1;
   */
  root: string;

  /**
   * @generated from field: repeated grpcview.v1.CollectionSummary collections = 2;
   */
  collections: CollectionSummary[];

  /**
   * Whether this root is trusted. Trust gates ONLY the source kinds that EXECUTE
   * (a bazel label); reflection and uploads resolve regardless.
   *
   * @generated from field: bool trusted = 3;
   */
  trusted: boolean;
};

/**
 * Describes the message grpcview.v1.ListCollectionsResponse.
 * Use `create(ListCollectionsResponseSchema)` to create a new message.
 */
export declare const ListCollectionsResponseSchema: GenMessage<ListCollectionsResponse>;

/**
 * @generated from message grpcview.v1.SetWorkspaceTrustRequest
 */
export declare type SetWorkspaceTrustRequest = Message<"grpcview.v1.SetWorkspaceTrustRequest"> & {
  /**
   * @generated from field: bool trusted = 1;
   */
  trusted: boolean;
};

/**
 * Describes the message grpcview.v1.SetWorkspaceTrustRequest.
 * Use `create(SetWorkspaceTrustRequestSchema)` to create a new message.
 */
export declare const SetWorkspaceTrustRequestSchema: GenMessage<SetWorkspaceTrustRequest>;

/**
 * @generated from message grpcview.v1.SetWorkspaceTrustResponse
 */
export declare type SetWorkspaceTrustResponse = Message<"grpcview.v1.SetWorkspaceTrustResponse"> & {
  /**
   * The resulting state, so a client never has to guess whether the flip took.
   *
   * @generated from field: bool trusted = 1;
   */
  trusted: boolean;
};

/**
 * Describes the message grpcview.v1.SetWorkspaceTrustResponse.
 * Use `create(SetWorkspaceTrustResponseSchema)` to create a new message.
 */
export declare const SetWorkspaceTrustResponseSchema: GenMessage<SetWorkspaceTrustResponse>;

/**
 * Takes no arguments on purpose: the query is built here, never from client
 * input, since the label validator cannot check a query expression.
 *
 * @generated from message grpcview.v1.ListBazelTargetsRequest
 */
export declare type ListBazelTargetsRequest = Message<"grpcview.v1.ListBazelTargetsRequest"> & {
};

/**
 * Describes the message grpcview.v1.ListBazelTargetsRequest.
 * Use `create(ListBazelTargetsRequestSchema)` to create a new message.
 */
export declare const ListBazelTargetsRequestSchema: GenMessage<ListBazelTargetsRequest>;

/**
 * @generated from message grpcview.v1.ListBazelTargetsResponse
 */
export declare type ListBazelTargetsResponse = Message<"grpcview.v1.ListBazelTargetsResponse"> & {
  /**
   * Canonical labels, sorted, deduped. A SUGGESTION list: the field stays free
   * text, because an unknown rule can still produce a descriptor set.
   *
   * @generated from field: repeated string labels = 1;
   */
  labels: string[];

  /**
   * Why the listing is short, when bazel errored but the query survived (one
   * unloadable package under --keep_going). Never a reason to refuse the labels.
   *
   * @generated from field: string warning = 2;
   */
  warning: string;
};

/**
 * Describes the message grpcview.v1.ListBazelTargetsResponse.
 * Use `create(ListBazelTargetsResponseSchema)` to create a new message.
 */
export declare const ListBazelTargetsResponseSchema: GenMessage<ListBazelTargetsResponse>;

/**
 * An importable TypeScript module in the workspace, as the editors need it:
 * contents, not declarations — the inferred types are the point.
 *
 * @generated from message grpcview.v1.WorkspaceModule
 */
export declare type WorkspaceModule = Message<"grpcview.v1.WorkspaceModule"> & {
  /**
   * Workspace-relative, slash-separated: "example/scripts/uuid.ts".
   *
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: string content = 2;
   */
  content: string;
};

/**
 * Describes the message grpcview.v1.WorkspaceModule.
 * Use `create(WorkspaceModuleSchema)` to create a new message.
 */
export declare const WorkspaceModuleSchema: GenMessage<WorkspaceModule>;

/**
 * @generated from message grpcview.v1.ListWorkspaceModulesRequest
 */
export declare type ListWorkspaceModulesRequest = Message<"grpcview.v1.ListWorkspaceModulesRequest"> & {
};

/**
 * Describes the message grpcview.v1.ListWorkspaceModulesRequest.
 * Use `create(ListWorkspaceModulesRequestSchema)` to create a new message.
 */
export declare const ListWorkspaceModulesRequestSchema: GenMessage<ListWorkspaceModulesRequest>;

/**
 * @generated from message grpcview.v1.ListWorkspaceModulesResponse
 */
export declare type ListWorkspaceModulesResponse = Message<"grpcview.v1.ListWorkspaceModulesResponse"> & {
  /**
   * @generated from field: repeated grpcview.v1.WorkspaceModule modules = 1;
   */
  modules: WorkspaceModule[];
};

/**
 * Describes the message grpcview.v1.ListWorkspaceModulesResponse.
 * Use `create(ListWorkspaceModulesResponseSchema)` to create a new message.
 */
export declare const ListWorkspaceModulesResponseSchema: GenMessage<ListWorkspaceModulesResponse>;

/**
 * A collection is only ever created by an explicit act — this RPC, or
 * `grpcview init` — or a stale query would scatter grpcview.json around a repo.
 *
 * @generated from message grpcview.v1.CreateCollectionRequest
 */
export declare type CreateCollectionRequest = Message<"grpcview.v1.CreateCollectionRequest"> & {
  /**
   * Workspace-relative directory to create it in; "." is the workspace root.
   *
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * Display name; empty defaults to the directory's own base name.
   *
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message grpcview.v1.CreateCollectionRequest.
 * Use `create(CreateCollectionRequestSchema)` to create a new message.
 */
export declare const CreateCollectionRequestSchema: GenMessage<CreateCollectionRequest>;

/**
 * @generated from message grpcview.v1.CreateCollectionResponse
 */
export declare type CreateCollectionResponse = Message<"grpcview.v1.CreateCollectionResponse"> & {
  /**
   * @generated from field: grpcview.v1.Collection collection = 1;
   */
  collection?: Collection | undefined;
};

/**
 * Describes the message grpcview.v1.CreateCollectionResponse.
 * Use `create(CreateCollectionResponseSchema)` to create a new message.
 */
export declare const CreateCollectionResponseSchema: GenMessage<CreateCollectionResponse>;

/**
 * The two names a collection has, editable independently: `name` is manifest
 * text, `new_collection` is the directory the collection lives in. An unset
 * field is left alone.
 *
 * @generated from message grpcview.v1.UpdateCollectionRequest
 */
export declare type UpdateCollectionRequest = Message<"grpcview.v1.UpdateCollectionRequest"> & {
  /**
   * The collection to edit, addressed as it is now.
   *
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * New display name. Empty resets it to the directory's own base name.
   *
   * @generated from field: optional string name = 2;
   */
  name?: string | undefined;

  /**
   * New workspace-relative directory; MOVES the directory on disk. Neither the
   * source nor the destination may be ".", and the destination must not exist.
   *
   * @generated from field: optional string new_collection = 3;
   */
  newCollection?: string | undefined;
};

/**
 * Describes the message grpcview.v1.UpdateCollectionRequest.
 * Use `create(UpdateCollectionRequestSchema)` to create a new message.
 */
export declare const UpdateCollectionRequestSchema: GenMessage<UpdateCollectionRequest>;

/**
 * @generated from message grpcview.v1.UpdateCollectionResponse
 */
export declare type UpdateCollectionResponse = Message<"grpcview.v1.UpdateCollectionResponse"> & {
  /**
   * @generated from field: grpcview.v1.Collection collection = 1;
   */
  collection?: Collection | undefined;
};

/**
 * Describes the message grpcview.v1.UpdateCollectionResponse.
 * Use `create(UpdateCollectionResponseSchema)` to create a new message.
 */
export declare const UpdateCollectionResponseSchema: GenMessage<UpdateCollectionResponse>;

/**
 * Everything an ad-hoc invoke needs except the client payload — the one thing
 * the unary and streaming forms disagree about.
 *
 * @generated from message grpcview.v1.InvokeSpec
 */
export declare type InvokeSpec = Message<"grpcview.v1.InvokeSpec"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * Parent-folder display-name path, outermost first; empty at the top level.
   *
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;

  /**
   * @generated from field: string service = 4;
   */
  service: string;

  /**
   * @generated from field: string method = 5;
   */
  method: string;

  /**
   * @generated from field: google.protobuf.Struct metadata = 6;
   */
  metadata?: JsonObject | undefined;

  /**
   * Unset defaults to the collection's first reflection source.
   *
   * @generated from field: optional grpcview.v1.Server target = 7;
   */
  target?: Server | undefined;

  /**
   * TypeScript module; supersedes `metadata` when non-empty.
   *
   * @generated from field: string metadata_script = 8;
   */
  metadataScript: string;
};

/**
 * Describes the message grpcview.v1.InvokeSpec.
 * Use `create(InvokeSpecSchema)` to create a new message.
 */
export declare const InvokeSpecSchema: GenMessage<InvokeSpec>;

/**
 * Executes a unary RPC carrying the caller's own, possibly unsaved, body.
 *
 * @generated from message grpcview.v1.InvokeRequest
 */
export declare type InvokeRequest = Message<"grpcview.v1.InvokeRequest"> & {
  /**
   * @generated from field: grpcview.v1.InvokeSpec spec = 1;
   */
  spec?: InvokeSpec | undefined;

  /**
   * The request message as a JSON object, or a TypeScript module default-exporting
   * one — valid JSON is already valid TS, so both forms parse. Quote 64-bit ints:
   * an unquoted one loses precision. Empty sends an empty message.
   *
   * @generated from field: string body = 2;
   */
  body: string;
};

/**
 * Describes the message grpcview.v1.InvokeRequest.
 * Use `create(InvokeRequestSchema)` to create a new message.
 */
export declare const InvokeRequestSchema: GenMessage<InvokeRequest>;

/**
 * @generated from message grpcview.v1.InvokeResponse
 */
export declare type InvokeResponse = Message<"grpcview.v1.InvokeResponse"> & {
  /**
   * @generated from field: grpcview.v1.Request.Response response = 1;
   */
  response?: Request_Response | undefined;
};

/**
 * Describes the message grpcview.v1.InvokeResponse.
 * Use `create(InvokeResponseSchema)` to create a new message.
 */
export declare const InvokeResponseSchema: GenMessage<InvokeResponse>;

/**
 * All client messages are supplied up-front: connect-web cannot stream a body.
 *
 * @generated from message grpcview.v1.InvokeStreamRequest
 */
export declare type InvokeStreamRequest = Message<"grpcview.v1.InvokeStreamRequest"> & {
  /**
   * @generated from field: grpcview.v1.InvokeSpec spec = 1;
   */
  spec?: InvokeSpec | undefined;

  /**
   * Client bodies as JSON text, in send order; empty defaults to one "{}".
   *
   * @generated from field: repeated string messages = 2;
   */
  messages: string[];
};

/**
 * Describes the message grpcview.v1.InvokeStreamRequest.
 * Use `create(InvokeStreamRequestSchema)` to create a new message.
 */
export declare const InvokeStreamRequestSchema: GenMessage<InvokeStreamRequest>;

/**
 * Zero or more `message` frames, then exactly one terminal `result`. The invoked
 * call's gRPC status is reported in `result`, not as a Connect stream error.
 *
 * @generated from message grpcview.v1.InvokeStreamingResponse
 */
export declare type InvokeStreamingResponse = Message<"grpcview.v1.InvokeStreamingResponse"> & {
  /**
   * @generated from oneof grpcview.v1.InvokeStreamingResponse.event
   */
  event: {
    /**
     * @generated from field: bytes message = 1;
     */
    value: Uint8Array;
    case: "message";
  } | {
    /**
     * @generated from field: grpcview.v1.Request.Response result = 2;
     */
    value: Request_Response;
    case: "result";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message grpcview.v1.InvokeStreamingResponse.
 * Use `create(InvokeStreamingResponseSchema)` to create a new message.
 */
export declare const InvokeStreamingResponseSchema: GenMessage<InvokeStreamingResponse>;

/**
 * Addresses the request SAVED at path/item_name and says how to run it once.
 *
 * @generated from message grpcview.v1.SavedInvokeSpec
 */
export declare type SavedInvokeSpec = Message<"grpcview.v1.SavedInvokeSpec"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * Parent-folder display-name path, outermost first; empty at the top level.
   *
   * @generated from field: repeated string path = 2;
   */
  path: string[];

  /**
   * @generated from field: string item_name = 3;
   */
  itemName: string;

  /**
   * This run's gv.request.params.
   *
   * @generated from field: google.protobuf.Struct params = 4;
   */
  params?: JsonObject | undefined;

  /**
   * Unset uses the saved request's own target.
   *
   * @generated from field: optional grpcview.v1.Server target = 5;
   */
  target?: Server | undefined;

  /**
   * Overrides the saved body for this run only.
   *
   * @generated from field: repeated string messages = 6;
   */
  messages: string[];

  /**
   * Append this run to the request's history. Defaults to TRUE.
   *
   * @generated from field: optional bool record_history = 7;
   */
  recordHistory?: boolean | undefined;
};

/**
 * Describes the message grpcview.v1.SavedInvokeSpec.
 * Use `create(SavedInvokeSpecSchema)` to create a new message.
 */
export declare const SavedInvokeSpecSchema: GenMessage<SavedInvokeSpec>;

/**
 * Runs the request SAVED at path/item_name, resolved server-side.
 *
 * @generated from message grpcview.v1.InvokeSavedRequest
 */
export declare type InvokeSavedRequest = Message<"grpcview.v1.InvokeSavedRequest"> & {
  /**
   * @generated from field: grpcview.v1.SavedInvokeSpec spec = 1;
   */
  spec?: SavedInvokeSpec | undefined;

  /**
   * Resolve and evaluate everything, send nothing.
   *
   * @generated from field: bool dry_run = 2;
   */
  dryRun: boolean;
};

/**
 * Describes the message grpcview.v1.InvokeSavedRequest.
 * Use `create(InvokeSavedRequestSchema)` to create a new message.
 */
export declare const InvokeSavedRequestSchema: GenMessage<InvokeSavedRequest>;

/**
 * No dry_run: a dry run reports one resolved request, which is the unary shape.
 *
 * @generated from message grpcview.v1.InvokeSavedStreamRequest
 */
export declare type InvokeSavedStreamRequest = Message<"grpcview.v1.InvokeSavedStreamRequest"> & {
  /**
   * @generated from field: grpcview.v1.SavedInvokeSpec spec = 1;
   */
  spec?: SavedInvokeSpec | undefined;
};

/**
 * Describes the message grpcview.v1.InvokeSavedStreamRequest.
 * Use `create(InvokeSavedStreamRequestSchema)` to create a new message.
 */
export declare const InvokeSavedStreamRequestSchema: GenMessage<InvokeSavedStreamRequest>;

/**
 * Exactly one of `response` (a real call) and `resolved` (a dry run) is set.
 *
 * @generated from message grpcview.v1.InvokeSavedResponse
 */
export declare type InvokeSavedResponse = Message<"grpcview.v1.InvokeSavedResponse"> & {
  /**
   * @generated from field: grpcview.v1.Request.Response response = 1;
   */
  response?: Request_Response | undefined;

  /**
   * @generated from field: optional grpcview.v1.ResolvedRequest resolved = 2;
   */
  resolved?: ResolvedRequest | undefined;
};

/**
 * Describes the message grpcview.v1.InvokeSavedResponse.
 * Use `create(InvokeSavedResponseSchema)` to create a new message.
 */
export declare const InvokeSavedResponseSchema: GenMessage<InvokeSavedResponse>;

/**
 * What a dry run reports: what would have been sent, post-middleware, nothing dialed.
 *
 * @generated from message grpcview.v1.ResolvedRequest
 */
export declare type ResolvedRequest = Message<"grpcview.v1.ResolvedRequest"> & {
  /**
   * @generated from field: string service = 1;
   */
  service: string;

  /**
   * @generated from field: string method = 2;
   */
  method: string;

  /**
   * @generated from field: grpcview.v1.Server target = 3;
   */
  target?: Server | undefined;

  /**
   * @generated from field: repeated string messages = 4;
   */
  messages: string[];

  /**
   * @generated from field: google.protobuf.Struct metadata = 5;
   */
  metadata?: JsonObject | undefined;
};

/**
 * Describes the message grpcview.v1.ResolvedRequest.
 * Use `create(ResolvedRequestSchema)` to create a new message.
 */
export declare const ResolvedRequestSchema: GenMessage<ResolvedRequest>;

/**
 * @generated from message grpcview.v1.DescribeMethodRequest
 */
export declare type DescribeMethodRequest = Message<"grpcview.v1.DescribeMethodRequest"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * Fully qualified, e.g. "echo.v1.EchoService"; method is its own name, "Unary".
   *
   * @generated from field: string service = 2;
   */
  service: string;

  /**
   * @generated from field: string method = 3;
   */
  method: string;
};

/**
 * Describes the message grpcview.v1.DescribeMethodRequest.
 * Use `create(DescribeMethodRequestSchema)` to create a new message.
 */
export declare const DescribeMethodRequestSchema: GenMessage<DescribeMethodRequest>;

/**
 * @generated from message grpcview.v1.DescribeMethodResponse
 */
export declare type DescribeMethodResponse = Message<"grpcview.v1.DescribeMethodResponse"> & {
  /**
   * The method, its input and output messages, and every type they reference.
   *
   * @generated from field: string proto_text = 1;
   */
  protoText: string;

  /**
   * The same closure, transitive imports included so it links on its own.
   *
   * @generated from field: bytes descriptor_set = 2;
   */
  descriptorSet: Uint8Array;

  /**
   * The source it was read from, e.g. "reflection:localhost:9000".
   *
   * @generated from field: string source_id = 3;
   */
  sourceId: string;

  /**
   * @generated from field: bool client_streaming = 4;
   */
  clientStreaming: boolean;

  /**
   * @generated from field: bool server_streaming = 5;
   */
  serverStreaming: boolean;

  /**
   * Why invoking this method would fail today; empty when it is invocable. Set for
   * every streaming method, which invoke rejects with Unimplemented.
   *
   * @generated from field: string not_invocable_reason = 6;
   */
  notInvocableReason: string;
};

/**
 * Describes the message grpcview.v1.DescribeMethodResponse.
 * Use `create(DescribeMethodResponseSchema)` to create a new message.
 */
export declare const DescribeMethodResponseSchema: GenMessage<DescribeMethodResponse>;

/**
 * @generated from message grpcview.v1.CreateScriptRequest
 */
export declare type CreateScriptRequest = Message<"grpcview.v1.CreateScriptRequest"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * @generated from field: string path = 2;
   */
  path: string;
};

/**
 * Describes the message grpcview.v1.CreateScriptRequest.
 * Use `create(CreateScriptRequestSchema)` to create a new message.
 */
export declare const CreateScriptRequestSchema: GenMessage<CreateScriptRequest>;

/**
 * @generated from message grpcview.v1.CreateScriptResponse
 */
export declare type CreateScriptResponse = Message<"grpcview.v1.CreateScriptResponse"> & {
  /**
   * @generated from field: grpcview.v1.Collection collection = 1;
   */
  collection?: Collection | undefined;
};

/**
 * Describes the message grpcview.v1.CreateScriptResponse.
 * Use `create(CreateScriptResponseSchema)` to create a new message.
 */
export declare const CreateScriptResponseSchema: GenMessage<CreateScriptResponse>;

/**
 * Partial update: `path` addresses the script, `new_path` renames it (a rename is a file move).
 *
 * @generated from message grpcview.v1.UpdateScriptRequest
 */
export declare type UpdateScriptRequest = Message<"grpcview.v1.UpdateScriptRequest"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * @generated from field: string path = 2;
   */
  path: string;

  /**
   * @generated from field: optional string source = 3;
   */
  source?: string | undefined;

  /**
   * @generated from field: optional string new_path = 4;
   */
  newPath?: string | undefined;
};

/**
 * Describes the message grpcview.v1.UpdateScriptRequest.
 * Use `create(UpdateScriptRequestSchema)` to create a new message.
 */
export declare const UpdateScriptRequestSchema: GenMessage<UpdateScriptRequest>;

/**
 * @generated from message grpcview.v1.UpdateScriptResponse
 */
export declare type UpdateScriptResponse = Message<"grpcview.v1.UpdateScriptResponse"> & {
  /**
   * @generated from field: grpcview.v1.Collection collection = 1;
   */
  collection?: Collection | undefined;
};

/**
 * Describes the message grpcview.v1.UpdateScriptResponse.
 * Use `create(UpdateScriptResponseSchema)` to create a new message.
 */
export declare const UpdateScriptResponseSchema: GenMessage<UpdateScriptResponse>;

/**
 * @generated from message grpcview.v1.DeleteScriptRequest
 */
export declare type DeleteScriptRequest = Message<"grpcview.v1.DeleteScriptRequest"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * @generated from field: string path = 2;
   */
  path: string;
};

/**
 * Describes the message grpcview.v1.DeleteScriptRequest.
 * Use `create(DeleteScriptRequestSchema)` to create a new message.
 */
export declare const DeleteScriptRequestSchema: GenMessage<DeleteScriptRequest>;

/**
 * @generated from message grpcview.v1.DeleteScriptResponse
 */
export declare type DeleteScriptResponse = Message<"grpcview.v1.DeleteScriptResponse"> & {
  /**
   * @generated from field: grpcview.v1.Collection collection = 1;
   */
  collection?: Collection | undefined;
};

/**
 * Describes the message grpcview.v1.DeleteScriptResponse.
 * Use `create(DeleteScriptResponseSchema)` to create a new message.
 */
export declare const DeleteScriptResponseSchema: GenMessage<DeleteScriptResponse>;

/**
 * @generated from message grpcview.v1.RunScriptRequest
 */
export declare type RunScriptRequest = Message<"grpcview.v1.RunScriptRequest"> & {
  /**
   * @generated from field: string collection = 1;
   */
  collection: string;

  /**
   * A source with `export default` is compiled as an entry and its default export is
   * called; anything else is evaluated as a scratchpad and its last expression is the
   * value. Ignored when `script` names a saved script, which follows the same rule.
   *
   * @generated from field: string source = 2;
   */
  source: string;

  /**
   * Path of a saved script to run instead of `source`. Exactly one of the two.
   *
   * @generated from field: optional string script = 4;
   */
  script?: string | undefined;
};

/**
 * Describes the message grpcview.v1.RunScriptRequest.
 * Use `create(RunScriptRequestSchema)` to create a new message.
 */
export declare const RunScriptRequestSchema: GenMessage<RunScriptRequest>;

/**
 * @generated from message grpcview.v1.ScriptLog
 */
export declare type ScriptLog = Message<"grpcview.v1.ScriptLog"> & {
  /**
   * debug | log | warn | error
   *
   * @generated from field: string level = 1;
   */
  level: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message grpcview.v1.ScriptLog.
 * Use `create(ScriptLogSchema)` to create a new message.
 */
export declare const ScriptLogSchema: GenMessage<ScriptLog>;

/**
 * @generated from message grpcview.v1.ScriptError
 */
export declare type ScriptError = Message<"grpcview.v1.ScriptError"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: string stack = 2;
   */
  stack: string;

  /**
   * Source line parsed from the guest backtrace; 0 when unknown.
   *
   * @generated from field: int32 line = 3;
   */
  line: number;
};

/**
 * Describes the message grpcview.v1.ScriptError.
 * Use `create(ScriptErrorSchema)` to create a new message.
 */
export declare const ScriptErrorSchema: GenMessage<ScriptError>;

/**
 * A script that throws or times out is reported in `error`, not as a Connect failure.
 *
 * @generated from message grpcview.v1.RunScriptResponse
 */
export declare type RunScriptResponse = Message<"grpcview.v1.RunScriptResponse"> & {
  /**
   * JSON text; unset when the script returned undefined.
   *
   * @generated from field: optional string value = 1;
   */
  value?: string | undefined;

  /**
   * @generated from field: repeated grpcview.v1.ScriptLog logs = 2;
   */
  logs: ScriptLog[];

  /**
   * @generated from field: optional grpcview.v1.ScriptError error = 3;
   */
  error?: ScriptError | undefined;
};

/**
 * Describes the message grpcview.v1.RunScriptResponse.
 * Use `create(RunScriptResponseSchema)` to create a new message.
 */
export declare const RunScriptResponseSchema: GenMessage<RunScriptResponse>;

/**
 * Identity of the binary a server is running, so a client can tell a daemon serving
 * last hour's code from one serving this build. A version STRING cannot: an unstamped
 * build links "dev" for every rebuild.
 *
 * @generated from message grpcview.v1.ServerExecutable
 */
export declare type ServerExecutable = Message<"grpcview.v1.ServerExecutable"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: int64 modified_unix = 2;
   */
  modifiedUnix: bigint;

  /**
   * @generated from field: int64 size = 3;
   */
  size: bigint;
};

/**
 * Describes the message grpcview.v1.ServerExecutable.
 * Use `create(ServerExecutableSchema)` to create a new message.
 */
export declare const ServerExecutableSchema: GenMessage<ServerExecutable>;

/**
 * @generated from message grpcview.v1.ServerInfoRequest
 */
export declare type ServerInfoRequest = Message<"grpcview.v1.ServerInfoRequest"> & {
};

/**
 * Describes the message grpcview.v1.ServerInfoRequest.
 * Use `create(ServerInfoRequestSchema)` to create a new message.
 */
export declare const ServerInfoRequestSchema: GenMessage<ServerInfoRequest>;

/**
 * @generated from message grpcview.v1.ServerInfoResponse
 */
export declare type ServerInfoResponse = Message<"grpcview.v1.ServerInfoResponse"> & {
  /**
   * Absolute, and the field the whole registration design turns on: a client verifies
   * it matches the root it resolved before trusting anything else the server says.
   *
   * @generated from field: string workspace_root = 1;
   */
  workspaceRoot: string;

  /**
   * @generated from field: int32 pid = 2;
   */
  pid: number;

  /**
   * @generated from field: int32 port = 3;
   */
  port: number;

  /**
   * @generated from field: string version = 4;
   */
  version: string;

  /**
   * @generated from field: grpcview.v1.ServerExecutable executable = 5;
   */
  executable?: ServerExecutable | undefined;

  /**
   * Zero when the server never idles out, which is every hand-run one.
   *
   * @generated from field: google.protobuf.Duration idle_timeout = 6;
   */
  idleTimeout?: Duration | undefined;
};

/**
 * Describes the message grpcview.v1.ServerInfoResponse.
 * Use `create(ServerInfoResponseSchema)` to create a new message.
 */
export declare const ServerInfoResponseSchema: GenMessage<ServerInfoResponse>;

/**
 * @generated from message grpcview.v1.ShutdownRequest
 */
export declare type ShutdownRequest = Message<"grpcview.v1.ShutdownRequest"> & {
};

/**
 * Describes the message grpcview.v1.ShutdownRequest.
 * Use `create(ShutdownRequestSchema)` to create a new message.
 */
export declare const ShutdownRequestSchema: GenMessage<ShutdownRequest>;

/**
 * @generated from message grpcview.v1.ShutdownResponse
 */
export declare type ShutdownResponse = Message<"grpcview.v1.ShutdownResponse"> & {
};

/**
 * Describes the message grpcview.v1.ShutdownResponse.
 * Use `create(ShutdownResponseSchema)` to create a new message.
 */
export declare const ShutdownResponseSchema: GenMessage<ShutdownResponse>;

/**
 * One registered server as the answering one sees it. The registration fields are read off
 * the file; everything else is what that server itself answered, so a row that is not
 * running carries only what the file claimed.
 *
 * @generated from message grpcview.v1.ServerEntry
 */
export declare type ServerEntry = Message<"grpcview.v1.ServerEntry"> & {
  /**
   * @generated from field: string workspace_root = 1;
   */
  workspaceRoot: string;

  /**
   * @generated from field: int32 port = 2;
   */
  port: number;

  /**
   * @generated from field: int32 pid = 3;
   */
  pid: number;

  /**
   * @generated from field: string version = 4;
   */
  version: string;

  /**
   * @generated from field: grpcview.v1.ServerExecutable executable = 5;
   */
  executable?: ServerExecutable | undefined;

  /**
   * Zero when it never idles out, which is every hand-run one.
   *
   * @generated from field: google.protobuf.Duration idle_timeout = 6;
   */
  idleTimeout?: Duration | undefined;

  /**
   * @generated from field: int64 started_unix = 7;
   */
  startedUnix: bigint;

  /**
   * A registration is a hint: false means nothing answered on that port, or what did
   * reports another root. The file outliving its process is the ordinary case.
   *
   * @generated from field: bool running = 8;
   */
  running: boolean;

  /**
   * The server answering this call, so a client can tell which row it is talking through.
   *
   * @generated from field: bool current = 9;
   */
  current: boolean;

  /**
   * Answers, and it is that workspace's, but it is running a different build than the
   * server answering this call.
   *
   * @generated from field: bool skewed = 10;
   */
  skewed: boolean;
};

/**
 * Describes the message grpcview.v1.ServerEntry.
 * Use `create(ServerEntrySchema)` to create a new message.
 */
export declare const ServerEntrySchema: GenMessage<ServerEntry>;

/**
 * @generated from message grpcview.v1.ListServersRequest
 */
export declare type ListServersRequest = Message<"grpcview.v1.ListServersRequest"> & {
};

/**
 * Describes the message grpcview.v1.ListServersRequest.
 * Use `create(ListServersRequestSchema)` to create a new message.
 */
export declare const ListServersRequestSchema: GenMessage<ListServersRequest>;

/**
 * @generated from message grpcview.v1.ListServersResponse
 */
export declare type ListServersResponse = Message<"grpcview.v1.ListServersResponse"> & {
  /**
   * Every registration on this machine for this user, ordered by workspace root.
   *
   * @generated from field: repeated grpcview.v1.ServerEntry servers = 1;
   */
  servers: ServerEntry[];
};

/**
 * Describes the message grpcview.v1.ListServersResponse.
 * Use `create(ListServersResponseSchema)` to create a new message.
 */
export declare const ListServersResponseSchema: GenMessage<ListServersResponse>;

/**
 * @generated from message grpcview.v1.StopServerRequest
 */
export declare type StopServerRequest = Message<"grpcview.v1.StopServerRequest"> & {
  /**
   * Absolute, and matched against the registration rather than against a port: a port is
   * reused, a root is the identity.
   *
   * @generated from field: string workspace_root = 1;
   */
  workspaceRoot: string;
};

/**
 * Describes the message grpcview.v1.StopServerRequest.
 * Use `create(StopServerRequestSchema)` to create a new message.
 */
export declare const StopServerRequestSchema: GenMessage<StopServerRequest>;

/**
 * @generated from message grpcview.v1.StopServerResponse
 */
export declare type StopServerResponse = Message<"grpcview.v1.StopServerResponse"> & {
};

/**
 * Describes the message grpcview.v1.StopServerResponse.
 * Use `create(StopServerResponseSchema)` to create a new message.
 */
export declare const StopServerResponseSchema: GenMessage<StopServerResponse>;

/**
 * @generated from service grpcview.v1.WorkspaceService
 */
export declare const WorkspaceService: GenService<{
  /**
   * Appends at LOWEST priority, or refreshes in place when the id already exists.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.AddDescriptorSource
   */
  addDescriptorSource: {
    methodKind: "unary";
    input: typeof AddDescriptorSourceRequestSchema;
    output: typeof AddDescriptorSourceResponseSchema;
  },
  /**
   * Never dials, so an unreachable sibling source cannot block a removal. Services
   * only this source provided leave the services list; requests against them remain
   * saved but stop being invocable.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.RemoveDescriptorSource
   */
  removeDescriptorSource: {
    methodKind: "unary";
    input: typeof RemoveDescriptorSourceRequestSchema;
    output: typeof RemoveDescriptorSourceResponseSchema;
  },
  /**
   * Re-dials a reflection target, or re-reads an upload. An unreachable target stays
   * listed with the reason in its resolved.error rather than being dropped.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.RefreshDescriptorSource
   */
  refreshDescriptorSource: {
    methodKind: "unary";
    input: typeof RefreshDescriptorSourceRequestSchema;
    output: typeof RefreshDescriptorSourceResponseSchema;
  },
  /**
   * Sets which source wins when several describe the same protos.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.ReorderDescriptorSources
   */
  reorderDescriptorSources: {
    methodKind: "unary";
    input: typeof ReorderDescriptorSourcesRequestSchema;
    output: typeof ReorderDescriptorSourcesResponseSchema;
  },
  /**
   * Moves one source's descriptors between the committed sidecar and the local
   * blob store. Never dials or builds, so committing a source that has never
   * resolved is InvalidArgument.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.SetDescriptorSourceCommit
   */
  setDescriptorSourceCommit: {
    methodKind: "unary";
    input: typeof SetDescriptorSourceCommitRequestSchema;
    output: typeof SetDescriptorSourceCommitResponseSchema;
  },
  /**
   * A collection that does not exist is NotFound, never created on demand.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetRequestSchema;
    output: typeof GetResponseSchema;
  },
  /**
   * Deliberately cheap: reads manifests, never trees. Eagerly Getting every
   * collection instead is the one way to make this design feel slow.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.ListCollections
   */
  listCollections: {
    methodKind: "unary";
    input: typeof ListCollectionsRequestSchema;
    output: typeof ListCollectionsResponseSchema;
  },
  /**
   * Trusts or un-trusts this workspace ROOT, like VS Code's Workspace Trust: a
   * committed bazel label means opening a repo could run arbitrary code. Trust is
   * on the folder, not its content. Revoking un-resolves nothing — only a future
   * build is refused.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.SetWorkspaceTrust
   */
  setWorkspaceTrust: {
    methodKind: "unary";
    input: typeof SetWorkspaceTrustRequestSchema;
    output: typeof SetWorkspaceTrustResponseSchema;
  },
  /**
   * Lists the workspace's descriptor-set-producing labels, so adding a bazel
   * source can be a pick. Runs `bazel query`, which loads BUILD files, so it is
   * trust-gated: an untrusted workspace gets FailedPrecondition, not an empty list.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.ListBazelTargets
   */
  listBazelTargets: {
    methodKind: "unary";
    input: typeof ListBazelTargetsRequestSchema;
    output: typeof ListBazelTargetsResponseSchema;
  },
  /**
   * Every importable `.ts` under the workspace root, so the editor's module resolution
   * (Monaco `compilerOptions.paths`) can mirror what the bundler's `@/` / `#/` plugin
   * actually resolves at compile time.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.ListWorkspaceModules
   */
  listWorkspaceModules: {
    methodKind: "unary";
    input: typeof ListWorkspaceModulesRequestSchema;
    output: typeof ListWorkspaceModulesResponseSchema;
  },
  /**
   * Creates the collection's directory in the workspace. An existing collection at
   * that path is AlreadyExists, never adopted.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.CreateCollection
   */
  createCollection: {
    methodKind: "unary";
    input: typeof CreateCollectionRequestSchema;
    output: typeof CreateCollectionResponseSchema;
  },
  /**
   * Renames a collection's display name and/or MOVES its directory. The local
   * state (history, resolve caches) moves with it; nothing is re-resolved.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.UpdateCollection
   */
  updateCollection: {
    methodKind: "unary";
    input: typeof UpdateCollectionRequestSchema;
    output: typeof UpdateCollectionResponseSchema;
  },
  /**
   * A name colliding with an existing sibling is FailedPrecondition.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.CreateFolder
   */
  createFolder: {
    methodKind: "unary";
    input: typeof CreateFolderRequestSchema;
    output: typeof CreateFolderResponseSchema;
  },
  /**
   * The body starts empty. Saving is optional: invoke calls a method without one.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.CreateRequest
   */
  createRequest: {
    methodKind: "unary";
    input: typeof CreateRequestRequestSchema;
    output: typeof CreateRequestResponseSchema;
  },
  /**
   * Deletes requests AND folders, a folder recursively. An item that is not there is
   * a silent success, so check the returned tree rather than relying on an error.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.DeleteRequest
   */
  deleteRequest: {
    methodKind: "unary";
    input: typeof DeleteRequestRequestSchema;
    output: typeof DeleteRequestResponseSchema;
  },
  /**
   * Partial update: everything but the fields locating the request is optional, and an
   * omitted one is left as it was. `target` and `middleware` change only when their
   * update_ set-flag is true.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.UpdateRequest
   */
  updateRequest: {
    methodKind: "unary";
    input: typeof UpdateRequestRequestSchema;
    output: typeof UpdateRequestResponseSchema;
  },
  /**
   * Sets the metadata script requests inside the folder inherit, so shared headers are
   * written once. Present but empty clears it; omitted leaves it unchanged.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.UpdateFolder
   */
  updateFolder: {
    methodKind: "unary";
    input: typeof UpdateFolderRequestSchema;
    output: typeof UpdateFolderResponseSchema;
  },
  /**
   * Reparents and/or reorders one item. Moving a folder into its own descendant is
   * FailedPrecondition.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.MoveItem
   */
  moveItem: {
    methodKind: "unary";
    input: typeof MoveItemRequestSchema;
    output: typeof MoveItemResponseSchema;
  },
  /**
   * Returns the status, response body, request/response metadata and latency.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.Invoke
   */
  invoke: {
    methodKind: "unary";
    input: typeof InvokeRequestSchema;
    output: typeof InvokeResponseSchema;
  },
  /**
   * Handles any streaming kind, modeled as server-streaming.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.InvokeStreaming
   */
  invokeStreaming: {
    methodKind: "server_streaming";
    input: typeof InvokeStreamRequestSchema;
    output: typeof InvokeStreamingResponseSchema;
  },
  /**
   * Reports a status the target returned in the response, never as an error.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.InvokeSaved
   */
  invokeSaved: {
    methodKind: "unary";
    input: typeof InvokeSavedRequestSchema;
    output: typeof InvokeSavedResponseSchema;
  },
  /**
   * InvokeSaved for any streaming kind.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.InvokeSavedStreaming
   */
  invokeSavedStreaming: {
    methodKind: "server_streaming";
    input: typeof InvokeSavedStreamRequestSchema;
    output: typeof InvokeStreamingResponseSchema;
  },
  /**
   * Answers from already-resolved definitions, so it works with the target down.
   * Doc comments survive only if the winning source carried them.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.DescribeMethod
   */
  describeMethod: {
    methodKind: "unary";
    input: typeof DescribeMethodRequestSchema;
    output: typeof DescribeMethodResponseSchema;
  },
  /**
   * Uses a fresh isolated instance: no capabilities, no collection state.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.RunScript
   */
  runScript: {
    methodKind: "unary";
    input: typeof RunScriptRequestSchema;
    output: typeof RunScriptResponseSchema;
  },
  /**
   * Creates it empty; use UpdateScript to fill in the source.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.CreateScript
   */
  createScript: {
    methodKind: "unary";
    input: typeof CreateScriptRequestSchema;
    output: typeof CreateScriptResponseSchema;
  },
  /**
   * Partial update: an omitted field is left unchanged. Renaming onto an existing
   * script's path fails.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.UpdateScript
   */
  updateScript: {
    methodKind: "unary";
    input: typeof UpdateScriptRequestSchema;
    output: typeof UpdateScriptResponseSchema;
  },
  /**
   * Requests still listing it as middleware keep the dangling reference and fail when
   * invoked, so clear it from them first.
   *
   * @generated from rpc grpcview.v1.WorkspaceService.DeleteScript
   */
  deleteScript: {
    methodKind: "unary";
    input: typeof DeleteScriptRequestSchema;
    output: typeof DeleteScriptResponseSchema;
  },
}>;

/**
 * Server lifecycle, deliberately NOT part of WorkspaceService: it is a property of the
 * process, it is meaningless in-process, and Shutdown has no business being an MCP tool.
 *
 * @generated from service grpcview.v1.ServerService
 */
export declare const ServerService: GenService<{
  /**
   * Never fails. Answering it at all is what proves a listener is this workspace's.
   *
   * @generated from rpc grpcview.v1.ServerService.ServerInfo
   */
  serverInfo: {
    methodKind: "unary";
    input: typeof ServerInfoRequestSchema;
    output: typeof ServerInfoResponseSchema;
  },
  /**
   * Returns first, then stops accepting, drains in flight requests and unlinks the
   * registration. Asking over the wire is why the design never has to signal a pid.
   *
   * @generated from rpc grpcview.v1.ServerService.Shutdown
   */
  shutdown: {
    methodKind: "unary";
    input: typeof ShutdownRequestSchema;
    output: typeof ShutdownResponseSchema;
  },
  /**
   * Every server registered on this machine, this one included, each verified over the
   * wire before it is reported running. Reads the registry, never a process table.
   *
   * @generated from rpc grpcview.v1.ServerService.ListServers
   */
  listServers: {
    methodKind: "unary";
    input: typeof ListServersRequestSchema;
    output: typeof ListServersResponseSchema;
  },
  /**
   * Asks another workspace's server to exit, after verifying it is that workspace's, and
   * waits for it to go. Naming this server's own root is Shutdown.
   *
   * @generated from rpc grpcview.v1.ServerService.StopServer
   */
  stopServer: {
    methodKind: "unary";
    input: typeof StopServerRequestSchema;
    output: typeof StopServerResponseSchema;
  },
}>;

