// @generated by protoc-gen-connect-query v2.2.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file proto/grpcview/v1/service.proto (package grpcview.v1, syntax proto3)
/* eslint-disable */

import { WorkspaceService } from "./service_pb";

/**
 * AddDescriptorSource adds a descriptor source to the workspace — where its
 * definitions come from. A source whose id already exists is refreshed in place
 * (see AddDescriptorSourceRequest.file_name); a new one is appended at LOWEST
 * priority, so adding never changes which source an existing service resolves
 * from. Only the added/refreshed source is resolved (one network round-trip for
 * reflection); the merged view is rebuilt from every source's cached resolve.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.AddDescriptorSource
 */
export const addDescriptorSource: typeof WorkspaceService["method"]["addDescriptorSource"];
/**
 * RemoveDescriptorSource drops the source with the given id and rebuilds the
 * merged view from the cached resolves of those that remain — no network, so
 * an unreachable sibling source can never block a removal.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.RemoveDescriptorSource
 */
export const removeDescriptorSource: typeof WorkspaceService["method"]["removeDescriptorSource"];
/**
 * RefreshDescriptorSource re-resolves exactly one source (re-dialing a
 * reflection target, re-parsing an upload) and rebuilds the merged view.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.RefreshDescriptorSource
 */
export const refreshDescriptorSource: typeof WorkspaceService["method"]["refreshDescriptorSource"];
/**
 * ReorderDescriptorSources sets the source priority order and rebuilds the
 * merged view from the cached resolves — no network. This is how you switch
 * which source's definitions win when several describe the same protos.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.ReorderDescriptorSources
 */
export const reorderDescriptorSources: typeof WorkspaceService["method"]["reorderDescriptorSources"];
/**
 * Get returns the workspace snapshot
 *
 * @generated from rpc grpcview.v1.WorkspaceService.Get
 */
export const get: typeof WorkspaceService["method"]["get"];
/**
 * CreateFolder creates a new folder in the workspace
 *
 * @generated from rpc grpcview.v1.WorkspaceService.CreateFolder
 */
export const createFolder: typeof WorkspaceService["method"]["createFolder"];
/**
 * CreateRequest creates a new request in the workspace
 *
 * @generated from rpc grpcview.v1.WorkspaceService.CreateRequest
 */
export const createRequest: typeof WorkspaceService["method"]["createRequest"];
/**
 * DeleteRequest deletes a request from the workspace
 *
 * @generated from rpc grpcview.v1.WorkspaceService.DeleteRequest
 */
export const deleteRequest: typeof WorkspaceService["method"]["deleteRequest"];
/**
 * UpdateRequest updates a request in the workspace
 *
 * @generated from rpc grpcview.v1.WorkspaceService.UpdateRequest
 */
export const updateRequest: typeof WorkspaceService["method"]["updateRequest"];
/**
 * UpdateFolder updates a folder's metadata script in the workspace
 *
 * @generated from rpc grpcview.v1.WorkspaceService.UpdateFolder
 */
export const updateFolder: typeof WorkspaceService["method"]["updateFolder"];
/**
 * MoveItem reparents and/or reorders an item; a drop into the moved folder's own
 * subtree is rejected server-side.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.MoveItem
 */
export const moveItem: typeof WorkspaceService["method"]["moveItem"];
/**
 * Invoke executes a unary RPC against a target server and returns the result
 * (status, response body, request/response metadata, latency).
 *
 * @generated from rpc grpcview.v1.WorkspaceService.Invoke
 */
export const invoke: typeof WorkspaceService["method"]["invoke"];
/**
 * Runs the request saved at a collection path and returns the result of the call.
 *
 * Requires workspace_name, item_name (the request's display name) and path (its
 * parent folders, outermost first; empty at the top level). The saved request's own
 * body, metadata, middleware and target are used, so the caller supplies no body of
 * its own. params is a free-form object its body and metadata read values from. For one
 * run only: target overrides where the call goes, messages override the request
 * bodies as JSON text, record_history defaults to true, and dry_run evaluates
 * everything but sends nothing.
 *
 * Returns the response message, the call's gRPC status, request and response
 * metadata and the latency — or, for a dry run, only the resolved request. A status
 * the target returned is reported in the response, never as an error. A streaming
 * method needs the streaming form of this call.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.InvokeSaved
 */
export const invokeSaved: typeof WorkspaceService["method"]["invokeSaved"];
/**
 * RunScript evaluates a script through the scripting engine and returns its
 * value, console output, and any error — the scratchpad and the per-kind
 * test-run surface that validates the engine end to end.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.RunScript
 */
export const runScript: typeof WorkspaceService["method"]["runScript"];
/**
 * CreateScript creates a new, empty script of a given kind in the workspace.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.CreateScript
 */
export const createScript: typeof WorkspaceService["method"]["createScript"];
/**
 * UpdateScript edits a script's source and/or renames it.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.UpdateScript
 */
export const updateScript: typeof WorkspaceService["method"]["updateScript"];
/**
 * DeleteScript removes a script from the workspace.
 *
 * @generated from rpc grpcview.v1.WorkspaceService.DeleteScript
 */
export const deleteScript: typeof WorkspaceService["method"]["deleteScript"];
