// @generated by protoc-gen-es v2.12.1 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file proto/grpcview/v1/workspace.proto (package grpcview.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message as Message$1 } from "@bufbuild/protobuf";
import type { Any, Duration, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file proto/grpcview/v1/workspace.proto.
 */
export declare const file_proto_grpcview_v1_workspace: GenFile;

/**
 * Copy of google.rpc.Status: rules_ts cannot import google/rpc/status.proto.
 *
 * @generated from message grpcview.v1.Status
 */
export declare type Status = Message$1<"grpcview.v1.Status"> & {
  /**
   * @generated from field: int32 code = 1;
   */
  code: number;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: repeated google.protobuf.Any details = 3;
   */
  details: Any[];
};

/**
 * Describes the message grpcview.v1.Status.
 * Use `create(StatusSchema)` to create a new message.
 */
export declare const StatusSchema: GenMessage<Status>;

/**
 * @generated from message grpcview.v1.Server
 */
export declare type Server = Message$1<"grpcview.v1.Server"> & {
  /**
   * Dial string, host:port.
   *
   * @generated from field: string address = 1;
   */
  address: string;

  /**
   * @generated from field: optional grpcview.v1.Server.TLS tls = 2;
   */
  tls?: Server_TLS | undefined;
};

/**
 * Describes the message grpcview.v1.Server.
 * Use `create(ServerSchema)` to create a new message.
 */
export declare const ServerSchema: GenMessage<Server>;

/**
 * @generated from message grpcview.v1.Server.TLS
 */
export declare type Server_TLS = Message$1<"grpcview.v1.Server.TLS"> & {
};

/**
 * Describes the message grpcview.v1.Server.TLS.
 * Use `create(Server_TLSSchema)` to create a new message.
 */
export declare const Server_TLSSchema: GenMessage<Server_TLS>;

/**
 * @generated from message grpcview.v1.Message
 */
export declare type Message = Message$1<"grpcview.v1.Message"> & {
  /**
   * @generated from field: string package = 1;
   */
  package: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Proto file path defining this message, e.g. proto/foo/v1/foo.proto.
   *
   * @generated from field: string file = 4;
   */
  file: string;
};

/**
 * Describes the message grpcview.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export declare const MessageSchema: GenMessage<Message>;

/**
 * @generated from message grpcview.v1.Method
 */
export declare type Method = Message$1<"grpcview.v1.Method"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: grpcview.v1.Message input = 2;
   */
  input?: Message | undefined;

  /**
   * @generated from field: grpcview.v1.Message output = 3;
   */
  output?: Message | undefined;

  /**
   * @generated from field: bool client_streaming = 4;
   */
  clientStreaming: boolean;

  /**
   * @generated from field: bool server_streaming = 5;
   */
  serverStreaming: boolean;
};

/**
 * Describes the message grpcview.v1.Method.
 * Use `create(MethodSchema)` to create a new message.
 */
export declare const MethodSchema: GenMessage<Method>;

/**
 * @generated from message grpcview.v1.Service
 */
export declare type Service = Message$1<"grpcview.v1.Service"> & {
  /**
   * @generated from field: string package = 1;
   */
  package: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: repeated grpcview.v1.Method methods = 3;
   */
  methods: Method[];

  /**
   * First reflection source serving it — the default invoke target; unset if none.
   *
   * @generated from field: optional grpcview.v1.Server source = 4;
   */
  source?: Server | undefined;
};

/**
 * Describes the message grpcview.v1.Service.
 * Use `create(ServiceSchema)` to create a new message.
 */
export declare const ServiceSchema: GenMessage<Service>;

/**
 * Priority-ordered: the first source to define a file, or serve a service, wins.
 *
 * @generated from message grpcview.v1.DescriptorSource
 */
export declare type DescriptorSource = Message$1<"grpcview.v1.DescriptorSource"> & {
  /**
   * "reflection:<address>" (+"+tls") or "upload:<file name>"; adding an existing
   * id refreshes that source in place.
   *
   * @generated from field: string id = 3;
   */
  id: string;

  /**
   * @generated from oneof grpcview.v1.DescriptorSource.source
   */
  source: {
    /**
     * @generated from field: grpcview.v1.Upload upload = 1;
     */
    value: Upload;
    case: "upload";
  } | {
    /**
     * @generated from field: grpcview.v1.Server reflection = 2;
     */
    value: Server;
    case: "reflection";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: grpcview.v1.Resolved resolved = 4;
   */
  resolved?: Resolved | undefined;
};

/**
 * Describes the message grpcview.v1.DescriptorSource.
 * Use `create(DescriptorSourceSchema)` to create a new message.
 */
export declare const DescriptorSourceSchema: GenMessage<DescriptorSource>;

/**
 * The descriptor bytes are never sent to the client, only this file name.
 *
 * @generated from message grpcview.v1.Upload
 */
export declare type Upload = Message$1<"grpcview.v1.Upload"> & {
  /**
   * @generated from field: string file_name = 1;
   */
  fileName: string;
};

/**
 * Describes the message grpcview.v1.Upload.
 * Use `create(UploadSchema)` to create a new message.
 */
export declare const UploadSchema: GenMessage<Upload>;

/**
 * @generated from message grpcview.v1.Resolved
 */
export declare type Resolved = Message$1<"grpcview.v1.Resolved"> & {
  /**
   * @generated from field: int32 file_count = 1;
   */
  fileCount: number;

  /**
   * @generated from field: repeated string service_names = 2;
   */
  serviceNames: string[];

  /**
   * Subset of service_names whose descriptors the collection takes from here.
   *
   * @generated from field: repeated string won_service_names = 3;
   */
  wonServiceNames: string[];

  /**
   * Why the last resolve failed; empty when it succeeded.
   *
   * @generated from field: string error = 4;
   */
  error: string;
};

/**
 * Describes the message grpcview.v1.Resolved.
 * Use `create(ResolvedSchema)` to create a new message.
 */
export declare const ResolvedSchema: GenMessage<Resolved>;

/**
 * @generated from message grpcview.v1.Folder
 */
export declare type Folder = Message$1<"grpcview.v1.Folder"> & {
  /**
   * @generated from field: repeated grpcview.v1.Item items = 1;
   */
  items: Item[];

  /**
   * TypeScript module feeding the gv.metadata.inherit() ancestor chain.
   *
   * @generated from field: string draft_metadata_script = 2;
   */
  draftMetadataScript: string;
};

/**
 * Describes the message grpcview.v1.Folder.
 * Use `create(FolderSchema)` to create a new message.
 */
export declare const FolderSchema: GenMessage<Folder>;

/**
 * @generated from message grpcview.v1.History
 */
export declare type History = Message$1<"grpcview.v1.History"> & {
  /**
   * @generated from field: grpcview.v1.History.Request request = 1;
   */
  request?: History_Request | undefined;

  /**
   * @generated from field: grpcview.v1.History.Response response = 2;
   */
  response?: History_Response | undefined;
};

/**
 * Describes the message grpcview.v1.History.
 * Use `create(HistorySchema)` to create a new message.
 */
export declare const HistorySchema: GenMessage<History>;

/**
 * @generated from message grpcview.v1.History.Request
 */
export declare type History_Request = Message$1<"grpcview.v1.History.Request"> & {
  /**
   * @generated from field: string service = 1;
   */
  service: string;

  /**
   * @generated from field: string method = 2;
   */
  method: string;

  /**
   * @generated from field: bytes body = 3;
   */
  body: Uint8Array;

  /**
   * @generated from field: google.protobuf.Struct metadata = 4;
   */
  metadata?: JsonObject | undefined;
};

/**
 * Describes the message grpcview.v1.History.Request.
 * Use `create(History_RequestSchema)` to create a new message.
 */
export declare const History_RequestSchema: GenMessage<History_Request>;

/**
 * @generated from message grpcview.v1.History.Response
 */
export declare type History_Response = Message$1<"grpcview.v1.History.Response"> & {
  /**
   * @generated from field: grpcview.v1.Status status = 1;
   */
  status?: Status | undefined;

  /**
   * @generated from field: bytes response = 2;
   */
  response: Uint8Array;

  /**
   * @generated from field: google.protobuf.Struct metadata = 3;
   */
  metadata?: JsonObject | undefined;

  /**
   * @generated from field: google.protobuf.Duration latency = 4;
   */
  latency?: Duration | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 5;
   */
  timestamp?: Timestamp | undefined;
};

/**
 * Describes the message grpcview.v1.History.Response.
 * Use `create(History_ResponseSchema)` to create a new message.
 */
export declare const History_ResponseSchema: GenMessage<History_Response>;

/**
 * @generated from message grpcview.v1.Request
 */
export declare type Request = Message$1<"grpcview.v1.Request"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string service = 2;
   */
  service: string;

  /**
   * @generated from field: string method = 3;
   */
  method: string;

  /**
   * @generated from field: string draft_body = 4;
   */
  draftBody: string;

  /**
   * @generated from field: repeated grpcview.v1.History history = 6;
   */
  history: History[];

  /**
   * Ordered display names of the MIDDLEWARE scripts run before the call.
   *
   * @generated from field: repeated string middleware = 7;
   */
  middleware: string[];

  /**
   * TypeScript module returning {[key: string]: string[]}, evaluated on invoke.
   *
   * @generated from field: string draft_metadata_script = 9;
   */
  draftMetadataScript: string;

  /**
   * Unset means "use the collection's first reflection source".
   *
   * @generated from field: optional grpcview.v1.Server target = 10;
   */
  target?: Server | undefined;
};

/**
 * Describes the message grpcview.v1.Request.
 * Use `create(RequestSchema)` to create a new message.
 */
export declare const RequestSchema: GenMessage<Request>;

/**
 * @generated from message grpcview.v1.Request.Response
 */
export declare type Request_Response = Message$1<"grpcview.v1.Request.Response"> & {
  /**
   * @generated from field: grpcview.v1.Status status = 1;
   */
  status?: Status | undefined;

  /**
   * @generated from field: bytes response = 2;
   */
  response: Uint8Array;

  /**
   * @generated from field: google.protobuf.Struct request_metadata = 3;
   */
  requestMetadata?: JsonObject | undefined;

  /**
   * @generated from field: google.protobuf.Struct response_metadata = 4;
   */
  responseMetadata?: JsonObject | undefined;

  /**
   * @generated from field: google.protobuf.Duration latency = 5;
   */
  latency?: Duration | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 6;
   */
  timestamp?: Timestamp | undefined;
};

/**
 * Describes the message grpcview.v1.Request.Response.
 * Use `create(Request_ResponseSchema)` to create a new message.
 */
export declare const Request_ResponseSchema: GenMessage<Request_Response>;

/**
 * @generated from message grpcview.v1.Item
 */
export declare type Item = Message$1<"grpcview.v1.Item"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The stable on-disk directory name. A rename never changes it, so UI state
   * (tabs, drafts, expansion) is keyed by it. RPC addressing stays on
   * display-name paths; this is identity, not an address. Empty on the synthetic
   * root item, which has no directory of its own.
   *
   * @generated from field: string slug = 4;
   */
  slug: string;

  /**
   * @generated from oneof grpcview.v1.Item.content
   */
  content: {
    /**
     * @generated from field: grpcview.v1.Folder folder = 2;
     */
    value: Folder;
    case: "folder";
  } | {
    /**
     * @generated from field: grpcview.v1.Request request = 3;
     */
    value: Request;
    case: "request";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message grpcview.v1.Item.
 * Use `create(ItemSchema)` to create a new message.
 */
export declare const ItemSchema: GenMessage<Item>;

/**
 * @generated from message grpcview.v1.Script
 */
export declare type Script = Message$1<"grpcview.v1.Script"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: grpcview.v1.ScriptKind kind = 2;
   */
  kind: ScriptKind;

  /**
   * @generated from field: string source = 3;
   */
  source: string;
};

/**
 * Describes the message grpcview.v1.Script.
 * Use `create(ScriptSchema)` to create a new message.
 */
export declare const ScriptSchema: GenMessage<Script>;

/**
 * @generated from message grpcview.v1.Collection
 */
export declare type Collection = Message$1<"grpcview.v1.Collection"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: grpcview.v1.Item item = 2;
   */
  item?: Item | undefined;

  /**
   * @generated from field: repeated grpcview.v1.DescriptorSource sources = 3;
   */
  sources: DescriptorSource[];

  /**
   * Derived by the priority merge: one entry per fully-qualified service.
   *
   * @generated from field: repeated grpcview.v1.Service services = 4;
   */
  services: Service[];

  /**
   * @generated from field: repeated grpcview.v1.Script scripts = 5;
   */
  scripts: Script[];

  /**
   * Merged, deduped FileDescriptorSet; derived and cached, never persisted.
   *
   * @generated from field: bytes descriptor_set = 6;
   */
  descriptorSet: Uint8Array;
};

/**
 * Describes the message grpcview.v1.Collection.
 * Use `create(CollectionSchema)` to create a new message.
 */
export declare const CollectionSchema: GenMessage<Collection>;

/**
 * @generated from enum grpcview.v1.ScriptKind
 */
export enum ScriptKind {
  /**
   * @generated from enum value: SCRIPT_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SCRIPT_KIND_GENERATOR = 1;
   */
  GENERATOR = 1,

  /**
   * @generated from enum value: SCRIPT_KIND_MIDDLEWARE = 2;
   */
  MIDDLEWARE = 2,

  /**
   * @generated from enum value: SCRIPT_KIND_SCENARIO = 3;
   */
  SCENARIO = 3,
}

/**
 * Describes the enum grpcview.v1.ScriptKind.
 */
export declare const ScriptKindSchema: GenEnum<ScriptKind>;

