// @generated by protoc-gen-es v2.12.1 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file proto/grpcview/v1/workspace.proto (package grpcview.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message as Message$1 } from "@bufbuild/protobuf";
import type { Any, Duration, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file proto/grpcview/v1/workspace.proto.
 */
export declare const file_proto_grpcview_v1_workspace: GenFile;

/**
 * Status is a copy of google.rpc.Status, this is a hack, because we can't import google/rpc/status.proto for rules_ts
 *
 * @generated from message grpcview.v1.Status
 */
export declare type Status = Message$1<"grpcview.v1.Status"> & {
  /**
   * @generated from field: int32 code = 1;
   */
  code: number;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: repeated google.protobuf.Any details = 3;
   */
  details: Any[];
};

/**
 * Describes the message grpcview.v1.Status.
 * Use `create(StatusSchema)` to create a new message.
 */
export declare const StatusSchema: GenMessage<Status>;

/**
 * @generated from message grpcview.v1.Server
 */
export declare type Server = Message$1<"grpcview.v1.Server"> & {
  /**
   * address is the target's dial string — a host:port (grpc.NewClient accepts it
   * verbatim). It is both a reflection source's address and a request's invoke
   * target.
   *
   * @generated from field: string address = 1;
   */
  address: string;

  /**
   * @generated from field: optional grpcview.v1.Server.TLS tls = 2;
   */
  tls?: Server_TLS | undefined;
};

/**
 * Describes the message grpcview.v1.Server.
 * Use `create(ServerSchema)` to create a new message.
 */
export declare const ServerSchema: GenMessage<Server>;

/**
 * @generated from message grpcview.v1.Server.TLS
 */
export declare type Server_TLS = Message$1<"grpcview.v1.Server.TLS"> & {
};

/**
 * Describes the message grpcview.v1.Server.TLS.
 * Use `create(Server_TLSSchema)` to create a new message.
 */
export declare const Server_TLSSchema: GenMessage<Server_TLS>;

/**
 * @generated from message grpcview.v1.Message
 */
export declare type Message = Message$1<"grpcview.v1.Message"> & {
  /**
   * @generated from field: string package = 1;
   */
  package: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * file is the proto file path that defines this message (e.g.
   * proto/foo/v1/foo.proto). It is the protoc-gen-es fileToGenerate selector and
   * identifies which generated _pb.ts exports this message's Json type
   * (ts-request-body-plan §T2/§4.4). Derived from the resolved descriptor.
   *
   * @generated from field: string file = 4;
   */
  file: string;
};

/**
 * Describes the message grpcview.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export declare const MessageSchema: GenMessage<Message>;

/**
 * @generated from message grpcview.v1.Method
 */
export declare type Method = Message$1<"grpcview.v1.Method"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: grpcview.v1.Message input = 2;
   */
  input?: Message | undefined;

  /**
   * @generated from field: grpcview.v1.Message output = 3;
   */
  output?: Message | undefined;

  /**
   * client_streaming / server_streaming carry the method's real streaming kind,
   * populated from reflection's IsClientStreaming/IsServerStreaming. The four
   * combinations map to unary (both false), server-streaming, client-streaming,
   * and bidi (both true).
   *
   * @generated from field: bool client_streaming = 4;
   */
  clientStreaming: boolean;

  /**
   * @generated from field: bool server_streaming = 5;
   */
  serverStreaming: boolean;
};

/**
 * Describes the message grpcview.v1.Method.
 * Use `create(MethodSchema)` to create a new message.
 */
export declare const MethodSchema: GenMessage<Method>;

/**
 * @generated from message grpcview.v1.Service
 */
export declare type Service = Message$1<"grpcview.v1.Service"> & {
  /**
   * @generated from field: string package = 1;
   */
  package: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: repeated grpcview.v1.Method methods = 3;
   */
  methods: Method[];

  /**
   * source is the reflection server this service's schema was resolved from — the
   * natural default invoke target for a request against it (see resolveTarget in
   * invoke.go, and sourceForService in the UI). Unset for services from a
   * descriptor-set upload (no dial target) or an older cache; such requests fall
   * back to the workspace's first reflection source.
   *
   * @generated from field: optional grpcview.v1.Server source = 4;
   */
  source?: Server | undefined;
};

/**
 * Describes the message grpcview.v1.Service.
 * Use `create(ServiceSchema)` to create a new message.
 */
export declare const ServiceSchema: GenMessage<Service>;

/**
 * @generated from message grpcview.v1.DescriptorSource
 */
export declare type DescriptorSource = Message$1<"grpcview.v1.DescriptorSource"> & {
  /**
   * @generated from oneof grpcview.v1.DescriptorSource.source
   */
  source: {
    /**
     * @generated from field: bytes descriptor_set = 1;
     */
    value: Uint8Array;
    case: "descriptorSet";
  } | {
    /**
     * @generated from field: grpcview.v1.Server reflection = 2;
     */
    value: Server;
    case: "reflection";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message grpcview.v1.DescriptorSource.
 * Use `create(DescriptorSourceSchema)` to create a new message.
 */
export declare const DescriptorSourceSchema: GenMessage<DescriptorSource>;

/**
 * @generated from message grpcview.v1.Folder
 */
export declare type Folder = Message$1<"grpcview.v1.Folder"> & {
  /**
   * @generated from field: repeated grpcview.v1.Item items = 1;
   */
  items: Item[];

  /**
   * draft_metadata_script is the folder's metadata authored as a TypeScript
   * module (`export default (): Metadata => ({ ... })`), mirroring
   * Request.draft_metadata_script. It feeds the ancestor-folder metadata chain
   * gv.metadata.inherit() folds over (gv-features-plan.md Feature 1): a request
   * (or a descendant folder) that spreads `{ ...gv.metadata.inherit() }` picks up
   * every non-empty ancestor folder script root-to-leaf. Empty means this folder
   * contributes nothing of its own (a transparent passthrough in the fold).
   *
   * @generated from field: string draft_metadata_script = 2;
   */
  draftMetadataScript: string;
};

/**
 * Describes the message grpcview.v1.Folder.
 * Use `create(FolderSchema)` to create a new message.
 */
export declare const FolderSchema: GenMessage<Folder>;

/**
 * @generated from message grpcview.v1.History
 */
export declare type History = Message$1<"grpcview.v1.History"> & {
  /**
   * @generated from field: grpcview.v1.History.Request request = 1;
   */
  request?: History_Request | undefined;

  /**
   * @generated from field: grpcview.v1.History.Response response = 2;
   */
  response?: History_Response | undefined;
};

/**
 * Describes the message grpcview.v1.History.
 * Use `create(HistorySchema)` to create a new message.
 */
export declare const HistorySchema: GenMessage<History>;

/**
 * @generated from message grpcview.v1.History.Request
 */
export declare type History_Request = Message$1<"grpcview.v1.History.Request"> & {
  /**
   * @generated from field: string service = 1;
   */
  service: string;

  /**
   * @generated from field: string method = 2;
   */
  method: string;

  /**
   * @generated from field: bytes body = 3;
   */
  body: Uint8Array;

  /**
   * @generated from field: google.protobuf.Struct metadata = 4;
   */
  metadata?: JsonObject | undefined;
};

/**
 * Describes the message grpcview.v1.History.Request.
 * Use `create(History_RequestSchema)` to create a new message.
 */
export declare const History_RequestSchema: GenMessage<History_Request>;

/**
 * @generated from message grpcview.v1.History.Response
 */
export declare type History_Response = Message$1<"grpcview.v1.History.Response"> & {
  /**
   * @generated from field: grpcview.v1.Status status = 1;
   */
  status?: Status | undefined;

  /**
   * @generated from field: bytes response = 2;
   */
  response: Uint8Array;

  /**
   * @generated from field: google.protobuf.Struct metadata = 3;
   */
  metadata?: JsonObject | undefined;

  /**
   * @generated from field: google.protobuf.Duration latency = 4;
   */
  latency?: Duration | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 5;
   */
  timestamp?: Timestamp | undefined;
};

/**
 * Describes the message grpcview.v1.History.Response.
 * Use `create(History_ResponseSchema)` to create a new message.
 */
export declare const History_ResponseSchema: GenMessage<History_Response>;

/**
 * @generated from message grpcview.v1.Request
 */
export declare type Request = Message$1<"grpcview.v1.Request"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string service = 2;
   */
  service: string;

  /**
   * @generated from field: string method = 3;
   */
  method: string;

  /**
   * @generated from field: string draft_body = 4;
   */
  draftBody: string;

  /**
   * @generated from field: repeated grpcview.v1.History history = 6;
   */
  history: History[];

  /**
   * middleware is the ordered display names of the MIDDLEWARE-kind scripts
   * attached to this request; each runs (in this order) before the call to
   * rewrite the outgoing body/metadata (scripting-ui-plan §S3).
   *
   * @generated from field: repeated string middleware = 7;
   */
  middleware: string[];

  /**
   * draft_metadata_script is the request's metadata authored as a TypeScript
   * module (`export default (): Metadata => ({ ... })`) whose returned
   * {[key: string]: string[]} object is evaluated on invoke to build the
   * outgoing metadata. It replaces the old key/value metadata grid. Mirrors
   * draft_body — a plain UTF-8 string.
   *
   * @generated from field: string draft_metadata_script = 9;
   */
  draftMetadataScript: string;

  /**
   * target overrides where this request's invoke is sent (host:port + TLS).
   * Unset means "use the workspace's first reflection source" (see
   * resolveTarget in invoke.go). The first slice of the storage.md §6
   * target-vs-source split: a plain per-request inline target — no
   * refs/inheritance yet.
   *
   * @generated from field: optional grpcview.v1.Server target = 10;
   */
  target?: Server | undefined;
};

/**
 * Describes the message grpcview.v1.Request.
 * Use `create(RequestSchema)` to create a new message.
 */
export declare const RequestSchema: GenMessage<Request>;

/**
 * @generated from message grpcview.v1.Request.Response
 */
export declare type Request_Response = Message$1<"grpcview.v1.Request.Response"> & {
  /**
   * @generated from field: grpcview.v1.Status status = 1;
   */
  status?: Status | undefined;

  /**
   * @generated from field: bytes response = 2;
   */
  response: Uint8Array;

  /**
   * @generated from field: google.protobuf.Struct request_metadata = 3;
   */
  requestMetadata?: JsonObject | undefined;

  /**
   * @generated from field: google.protobuf.Struct response_metadata = 4;
   */
  responseMetadata?: JsonObject | undefined;

  /**
   * @generated from field: google.protobuf.Duration latency = 5;
   */
  latency?: Duration | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 6;
   */
  timestamp?: Timestamp | undefined;
};

/**
 * Describes the message grpcview.v1.Request.Response.
 * Use `create(Request_ResponseSchema)` to create a new message.
 */
export declare const Request_ResponseSchema: GenMessage<Request_Response>;

/**
 * Item is a single element in the treeview
 *
 * @generated from message grpcview.v1.Item
 */
export declare type Item = Message$1<"grpcview.v1.Item"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from oneof grpcview.v1.Item.content
   */
  content: {
    /**
     * @generated from field: grpcview.v1.Folder folder = 2;
     */
    value: Folder;
    case: "folder";
  } | {
    /**
     * @generated from field: grpcview.v1.Request request = 3;
     */
    value: Request;
    case: "request";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message grpcview.v1.Item.
 * Use `create(ItemSchema)` to create a new message.
 */
export declare const ItemSchema: GenMessage<Item>;

/**
 * Script is a saved script in the collection: a kind, a display name, and the
 * authored source. Persisted under scripts/<slug>/script.json.
 *
 * @generated from message grpcview.v1.Script
 */
export declare type Script = Message$1<"grpcview.v1.Script"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: grpcview.v1.ScriptKind kind = 2;
   */
  kind: ScriptKind;

  /**
   * @generated from field: string source = 3;
   */
  source: string;
};

/**
 * Describes the message grpcview.v1.Script.
 * Use `create(ScriptSchema)` to create a new message.
 */
export declare const ScriptSchema: GenMessage<Script>;

/**
 * Workspace is a state of the workspace
 *
 * @generated from message grpcview.v1.Workspace
 */
export declare type Workspace = Message$1<"grpcview.v1.Workspace"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: grpcview.v1.Item item = 2;
   */
  item?: Item | undefined;

  /**
   * @generated from field: repeated grpcview.v1.DescriptorSource sources = 3;
   */
  sources: DescriptorSource[];

  /**
   * @generated from field: repeated grpcview.v1.Service services = 4;
   */
  services: Service[];

  /**
   * @generated from field: repeated grpcview.v1.Script scripts = 5;
   */
  scripts: Script[];

  /**
   * descriptor_set is the merged, deduped FileDescriptorSet (transitive deps
   * incl. WKTs, topo-sorted) that protoc-gen-es needs to type request bodies
   * client-side (ts-request-body-plan §T2/§4.4). It is DERIVED from the resolved
   * descriptors and cached alongside services (gitignored services.json), never
   * committed to grpcview.json and not part of grpcview.store.v1.
   *
   * @generated from field: bytes descriptor_set = 6;
   */
  descriptorSet: Uint8Array;
};

/**
 * Describes the message grpcview.v1.Workspace.
 * Use `create(WorkspaceSchema)` to create a new message.
 */
export declare const WorkspaceSchema: GenMessage<Workspace>;

/**
 * ScriptKind classifies a saved script by how it is invoked. Mirrors the on-disk
 * grpcview.store.v1.ScriptKind.
 *
 * @generated from enum grpcview.v1.ScriptKind
 */
export enum ScriptKind {
  /**
   * @generated from enum value: SCRIPT_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SCRIPT_KIND_GENERATOR = 1;
   */
  GENERATOR = 1,

  /**
   * @generated from enum value: SCRIPT_KIND_MIDDLEWARE = 2;
   */
  MIDDLEWARE = 2,

  /**
   * @generated from enum value: SCRIPT_KIND_SCENARIO = 3;
   */
  SCENARIO = 3,
}

/**
 * Describes the enum grpcview.v1.ScriptKind.
 */
export declare const ScriptKindSchema: GenEnum<ScriptKind>;

