// @generated by protoc-gen-connect-es v1.6.1 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file service/proto/v1/service.proto (package grpcview.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddRequest, AddResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service grpcview.v1.Workspace
 */
export declare const Workspace: {
  readonly typeName: "grpcview.v1.Workspace",
  readonly methods: {
    /**
     * @generated from rpc grpcview.v1.Workspace.Add
     */
    readonly add: {
      readonly name: "Add",
      readonly I: typeof AddRequest,
      readonly O: typeof AddResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

