syntax = "proto3";

package grpcview.v1;

import "google/protobuf/descriptor.proto";
import "google/protobuf/struct.proto";
import "service/proto/v1/workspace.proto";

option go_package = "github.com/ramilmsh/grpcview/service/proto/v1;grpcviewv1";

message AddDescriptorSourceRequest {
  oneof source {
    bytes descriptor_set = 1;
    Server reflection = 2;
  }
}

message AddDescriptorSourceResponse {
  WorkspaceSnapshot workspace = 1;
}

message GetWorkspaceRequest {
  string name = 1;
}

message GetWorkspaceResponse {
  WorkspaceSnapshot workspace = 1;
}

service Workspace {
  rpc AddDescriptorSource(AddDescriptorSourceRequest) returns (AddDescriptorSourceResponse);
  rpc GetWorkspace(GetWorkspaceRequest) returns (GetWorkspaceResponse);
}
