// @generated by protoc-gen-es v2.2.3 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file service/proto/v1/service.proto (package grpcview.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { FileDescriptorSet } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file service/proto/v1/service.proto.
 */
export declare const file_service_proto_v1_service: GenFile;

/**
 * @generated from message grpcview.v1.Server
 */
export declare type Server = Message<"grpcview.v1.Server"> & {
  /**
   * @generated from field: string host = 1;
   */
  host: string;

  /**
   * @generated from field: int32 port = 2;
   */
  port: number;

  /**
   * @generated from field: optional grpcview.v1.Server.TLS tls = 3;
   */
  tls?: Server_TLS;
};

/**
 * Describes the message grpcview.v1.Server.
 * Use `create(ServerSchema)` to create a new message.
 */
export declare const ServerSchema: GenMessage<Server>;

/**
 * @generated from message grpcview.v1.Server.TLS
 */
export declare type Server_TLS = Message<"grpcview.v1.Server.TLS"> & {
};

/**
 * Describes the message grpcview.v1.Server.TLS.
 * Use `create(Server_TLSSchema)` to create a new message.
 */
export declare const Server_TLSSchema: GenMessage<Server_TLS>;

/**
 * @generated from message grpcview.v1.AddRequest
 */
export declare type AddRequest = Message<"grpcview.v1.AddRequest"> & {
  /**
   * @generated from oneof grpcview.v1.AddRequest.source
   */
  source: {
    /**
     * @generated from field: google.protobuf.FileDescriptorSet descriptor_set = 1;
     */
    value: FileDescriptorSet;
    case: "descriptorSet";
  } | {
    /**
     * @generated from field: grpcview.v1.Server reflection = 2;
     */
    value: Server;
    case: "reflection";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message grpcview.v1.AddRequest.
 * Use `create(AddRequestSchema)` to create a new message.
 */
export declare const AddRequestSchema: GenMessage<AddRequest>;

/**
 * @generated from message grpcview.v1.AddResponse
 */
export declare type AddResponse = Message<"grpcview.v1.AddResponse"> & {
  /**
   * @generated from field: repeated grpcview.v1.AddResponse.Service services = 1;
   */
  services: AddResponse_Service[];
};

/**
 * Describes the message grpcview.v1.AddResponse.
 * Use `create(AddResponseSchema)` to create a new message.
 */
export declare const AddResponseSchema: GenMessage<AddResponse>;

/**
 * @generated from message grpcview.v1.AddResponse.Message
 */
export declare type AddResponse_Message = Message<"grpcview.v1.AddResponse.Message"> & {
  /**
   * @generated from field: string package = 1;
   */
  package: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional google.protobuf.Struct schema = 3;
   */
  schema?: JsonObject;
};

/**
 * Describes the message grpcview.v1.AddResponse.Message.
 * Use `create(AddResponse_MessageSchema)` to create a new message.
 */
export declare const AddResponse_MessageSchema: GenMessage<AddResponse_Message>;

/**
 * @generated from message grpcview.v1.AddResponse.Method
 */
export declare type AddResponse_Method = Message<"grpcview.v1.AddResponse.Method"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: grpcview.v1.AddResponse.Message input = 2;
   */
  input?: AddResponse_Message;

  /**
   * @generated from field: grpcview.v1.AddResponse.Message output = 3;
   */
  output?: AddResponse_Message;
};

/**
 * Describes the message grpcview.v1.AddResponse.Method.
 * Use `create(AddResponse_MethodSchema)` to create a new message.
 */
export declare const AddResponse_MethodSchema: GenMessage<AddResponse_Method>;

/**
 * @generated from message grpcview.v1.AddResponse.Service
 */
export declare type AddResponse_Service = Message<"grpcview.v1.AddResponse.Service"> & {
  /**
   * @generated from field: string package = 1;
   */
  package: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: repeated grpcview.v1.AddResponse.Method methods = 3;
   */
  methods: AddResponse_Method[];
};

/**
 * Describes the message grpcview.v1.AddResponse.Service.
 * Use `create(AddResponse_ServiceSchema)` to create a new message.
 */
export declare const AddResponse_ServiceSchema: GenMessage<AddResponse_Service>;

/**
 * @generated from service grpcview.v1.Workspace
 */
export declare const Workspace: GenService<{
  /**
   * @generated from rpc grpcview.v1.Workspace.Add
   */
  add: {
    methodKind: "unary";
    input: typeof AddRequestSchema;
    output: typeof AddResponseSchema;
  },
}>;

