syntax = "proto3";

package grpcview.v1;

import "google/protobuf/descriptor.proto";

option go_package = "github.com/ramilmsh/grpcview/service/proto/v1;grpcviewv1";

message Server {
    message TLS {}

    string host = 1;
    int32 port = 2;
    TLS tls = 3;
}

message AddRequest {
    oneof source {
        google.protobuf.FileDescriptorSet descriptor_set = 1;
        Server reflection = 2;
    }
}

message AddResponse {
    google.protobuf.FileDescriptorSet descriptor_set = 1;
}

service Workspace {
    rpc Add(AddRequest) returns (AddResponse);
}
