// @generated by protoc-gen-connect-query v2.2.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file service/proto/v1/service.proto (package grpcview.v1, syntax proto3)
/* eslint-disable */

import { Workspace } from "./service_pb";

/**
 * @generated from rpc grpcview.v1.Workspace.Add
 */
export const add: (typeof Workspace)["method"]["add"];
