// @generated by protoc-gen-es v2.10.2 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file service/proto/v1/service.proto (package grpcview.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Server, Service } from "./workspace_pb";

/**
 * Describes the file service/proto/v1/service.proto.
 */
export declare const file_service_proto_v1_service: GenFile;

/**
 * @generated from message grpcview.v1.AddRequest
 */
export declare type AddRequest = Message<"grpcview.v1.AddRequest"> & {
  /**
   * @generated from oneof grpcview.v1.AddRequest.source
   */
  source: {
    /**
     * @generated from field: bytes descriptor_set = 1;
     */
    value: Uint8Array;
    case: "descriptorSet";
  } | {
    /**
     * @generated from field: grpcview.v1.Server reflection = 2;
     */
    value: Server;
    case: "reflection";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message grpcview.v1.AddRequest.
 * Use `create(AddRequestSchema)` to create a new message.
 */
export declare const AddRequestSchema: GenMessage<AddRequest>;

/**
 * @generated from message grpcview.v1.AddResponse
 */
export declare type AddResponse = Message<"grpcview.v1.AddResponse"> & {
  /**
   * @generated from field: repeated grpcview.v1.Service services = 1;
   */
  services: Service[];
};

/**
 * Describes the message grpcview.v1.AddResponse.
 * Use `create(AddResponseSchema)` to create a new message.
 */
export declare const AddResponseSchema: GenMessage<AddResponse>;

/**
 * @generated from service grpcview.v1.Workspace
 */
export declare const Workspace: GenService<{
  /**
   * @generated from rpc grpcview.v1.Workspace.Add
   */
  add: {
    methodKind: "unary";
    input: typeof AddRequestSchema;
    output: typeof AddResponseSchema;
  },
}>;

