// @generated by protoc-gen-connect-es v1.6.1 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file service/proto/v1/service.proto (package grpcview.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Hello } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service grpcview.v1.Service
 */
export declare const Service: {
  readonly typeName: "grpcview.v1.Service",
  readonly methods: {
    /**
     * @generated from rpc grpcview.v1.Service.SayHello
     */
    readonly sayHello: {
      readonly name: "SayHello",
      readonly I: typeof Hello,
      readonly O: typeof Hello,
      readonly kind: MethodKind.Unary,
    },
  }
};

