// @generated by protoc-gen-es v2.2.3 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file service/proto/v1/service.proto (package grpcview.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/proto/v1/service.proto.
 */
export declare const file_service_proto_v1_service: GenFile;

/**
 * @generated from message grpcview.v1.Hello
 */
export declare type Hello = Message<"grpcview.v1.Hello"> & {
  /**
   * @generated from field: string a = 1;
   */
  a: string;
};

/**
 * Describes the message grpcview.v1.Hello.
 * Use `create(HelloSchema)` to create a new message.
 */
export declare const HelloSchema: GenMessage<Hello>;

/**
 * @generated from service grpcview.v1.Service
 */
export declare const Service: GenService<{
  /**
   * @generated from rpc grpcview.v1.Service.SayHello
   */
  sayHello: {
    methodKind: "unary";
    input: typeof HelloSchema;
    output: typeof HelloSchema;
  },
}>;

