// @generated by protoc-gen-es v2.10.2 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file service/proto/v1/workspace.proto (package grpcview.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message as Message$1 } from "@bufbuild/protobuf";
import type { Any, Duration, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file service/proto/v1/workspace.proto.
 */
export declare const file_service_proto_v1_workspace: GenFile;

/**
 * Status is a copy of google.rpc.Status, this is a hack, because we can't import google/rpc/status.proto for rules_ts
 *
 * @generated from message grpcview.v1.Status
 */
export declare type Status = Message$1<"grpcview.v1.Status"> & {
  /**
   * @generated from field: int32 code = 1;
   */
  code: number;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: repeated google.protobuf.Any details = 3;
   */
  details: Any[];
};

/**
 * Describes the message grpcview.v1.Status.
 * Use `create(StatusSchema)` to create a new message.
 */
export declare const StatusSchema: GenMessage<Status>;

/**
 * @generated from message grpcview.v1.Server
 */
export declare type Server = Message$1<"grpcview.v1.Server"> & {
  /**
   * @generated from field: string host = 1;
   */
  host: string;

  /**
   * @generated from field: int32 port = 2;
   */
  port: number;

  /**
   * @generated from field: optional grpcview.v1.Server.TLS tls = 3;
   */
  tls?: Server_TLS;
};

/**
 * Describes the message grpcview.v1.Server.
 * Use `create(ServerSchema)` to create a new message.
 */
export declare const ServerSchema: GenMessage<Server>;

/**
 * @generated from message grpcview.v1.Server.TLS
 */
export declare type Server_TLS = Message$1<"grpcview.v1.Server.TLS"> & {
};

/**
 * Describes the message grpcview.v1.Server.TLS.
 * Use `create(Server_TLSSchema)` to create a new message.
 */
export declare const Server_TLSSchema: GenMessage<Server_TLS>;

/**
 * @generated from message grpcview.v1.Message
 */
export declare type Message = Message$1<"grpcview.v1.Message"> & {
  /**
   * @generated from field: string package = 1;
   */
  package: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional google.protobuf.Struct schema = 3;
   */
  schema?: JsonObject;
};

/**
 * Describes the message grpcview.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export declare const MessageSchema: GenMessage<Message>;

/**
 * @generated from message grpcview.v1.Method
 */
export declare type Method = Message$1<"grpcview.v1.Method"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: grpcview.v1.Message input = 2;
   */
  input?: Message;

  /**
   * @generated from field: grpcview.v1.Message output = 3;
   */
  output?: Message;
};

/**
 * Describes the message grpcview.v1.Method.
 * Use `create(MethodSchema)` to create a new message.
 */
export declare const MethodSchema: GenMessage<Method>;

/**
 * @generated from message grpcview.v1.Service
 */
export declare type Service = Message$1<"grpcview.v1.Service"> & {
  /**
   * @generated from field: string package = 1;
   */
  package: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: repeated grpcview.v1.Method methods = 3;
   */
  methods: Method[];
};

/**
 * Describes the message grpcview.v1.Service.
 * Use `create(ServiceSchema)` to create a new message.
 */
export declare const ServiceSchema: GenMessage<Service>;

/**
 * @generated from message grpcview.v1.DescriptorSource
 */
export declare type DescriptorSource = Message$1<"grpcview.v1.DescriptorSource"> & {
  /**
   * @generated from oneof grpcview.v1.DescriptorSource.source
   */
  source: {
    /**
     * @generated from field: bytes descriptor_set = 1;
     */
    value: Uint8Array;
    case: "descriptorSet";
  } | {
    /**
     * @generated from field: grpcview.v1.Server reflection = 2;
     */
    value: Server;
    case: "reflection";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message grpcview.v1.DescriptorSource.
 * Use `create(DescriptorSourceSchema)` to create a new message.
 */
export declare const DescriptorSourceSchema: GenMessage<DescriptorSource>;

/**
 * @generated from message grpcview.v1.Folder
 */
export declare type Folder = Message$1<"grpcview.v1.Folder"> & {
  /**
   * @generated from field: repeated grpcview.v1.Item items = 1;
   */
  items: Item[];
};

/**
 * Describes the message grpcview.v1.Folder.
 * Use `create(FolderSchema)` to create a new message.
 */
export declare const FolderSchema: GenMessage<Folder>;

/**
 * @generated from message grpcview.v1.Request
 */
export declare type Request = Message$1<"grpcview.v1.Request"> & {
  /**
   * @generated from field: grpcview.v1.Service service = 1;
   */
  service?: Service;

  /**
   * @generated from field: grpcview.v1.Method method = 2;
   */
  method?: Method;

  /**
   * @generated from field: bytes request = 3;
   */
  request: Uint8Array;

  /**
   * @generated from field: repeated grpcview.v1.Request.Response response = 4;
   */
  response: Request_Response[];
};

/**
 * Describes the message grpcview.v1.Request.
 * Use `create(RequestSchema)` to create a new message.
 */
export declare const RequestSchema: GenMessage<Request>;

/**
 * @generated from message grpcview.v1.Request.Response
 */
export declare type Request_Response = Message$1<"grpcview.v1.Request.Response"> & {
  /**
   * @generated from field: grpcview.v1.Status status = 1;
   */
  status?: Status;

  /**
   * @generated from field: bytes response = 2;
   */
  response: Uint8Array;

  /**
   * @generated from field: google.protobuf.Struct metadata = 3;
   */
  metadata?: JsonObject;

  /**
   * @generated from field: google.protobuf.Duration latency = 4;
   */
  latency?: Duration;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 5;
   */
  timestamp?: Timestamp;
};

/**
 * Describes the message grpcview.v1.Request.Response.
 * Use `create(Request_ResponseSchema)` to create a new message.
 */
export declare const Request_ResponseSchema: GenMessage<Request_Response>;

/**
 * @generated from message grpcview.v1.Item
 */
export declare type Item = Message$1<"grpcview.v1.Item"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from oneof grpcview.v1.Item.content
   */
  content: {
    /**
     * @generated from field: grpcview.v1.Folder folder = 2;
     */
    value: Folder;
    case: "folder";
  } | {
    /**
     * @generated from field: grpcview.v1.Request request = 3;
     */
    value: Request;
    case: "request";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message grpcview.v1.Item.
 * Use `create(ItemSchema)` to create a new message.
 */
export declare const ItemSchema: GenMessage<Item>;

/**
 * @generated from message grpcview.v1.WorkspaceSnapshot
 */
export declare type WorkspaceSnapshot = Message$1<"grpcview.v1.WorkspaceSnapshot"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: repeated grpcview.v1.Item items = 2;
   */
  items: Item[];

  /**
   * @generated from field: repeated grpcview.v1.DescriptorSource sources = 3;
   */
  sources: DescriptorSource[];

  /**
   * @generated from field: repeated grpcview.v1.Service services = 4;
   */
  services: Service[];
};

/**
 * Describes the message grpcview.v1.WorkspaceSnapshot.
 * Use `create(WorkspaceSnapshotSchema)` to create a new message.
 */
export declare const WorkspaceSnapshotSchema: GenMessage<WorkspaceSnapshot>;

