load("@aspect_rules_ts//ts:proto.bzl", "ts_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_go//proto:def.bzl", "go_proto_library")

proto_library(
    name = "grpcviewv1_proto",
    srcs = [
        "service.proto",
        "workspace.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@protobuf//:any_proto",
        "@protobuf//:duration_proto",
        "@protobuf//:struct_proto",
        "@protobuf//:timestamp_proto",
    ],
)

go_proto_library(
    name = "grpcviewv1_go_proto",
    compilers = [
        "@rules_go//proto:go_proto",
        "//tools:connect_go_proto_compiler",
    ],
    importpath = "codeberg.org/ramilmsh/grpcview/grpcview/v1",
    proto = ":grpcviewv1_proto",
    visibility = ["//visibility:public"],
)

ts_proto_library(
    name = "grpcviewv1_proto_ts",
    gen_connect_query = True,
    gen_connect_query_service_mapping = {
        "service.proto": [
            "WorkspaceService",
            "ServerService",
        ],
    },
    node_modules = "//:node_modules",
    proto = ":grpcviewv1_proto",
    proto_srcs = [
        "service.proto",
        "workspace.proto",
    ],
    # keep
    visibility = ["//visibility:public"],
)
