// @generated by protoc-gen-connect-query v2.2.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file grpcview/v1/service.proto (package grpcview.v1, syntax proto3)
/* eslint-disable */

import { ServerService } from "./service_pb";

/**
 * Never fails. Answering it at all is what proves a listener is this workspace's.
 *
 * @generated from rpc grpcview.v1.ServerService.ServerInfo
 */
export const serverInfo: typeof ServerService["method"]["serverInfo"];
/**
 * Returns first, then stops accepting, drains in flight requests and unlinks the
 * registration. Asking over the wire is why the design never has to signal a pid.
 *
 * @generated from rpc grpcview.v1.ServerService.Shutdown
 */
export const shutdown: typeof ServerService["method"]["shutdown"];
/**
 * Every server registered on this machine, this one included, each verified over the
 * wire before it is reported running. Reads the registry, never a process table.
 *
 * @generated from rpc grpcview.v1.ServerService.ListServers
 */
export const listServers: typeof ServerService["method"]["listServers"];
/**
 * Asks another workspace's server to exit, after verifying it is that workspace's, and
 * waits for it to go. Naming this server's own root is Shutdown.
 *
 * @generated from rpc grpcview.v1.ServerService.StopServer
 */
export const stopServer: typeof ServerService["method"]["stopServer"];
