// @generated by protoc-gen-es v2.12.1 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file grpcview/v1/workspace.proto (package grpcview.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message as Message$1 } from "@bufbuild/protobuf";
import type { Any, Duration, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file grpcview/v1/workspace.proto.
 */
export declare const file_grpcview_v1_workspace: GenFile;

/**
 * Copy of google.rpc.Status: rules_ts cannot import google/rpc/status.proto.
 *
 * @generated from message grpcview.v1.Status
 */
export declare type Status = Message$1<"grpcview.v1.Status"> & {
  /**
   * Canonical gRPC status code.
   *
   * @generated from field: int32 code = 1;
   */
  code: number;

  /**
   * Human-readable status message.
   *
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * Structured error details, as attached by the server.
   *
   * @generated from field: repeated google.protobuf.Any details = 3;
   */
  details: Any[];
};

/**
 * Describes the message grpcview.v1.Status.
 * Use `create(StatusSchema)` to create a new message.
 */
export declare const StatusSchema: GenMessage<Status>;

/**
 * A dial target for an RPC.
 *
 * @generated from message grpcview.v1.Server
 */
export declare type Server = Message$1<"grpcview.v1.Server"> & {
  /**
   * Dial string, host:port.
   *
   * @generated from field: string address = 1;
   */
  address: string;

  /**
   * Present dials with TLS.
   *
   * @generated from field: optional grpcview.v1.Server.TLS tls = 2;
   */
  tls?: Server_TLS | undefined;
};

/**
 * Describes the message grpcview.v1.Server.
 * Use `create(ServerSchema)` to create a new message.
 */
export declare const ServerSchema: GenMessage<Server>;

/**
 * Marker for a TLS-secured Server; presence, not fields, is the signal.
 *
 * @generated from message grpcview.v1.Server.TLS
 */
export declare type Server_TLS = Message$1<"grpcview.v1.Server.TLS"> & {
};

/**
 * Describes the message grpcview.v1.Server.TLS.
 * Use `create(Server_TLSSchema)` to create a new message.
 */
export declare const Server_TLSSchema: GenMessage<Server_TLS>;

/**
 * A protobuf message type, as reflected from a schema source.
 *
 * @generated from message grpcview.v1.Message
 */
export declare type Message = Message$1<"grpcview.v1.Message"> & {
  /**
   * Proto package, e.g. "grpcview.echo.v1".
   *
   * @generated from field: string package = 1;
   */
  package: string;

  /**
   * Unqualified message name.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Proto file path defining this message, e.g. proto/foo/v1/foo.proto.
   *
   * @generated from field: string file = 4;
   */
  file: string;
};

/**
 * Describes the message grpcview.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export declare const MessageSchema: GenMessage<Message>;

/**
 * An RPC method, as reflected from a schema source.
 *
 * @generated from message grpcview.v1.Method
 */
export declare type Method = Message$1<"grpcview.v1.Method"> & {
  /**
   * Unqualified method name.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Input message type.
   *
   * @generated from field: grpcview.v1.Message input = 2;
   */
  input?: Message | undefined;

  /**
   * Output message type.
   *
   * @generated from field: grpcview.v1.Message output = 3;
   */
  output?: Message | undefined;

  /**
   * Whether the client sends more than one message.
   *
   * @generated from field: bool client_streaming = 4;
   */
  clientStreaming: boolean;

  /**
   * Whether the server sends more than one message.
   *
   * @generated from field: bool server_streaming = 5;
   */
  serverStreaming: boolean;
};

/**
 * Describes the message grpcview.v1.Method.
 * Use `create(MethodSchema)` to create a new message.
 */
export declare const MethodSchema: GenMessage<Method>;

/**
 * A gRPC service, as reflected from a schema source.
 *
 * @generated from message grpcview.v1.Service
 */
export declare type Service = Message$1<"grpcview.v1.Service"> & {
  /**
   * Proto package, e.g. "grpcview.echo.v1".
   *
   * @generated from field: string package = 1;
   */
  package: string;

  /**
   * Unqualified service name.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Every RPC method on this service.
   *
   * @generated from field: repeated grpcview.v1.Method methods = 3;
   */
  methods: Method[];

  /**
   * First reflection source serving it — the default invoke target; unset if none.
   *
   * @generated from field: optional grpcview.v1.Server source = 4;
   */
  source?: Server | undefined;
};

/**
 * Describes the message grpcview.v1.Service.
 * Use `create(ServiceSchema)` to create a new message.
 */
export declare const ServiceSchema: GenMessage<Service>;

/**
 * Priority-ordered: the first source to define a file, or serve a service, wins.
 *
 * @generated from message grpcview.v1.DescriptorSource
 */
export declare type DescriptorSource = Message$1<"grpcview.v1.DescriptorSource"> & {
  /**
   * "reflection:<address>" (+"+tls"), "upload:<file name>" or "bazel:<//pkg:target>";
   * adding an existing id refreshes that source in place.
   *
   * @generated from field: string id = 3;
   */
  id: string;

  /**
   * Which kind of source this is.
   *
   * @generated from oneof grpcview.v1.DescriptorSource.source
   */
  source: {
    /**
     * A human-uploaded FileDescriptorSet.
     *
     * @generated from field: grpcview.v1.Upload upload = 1;
     */
    value: Upload;
    case: "upload";
  } | {
    /**
     * A live server reflected over the wire.
     *
     * @generated from field: grpcview.v1.Server reflection = 2;
     */
    value: Server;
    case: "reflection";
  } | {
    /**
     * A Bazel label that builds its own descriptor set.
     *
     * @generated from field: grpcview.v1.Bazel bazel = 7;
     */
    value: Bazel;
    case: "bazel";
  } | { case: undefined; value?: undefined };

  /**
   * What this source last resolved to; unset before the first resolve.
   *
   * @generated from field: grpcview.v1.Resolved resolved = 4;
   */
  resolved?: Resolved | undefined;

  /**
   * Read-only: server-set, ignored on input. No RPC edits a WORKSPACE source's
   * config in place; a WORKSPACE row with no oneof arm is an undefined reference
   * and Resolved.error says so.
   *
   * @generated from field: grpcview.v1.SourceOrigin origin = 6;
   */
  origin: SourceOrigin;

  /**
   * Commit this source's descriptors as descriptors/<slug>-<hash of id>.json
   * instead of caching them in local state. Changes only WHERE the store writes.
   *
   * @generated from field: bool commit_descriptors = 5;
   */
  commitDescriptors: boolean;
};

/**
 * Describes the message grpcview.v1.DescriptorSource.
 * Use `create(DescriptorSourceSchema)` to create a new message.
 */
export declare const DescriptorSourceSchema: GenMessage<DescriptorSource>;

/**
 * The descriptor bytes are never sent to the client, only this file name.
 *
 * @generated from message grpcview.v1.Upload
 */
export declare type Upload = Message$1<"grpcview.v1.Upload"> & {
  /**
   * Identity of this upload; re-uploading under the same name refreshes it.
   *
   * @generated from field: string file_name = 1;
   */
  fileName: string;

  /**
   * Root-relative refresh recipe; empty when the bytes came from a browser file
   * picker. Never identity — the file name is, so a git mv edits this recipe.
   *
   * @generated from field: string path = 2;
   */
  path: string;
};

/**
 * Describes the message grpcview.v1.Upload.
 * Use `create(UploadSchema)` to create a new message.
 */
export declare const UploadSchema: GenMessage<Upload>;

/**
 * A canonical bazel label whose default outputs are descriptor sets. Unlike an
 * upload it can PRODUCE its bytes: refreshing it builds the label.
 *
 * @generated from message grpcview.v1.Bazel
 */
export declare type Bazel = Message$1<"grpcview.v1.Bazel"> & {
  /**
   * Canonical label, e.g. "//pkg:target".
   *
   * @generated from field: string label = 1;
   */
  label: string;
};

/**
 * Describes the message grpcview.v1.Bazel.
 * Use `create(BazelSchema)` to create a new message.
 */
export declare const BazelSchema: GenMessage<Bazel>;

/**
 * What one source last resolved to.
 *
 * @generated from message grpcview.v1.Resolved
 */
export declare type Resolved = Message$1<"grpcview.v1.Resolved"> & {
  /**
   * Number of files in the resolved descriptor set.
   *
   * @generated from field: int32 file_count = 1;
   */
  fileCount: number;

  /**
   * Every fully-qualified service name the resolved descriptor set defines.
   *
   * @generated from field: repeated string service_names = 2;
   */
  serviceNames: string[];

  /**
   * Subset of service_names whose descriptors the collection takes from here.
   *
   * @generated from field: repeated string won_service_names = 3;
   */
  wonServiceNames: string[];

  /**
   * Why the last resolve failed; empty when it succeeded.
   *
   * @generated from field: string error = 4;
   */
  error: string;
};

/**
 * Describes the message grpcview.v1.Resolved.
 * Use `create(ResolvedSchema)` to create a new message.
 */
export declare const ResolvedSchema: GenMessage<Resolved>;

/**
 * A directory of Items — folders and requests — in the tree.
 *
 * @generated from message grpcview.v1.Folder
 */
export declare type Folder = Message$1<"grpcview.v1.Folder"> & {
  /**
   * Ordered children.
   *
   * @generated from field: repeated grpcview.v1.Item items = 1;
   */
  items: Item[];

  /**
   * TypeScript module feeding the gv.metadata.inherit() ancestor chain.
   *
   * @generated from field: string draft_metadata_script = 2;
   */
  draftMetadataScript: string;
};

/**
 * Describes the message grpcview.v1.Folder.
 * Use `create(FolderSchema)` to create a new message.
 */
export declare const FolderSchema: GenMessage<Folder>;

/**
 * One past invocation of a request, as recorded server-side.
 *
 * @generated from message grpcview.v1.History
 */
export declare type History = Message$1<"grpcview.v1.History"> & {
  /**
   * What was sent.
   *
   * @generated from field: grpcview.v1.History.Request request = 1;
   */
  request?: History_Request | undefined;

  /**
   * What came back.
   *
   * @generated from field: grpcview.v1.History.Response response = 2;
   */
  response?: History_Response | undefined;
};

/**
 * Describes the message grpcview.v1.History.
 * Use `create(HistorySchema)` to create a new message.
 */
export declare const HistorySchema: GenMessage<History>;

/**
 * What was sent.
 *
 * @generated from message grpcview.v1.History.Request
 */
export declare type History_Request = Message$1<"grpcview.v1.History.Request"> & {
  /**
   * Fully qualified service name called.
   *
   * @generated from field: string service = 1;
   */
  service: string;

  /**
   * Method name on `service` called.
   *
   * @generated from field: string method = 2;
   */
  method: string;

  /**
   * Body sent, as protojson bytes.
   *
   * @generated from field: bytes body = 3;
   */
  body: Uint8Array;

  /**
   * Request metadata (headers) sent.
   *
   * @generated from field: google.protobuf.Struct metadata = 4;
   */
  metadata?: JsonObject | undefined;
};

/**
 * Describes the message grpcview.v1.History.Request.
 * Use `create(History_RequestSchema)` to create a new message.
 */
export declare const History_RequestSchema: GenMessage<History_Request>;

/**
 * What came back.
 *
 * @generated from message grpcview.v1.History.Response
 */
export declare type History_Response = Message$1<"grpcview.v1.History.Response"> & {
  /**
   * Final gRPC status.
   *
   * @generated from field: grpcview.v1.Status status = 1;
   */
  status?: Status | undefined;

  /**
   * Body received, as protojson bytes.
   *
   * @generated from field: bytes response = 2;
   */
  response: Uint8Array;

  /**
   * Response metadata (trailers) received.
   *
   * @generated from field: google.protobuf.Struct metadata = 3;
   */
  metadata?: JsonObject | undefined;

  /**
   * Wall-clock duration of the call.
   *
   * @generated from field: google.protobuf.Duration latency = 4;
   */
  latency?: Duration | undefined;

  /**
   * When the call was made.
   *
   * @generated from field: google.protobuf.Timestamp timestamp = 5;
   */
  timestamp?: Timestamp | undefined;
};

/**
 * Describes the message grpcview.v1.History.Response.
 * Use `create(History_ResponseSchema)` to create a new message.
 */
export declare const History_ResponseSchema: GenMessage<History_Response>;

/**
 * A saved request in the tree, addressable and invocable independently of any one run.
 *
 * @generated from message grpcview.v1.Request
 */
export declare type Request = Message$1<"grpcview.v1.Request"> & {
  /**
   * Display name.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Fully qualified service name this request calls.
   *
   * @generated from field: string service = 2;
   */
  service: string;

  /**
   * Method name on `service` this request calls.
   *
   * @generated from field: string method = 3;
   */
  method: string;

  /**
   * The request message as a JSON object, or a TypeScript module default-exporting one.
   *
   * @generated from field: string draft_body = 4;
   */
  draftBody: string;

  /**
   * Most recent first.
   *
   * @generated from field: repeated grpcview.v1.History history = 6;
   */
  history: History[];

  /**
   * Ordered display names of the MIDDLEWARE scripts run before the call.
   *
   * @generated from field: repeated string middleware = 7;
   */
  middleware: string[];

  /**
   * TypeScript module returning {[key: string]: string[]}, evaluated on invoke.
   *
   * @generated from field: string draft_metadata_script = 9;
   */
  draftMetadataScript: string;

  /**
   * Unset means "use the collection's first reflection source".
   *
   * @generated from field: optional grpcview.v1.Server target = 10;
   */
  target?: Server | undefined;
};

/**
 * Describes the message grpcview.v1.Request.
 * Use `create(RequestSchema)` to create a new message.
 */
export declare const RequestSchema: GenMessage<Request>;

/**
 * A live invoke's outcome — richer than History.Response, which is what got persisted.
 *
 * @generated from message grpcview.v1.Request.Response
 */
export declare type Request_Response = Message$1<"grpcview.v1.Request.Response"> & {
  /**
   * Final gRPC status.
   *
   * @generated from field: grpcview.v1.Status status = 1;
   */
  status?: Status | undefined;

  /**
   * Body received, as protojson bytes.
   *
   * @generated from field: bytes response = 2;
   */
  response: Uint8Array;

  /**
   * Request metadata (headers) sent.
   *
   * @generated from field: google.protobuf.Struct request_metadata = 3;
   */
  requestMetadata?: JsonObject | undefined;

  /**
   * Response metadata (trailers) received.
   *
   * @generated from field: google.protobuf.Struct response_metadata = 4;
   */
  responseMetadata?: JsonObject | undefined;

  /**
   * Wall-clock duration of the call.
   *
   * @generated from field: google.protobuf.Duration latency = 5;
   */
  latency?: Duration | undefined;

  /**
   * When the call was made.
   *
   * @generated from field: google.protobuf.Timestamp timestamp = 6;
   */
  timestamp?: Timestamp | undefined;
};

/**
 * Describes the message grpcview.v1.Request.Response.
 * Use `create(Request_ResponseSchema)` to create a new message.
 */
export declare const Request_ResponseSchema: GenMessage<Request_Response>;

/**
 * One entry in a Folder: either a nested Folder or a Request.
 *
 * @generated from message grpcview.v1.Item
 */
export declare type Item = Message$1<"grpcview.v1.Item"> & {
  /**
   * Display name.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Stable on-disk directory name: identity, not an address. A rename never
   * changes it, so UI state is keyed by it. Empty on the synthetic root item.
   *
   * @generated from field: string slug = 4;
   */
  slug: string;

  /**
   * Which kind of item this is.
   *
   * @generated from oneof grpcview.v1.Item.content
   */
  content: {
    /**
     * Present when this item is a folder.
     *
     * @generated from field: grpcview.v1.Folder folder = 2;
     */
    value: Folder;
    case: "folder";
  } | {
    /**
     * Present when this item is a saved request.
     *
     * @generated from field: grpcview.v1.Request request = 3;
     */
    value: Request;
    case: "request";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message grpcview.v1.Item.
 * Use `create(ItemSchema)` to create a new message.
 */
export declare const ItemSchema: GenMessage<Item>;

/**
 * A .ts file under the collection's scripts/ directory.
 *
 * @generated from message grpcview.v1.Script
 */
export declare type Script = Message$1<"grpcview.v1.Script"> & {
  /**
   * Collection-relative, slash-separated, with the extension: "scripts/uuid.ts".
   *
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * File contents.
   *
   * @generated from field: string source = 2;
   */
  source: string;
};

/**
 * Describes the message grpcview.v1.Script.
 * Use `create(ScriptSchema)` to create a new message.
 */
export declare const ScriptSchema: GenMessage<Script>;

/**
 * A collection: its tree, its schema sources, and its scripts.
 *
 * @generated from message grpcview.v1.Collection
 */
export declare type Collection = Message$1<"grpcview.v1.Collection"> & {
  /**
   * Display name.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Workspace-relative path this collection is addressed by; "." is the root.
   * Addressing only, never written to disk: the id IS the disk location.
   *
   * @generated from field: string id = 7;
   */
  id: string;

  /**
   * Root of the tree.
   *
   * @generated from field: grpcview.v1.Item item = 2;
   */
  item?: Item | undefined;

  /**
   * Priority-ordered schema sources.
   *
   * @generated from field: repeated grpcview.v1.DescriptorSource sources = 3;
   */
  sources: DescriptorSource[];

  /**
   * Derived by the priority merge: one entry per fully-qualified service.
   *
   * @generated from field: repeated grpcview.v1.Service services = 4;
   */
  services: Service[];

  /**
   * Scripts saved under this collection's scripts/ directory.
   *
   * @generated from field: repeated grpcview.v1.Script scripts = 5;
   */
  scripts: Script[];

  /**
   * Merged, deduped FileDescriptorSet; derived and cached, never persisted.
   *
   * @generated from field: bytes descriptor_set = 6;
   */
  descriptorSet: Uint8Array;
};

/**
 * Describes the message grpcview.v1.Collection.
 * Use `create(CollectionSchema)` to create a new message.
 */
export declare const CollectionSchema: GenMessage<Collection>;

/**
 * Where a source's config lives: this collection's grpcview.json, or the
 * workspace manifest with the collection holding only a reference by id.
 *
 * @generated from enum grpcview.v1.SourceOrigin
 */
export enum SourceOrigin {
  /**
   * Unset; never a valid origin on a resolved DescriptorSource.
   *
   * @generated from enum value: SOURCE_ORIGIN_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Defined in the collection's own grpcview.json.
   *
   * @generated from enum value: SOURCE_ORIGIN_COLLECTION = 1;
   */
  COLLECTION = 1,

  /**
   * Defined in the workspace manifest, referenced here by id.
   *
   * @generated from enum value: SOURCE_ORIGIN_WORKSPACE = 2;
   */
  WORKSPACE = 2,
}

/**
 * Describes the enum grpcview.v1.SourceOrigin.
 */
export declare const SourceOriginSchema: GenEnum<SourceOrigin>;

