load("@rules_proto//proto:defs.bzl", "proto_descriptor_set", "proto_library")

# gazelle:go_generate_proto false
# gazelle:proto file

proto_library(
    name = "unittest_import_proto",
    srcs = ["unittest_import.proto"],
    visibility = ["//visibility:public"],
    deps = [":unittest_import_public_proto"],
)

proto_library(
    name = "unittest_import_public_proto",
    srcs = ["unittest_import_public.proto"],
    visibility = ["//visibility:public"],
)

proto_library(
    name = "unittest_proto3_proto",
    srcs = ["unittest_proto3.proto"],
    visibility = ["//visibility:public"],
    deps = [":unittest_import_proto"],
)

proto_descriptor_set(
    name = "unittest_proto3_descriptor_set",
    visibility = ["//visibility:public"],
    deps = [":unittest_proto3_proto"],
)
