load("@aspect_rules_esbuild//esbuild:defs.bzl", "esbuild")
load("//ui:defs.bzl", "ts_project")

ts_project(
    name = "workers",
    srcs = [
        "editor-worker-entry.ts",
        "json-worker-entry.ts",
        "ts-worker-entry.ts",
    ],
    declaration = True,
    no_emit = False,
    preserve_jsx = False,
    resolve_json_module = True,
    tsconfig = "//ui:tsconfig",
    visibility = ["//visibility:public"],
    deps = ["//ui:node_modules/monaco-editor"],
)

# keep
esbuild(
    name = "editor_worker",
    entry_point = "editor-worker-entry.ts",
    format = "iife",
    minify = True,
    output = "dist/editor.worker.js",
    platform = "browser",
    target = ["es2020"],
    visibility = ["//ui/src:__pkg__"],
    deps = [":workers"],
)

# keep
esbuild(
    name = "json_worker",
    entry_point = "json-worker-entry.ts",
    format = "iife",
    minify = True,
    output = "dist/json.worker.js",
    platform = "browser",
    target = ["es2020"],
    visibility = ["//ui/src:__pkg__"],
    deps = [":workers"],
)

# keep
esbuild(
    name = "ts_worker",
    entry_point = "ts-worker-entry.ts",
    format = "iife",
    minify = True,
    output = "dist/ts.worker.js",
    platform = "browser",
    target = ["es2020"],
    visibility = ["//ui/src:__pkg__"],
    deps = [":workers"],
)
