# gazelle:go_grpc_compilers @rules_go//proto:go_proto,@rules_go//proto:go_grpc_v2
# gazelle:go_proto_compilers @rules_go//proto:go_proto

load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_go//go:def.bzl", "go_library")
load("@rules_go//proto:def.bzl", "go_proto_library")

proto_library(
    name = "grpcviewechov1_proto",
    srcs = ["echo.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "grpcviewechov1_go_proto",
    compilers = [
        "@rules_go//proto:go_proto",
        "@rules_go//proto:go_grpc_v2",
    ],
    importpath = "codeberg.org/ramilmsh/grpcview/proto/grpcview/echo/v1",
    proto = ":grpcviewechov1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "echo",
    embed = [":grpcviewechov1_go_proto"],
    importpath = "codeberg.org/ramilmsh/grpcview/proto/grpcview/echo/v1",
    visibility = ["//visibility:public"],
)
