syntax = "proto3";

package grpcview.echo.v1;

option go_package = "codeberg.org/ramilmsh/grpcview/proto/grpcview/echo/v1;grpcviewechov1";

message EchoRequest {
  string message = 1;
  int32 count = 2;
}

message EchoResponse {
  string message = 1;
  int32 index = 2;
}

service EchoService {
  rpc Unary(EchoRequest) returns (EchoResponse);
  rpc ServerStream(EchoRequest) returns (stream EchoResponse);
  rpc ClientStream(stream EchoRequest) returns (EchoResponse);
  rpc BidiStream(stream EchoRequest) returns (stream EchoResponse);
}
