load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "store",
    srcs = [
        "codec.go",
        "convert.go",
        "discover.go",
        "fs.go",
        "layout.go",
        "scripts.go",
        "sources.go",
        "store.go",
    ],
    importpath = "codeberg.org/ramilmsh/grpcview/service/store",
    visibility = ["//visibility:public"],
    deps = [
        "//proto/grpcview/store/v1:store",
        "//proto/grpcview/v1:grpcview",
        "@com_github_go_git_go_git_v5//plumbing/format/gitignore",
        "@org_golang_google_protobuf//encoding/protojson",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//types/descriptorpb",
    ],
)

go_test(
    name = "store_test",
    srcs = [
        "discover_test.go",
        "scripts_test.go",
        "sources_test.go",
        "store_test.go",
    ],
    embed = [":store"],
    deps = [
        "//proto/grpcview/store/v1:store",
        "//proto/grpcview/v1:grpcview",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//types/descriptorpb",
    ],
)
