load("@aspect_bazel_lib//lib:copy_file.bzl", "copy_file")
load("@rules_go//go:def.bzl", "go_library")

copy_file(
    name = "unittest_proto3_descriptor_set",
    src = "//inspector/unittest_proto3:unittest_proto3_descriptor_set",
    out = "unittest_proto3_descriptor_set.pb",
)

go_library(
    name = "inspector",
    srcs = ["inspector.go"],
    importpath = "codeberg.org/ramilmsh/grpcview/inspector",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_invopop_jsonschema//:jsonschema",
        "@org_golang_google_protobuf//reflect/protoreflect",
    ],
)
