load("@aspect_gazelle_prebuilt//:def.bzl", "aspect_gazelle")
load("@multitool//:tools.bzl", "TOOLS")
load("@rules_go//proto:compiler.bzl", "go_proto_compiler")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

aspect_gazelle(
    name = "gazelle",
    languages = [
        "go",
        "proto",
        "js",
    ],
    repo_config = "@bazel_gazelle_go_repository_config//:WORKSPACE",
    visibility = ["//:__pkg__"],
    with_check = True,
)

sh_binary(
    name = "release",
    srcs = ["release.sh"],
    data = [
        TOOLS["gh"],
        "//service/cmd:release",
    ],
    deps = ["@rules_shell//shell/runfiles"],
)

go_proto_compiler(
    name = "connect_go_proto_compiler",
    options = ["package_suffix"],
    plugin = "@com_connectrpc_connect//cmd/protoc-gen-connect-go:protoc-gen-connect-go",
    suffix = ".connect.go",
    visibility = ["//visibility:public"],
    deps = ["@com_connectrpc_connect//:go_default_library"],
)
